### ISSUE TITLE
Remove multiple attribute via jquery on select tag

### ISSUE THREAD

**Issue by kamleshchandnani** [silviomoreto/bootstrap-select#1000]
How can i remove multiple attribute from the select tag via javascript or jquery? i am having 2 buttons ,if user clicks on 1st he can select multiple items in dropdown and as soon as he clicks 2nd button the multiple property should be disabled.

**Comment by caseyjhol** [comment]
Your best option is probably to call

```javascript
$('#selctpickerID').selectpicker({maxOptions: 1});
```
when the button is clicked. This keeps the multiple attribute on the select, but only allows 1 option to be selected. Closing this for now, but if it's a popular enough request I can re-open and allow the option to change the multiple attribute on the fly.

**Comment by rajat26** [comment]
maxoptions solves it but user experience is not good . As user has to unclick the option selected and then click the option he wants to select.
