### ISSUE TITLE
Live search doesn't work accurately with Boostrap 2

### ISSUE THREAD

**Issue by stakemura** [silviomoreto/bootstrap-select#1002]
Live search doesn't work accurately with Boostrap 2.
* Width of the search box is odd.
* Item filtering doesn't work.

Can you help me, please.
Thank you

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case?

**Comment by stakemura** [comment]
Thank you for reply.
The trouble #1 can be seen here https://jsfiddle.net/rtpdwpdg/2/
The trouble #2 seems to be Iocale-depended problem so I found it is not easy to reproduce.

**Comment by stakemura** [comment]
Please check https://jsfiddle.net/rtpdwpdg/2/ on Firefox.

**Comment by caseyjhol** [comment]
The width of the search box is simply an issue with the box-sizing property. In Bootstrap 3, it is set to border-box:

```CSS
* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```

We no longer support Bootstrap 3 out of the box, as it became too time consuming to make everything work with both versions, and Bootstrap 3 was released nearly 2 years ago. If you want to use bootstrap-select with BS2, I recommend looking at some of the CSS from a version of bootstrap-select older than v1.6.3.
