### ISSUE TITLE
issue when maxOptionsGrp is set to 1

### ISSUE THREAD

**Issue by wnwnzhou** [silviomoreto/bootstrap-select#1007]
When set the "data-max-options" for a group selection to 1, I think there is a bug in the code.
In function clickListener, the if block (maxOptionsGrp && maxOptionsGrp == 1),  when it tries to get he group ID, $this does not has the attribute 'optgroup', but its parent does.
So the line:
var optgroupID = $this.data('optgroup');
should be corrected to:
var optgroupID = $this.parent().data('optgroup');

**Comment by caseyjhol** [comment]
This was fixed in https://github.com/silviomoreto/bootstrap-select/commit/d288807fa2526306bc62f9e5349d2291e44512a7 and is working properly in master.
