### ISSUE TITLE
At least select one option when multiple

### ISSUE THREAD

**Issue by SemonCat** [silviomoreto/bootstrap-select#1010]
I want user at least select one option when multiple.

Is any possible to do that?

**Comment by caseyjhol** [comment]
I'm not really sure how something like this would be implemented as a feature. This is a validation thing on your end, and you'll want to check that the select has an option selected before submitting the form.

Something like:

```javascript
if ($('#select').val().length < 1) {
    alert('You must select at least one option.');
}
```

If we had built in callbacks when the select is closed, you could run the validation then. But that's a different feature, and is already somewhat supported:

```javascript
$('[data-id="select"]').parent().on('hidden.bs.dropdown', function (e) {
    alert('You must select at least one option.');
});
```
or
```javascript
$('.bootstrap-select').on('hidden.bs.dropdown', function (e) {
    alert('You must select at least one option.');
});

**Comment by SemonCat** [comment]
Thanks for your reply,

But What I want is that user can not cancel option when only one option left.

**Comment by caseyjhol** [comment]
Hrmm...that seems like poor UX. What if they want to deselect that option and select another option?

**Comment by SemonCat** [comment]
Sorry,I don't think too much.

Thanks for your notify.

**Comment by abhishekyadav9590** [comment]
### This code select at least one option selected. 
- Initialise Select Picker
`var SelectPicker=$('.yourSelector').selectpicker()`

- Listen for the change event on select

```
$('.yourSelector').on('changed.bs.select', function (e) {
   // check if no option is selected.
    if ($('#Id-of-select-tag').val().length < 1) {
      SelectPicker.selectpicker('val', 'Value of your desired option u wish to be selected');
    }
  });
```

**Comment by hshoja** [comment]
My solution to keep one item at least
You also can change `1` to any number you want

```js
   $(document).on("changed.bs.select", ".yourSelector", function () {
      if ($(".yourSelector").val().length === 1) {
        $(".yourSelector").parent().find("li .selected a").addClass(".disable-option");
      }
    });

```

```css
.disable-option {
    pointer-events: none;
    pointer-events: none;
    background-color: #e9ecef;
    color: #6c757d;
}

```

**Comment by avraam-inside** [comment]
> Hrmm...that seems like poor UX. What if they want to deselect that option and select another option?

There is nothing wrong, good UX.

First user will choose another one, then he will cancel the first one by repeated selection (the select all and deselect all buttons to help him)
