### ISSUE TITLE
Live search with <optgroup> keeps heading even if there are no options.

### ISSUE THREAD

**Issue by devangmundhra** [silviomoreto/bootstrap-select#1012]
When doing a live search, the `<optgroup>` headings remain making it difficult to search through relevant results.

For example, in the following example, searching for *Ket* will also show `Head1` and `Head3` even though they don't have any relevant results.

https://jsfiddle.net/83sktxjh/1/

Bootstrap 3.3.4 and Bootstrap-Select 1.6.3 versions used.

**Comment by caseyjhol** [comment]
Please upgrade to 1.6.5. This has been fixed.

**Comment by devangmundhra** [comment]
Thanks. My bad, I didn't check the release and picked up the files directly from the CDN links mentioned in README.md
