### ISSUE TITLE
Bug with keyboard shortcuts

### ISSUE THREAD

**Issue by ntucakovic** [silviomoreto/bootstrap-select#1013]
I have noticed a bug with your plugin regarding keyboard shortcuts in specific situations. For instance, they're not working when there's no live-search data attribute set (filter is disabled). 

I have initialized plugin on all select elements, and depending on select, setting some option for it (e.g. setting width / live-search attribute, size)

When there's no live-search keyboard arrows only go from top-bottom of the wrapping container (reacting to overflow-y, and moving scrolltop of container to top or to bottom of it) and not actually selecting the options within it.

If there's live-search, it works just fine. For now, I'm using live-search everywhere, because of this bug, but I'd rather see this resolved...

Bootstrap select 1.6.3
Bootstrap 3
jQuery 1.8.2

On Drupal 7, on all browsers.

Nothing in console to check out and I can't provide you with a test env. If you're not aware of the bug, I'll fork and try to figure out what's going on and get back to you.

**Comment by caseyjhol** [comment]
Please upgrade to 1.6.5 and tell me if the problem persists. However, it sounds like you're expecting the value of the select to change when using the arrows, correct? You have to either click on the option or type "Enter" or "Spacebar." If I'm mistaken, maybe you can elaborate on the problem?

**Comment by ntucakovic** [comment]
I'm expecting to be able to use arrows to navigate through options, which worked only if there was live-search active. Of course, then I'd press enter, and it would select accordingly. Well, none of it works that way if there's no filter/live-search parameter.

I'll update on 1.6.5 tomorrow

**Comment by caseyjhol** [comment]
Oh, sorry - haven't updated the version number in master and told you to try the wrong version. Try the latest verion in master (https://github.com/silviomoreto/bootstrap-select/tree/master/dist).

**Comment by ntucakovic** [comment]
Alright, this one works exactly like 1.6.3, keyboard works only if there's live-search.

Just tried the same setup without drupal, bootstrap v3.0.0, jQ 1.8.2, and 1.6.5 for bootstrap-select. Exact same bugs. 

Jumped to 1.11.3 jQ and it works as it should. So for some reason there's a problem with my version of jQuery. It just troubles me why would it work if there's a search initialized...

On 1.8.2 it isn't working, on 1.9 it is. So basically jQ needs to be 1.9.x

But it still is a bug, since keyboard works just fine on 1.8.2 IF there's live-search attribute set to select.

Thank you for your help!

**Comment by caseyjhol** [comment]
Please try it with 1.7.0-rc1 to see if it persists.

**Comment by ntucakovic** [comment]
will do. Need this to be production ready atm. Once I'm done with that, I'll experiment with newer version. And thank you for your help!

**Comment by caseyjhol** [comment]
This should officially be fixed, but let me know if it's still happening.

**Comment by vmula** [comment]
I have taken the latest and still see the keyboard issue

**Comment by ntucakovic** [comment]
Another bug... When I click enter while I'm in focus of the form (e.g. some other input in the form where there's bootstrap select plugin initialized as well), enter selects all options in first bootstrap select instance and then does what it's supposed to do, submit the form. Same goes if focus is in some other's bs element (for instance live search input) and press enter there. All options are selected of first instance in the form... Very awkward and annoying bug. I'll look it up and post back here.

**Comment by ntucakovic** [comment]
1.7.3 doesn't have those issues. I'll update in another thread if I find something. 1.6.5 had it.
