### ISSUE TITLE
Using this without full bootstrap

### ISSUE THREAD

**Issue by adyz** [silviomoreto/bootstrap-select#1015]
Hey Guys, 

Wonderful project you've got here!

I would like to use your module but I don't use bootstrap in my current project.

Is there any way to download only the required files for bootstrap for this module?

Thank you, 
Adrian

**Comment by caseyjhol** [comment]
You can customized a Bootstrap download to have only dropdown.js (which should be the only file needed). See http://getbootstrap.com/customize/?id=47f760ded8204535d90c.

**Comment by duffyjp** [comment]
I'm trying to do the same this @adyz wanted above.  I'm using the .css and .js from the CDN listed in the README, and the compiled bootstrap.js with dropdown checked.  I can't seem to find a standalone dropdown.js

This is all I get:  No JS errors.  Any hints?

![screen shot 2016-07-20 at 7 13 56 pm](https://cloud.githubusercontent.com/assets/382216/17007467/a13ab3ae-4eae-11e6-8c2c-5167f88f394c.png)

**Comment by caseyjhol** [comment]
For future reference, see http://getbootstrap.com/customize/?id=7830063837006f6fc84f instead.
