### ISSUE TITLE
Using bootstrap-select with glyphicon pro?

### ISSUE THREAD

**Issue by allthosemiles** [silviomoreto/bootstrap-select#1020]
For what I'm working on, we only include the full pro version of the glyphicons and not the halflings, but in the multi-select (and probably other areas) the halflings are being used. Is there a way to use the pro version and have the halfings version included somehow?

In the console I'm getting the message "/dependency/fonts/glyphicons-halflings-regular.ttf"

**Comment by allthosemiles** [comment]
Realized this was a mistake. For some reason the glyphicon wasn't displaying in the multi-select dropdown, but in the console there was a message I hadn't seen.

Carry on!

**Comment by caseyjhol** [comment]
Are you using Bootstrap from a CDN or are you hosting it yourself?

**Comment by allthosemiles** [comment]
Hosting it ourselves.

**Comment by caseyjhol** [comment]
Check http://getbootstrap.com/components/#glyphicons-how-to-use. bootstrap-select doesn't utilize any font specifically - it just uses the `glyphicon` class by default. If you're receiving errors, your font file probably isn't hosted in the correct location relative to your CSS file. Try using the Bootstrap files from http://www.bootstrapcdn.com/ to see if that resolves your issue. If it does, then you'll know there's an issue with how your files are hosted.
