### ISSUE TITLE
maxOptions per optgroup?

### ISSUE THREAD

**Issue by KrunchMuffin** [silviomoreto/bootstrap-select#1021]
I was looking at the docs and it showed data-max-options on both the select and the optgroup. I assumed you could control maxOptions per optgroup but I can't seem to get it working if it does. So, is maxOptions per optgroup an option?

**Comment by caseyjhol** [comment]
You have to set `data-max-options` on each optgroup in the HTML, as it currently can't be set via JS.

**Comment by KrunchMuffin** [comment]
Yes I understand that,  but I want to have one optgroup have 6 and another have 2. Can this  be done?

**Comment by caseyjhol** [comment]
Yes, you set `data-max-options` on each optgroup.

```html
  <select class="selectpicker" multiple >
    <optgroup label="Condiments" data-max-options="2">
      <option>Mustard</option>
      <option>Ketchup</option>
      <option>Relish</option>
    </optgroup>
    <optgroup label="Breads" data-max-options="4">
      <option>Plain</option>
      <option>Steamed</option>
      <option>Toasted</option>
      <option>Mustard</option>
      <option>Ketchup</option>
      <option>Relish</option>
    </optgroup>
  </select>

**Comment by KrunchMuffin** [comment]
ok, my bad, forgot the closing optgroup tag.
