### ISSUE TITLE
Live Search lags on mobile devices 

### ISSUE THREAD

**Issue by Ulimn** [silviomoreto/bootstrap-select#1024]
Hello!

I'm trying to use your plugin to select locations from  a drop-down list with live search enabled.
On desktop browsers, it works fine, but when using it on a mobile or tablet, it gets so choppy / laggy that it is unusable.
Tried it on Android and iOS devices and with various context as well.

If you'd like to reproduce the issue, just open the test.html in your repo and and start typing in the search field of the second select example. It is worse with a lot of options in the select.

Looks as if pressing a new key doesn't delete the previous action from the queue. Kinda strange.

Could you please look into it? :)
Thanks!

**Comment by llstarscreamll** [comment]
Hi!! Great plugin, I have been waiting for solution to this problem, I have the same unusable behaviour on mobile devices when I use live search, it allows only one letter, unless you use swype writing mode on mobile keyboard...

Please, fix it my friend!!

Thank you so much!!

**Comment by caseyjhol** [comment]
The live search feature has been overhauled in v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.
