### ISSUE TITLE
classes on optgroup don't carry over?

### ISSUE THREAD

**Issue by KrunchMuffin** [silviomoreto/bootstrap-select#1025]
I have a class to change the font of the optgroup, but it does not carry over to the generated code. Is the only way to be able to use it is to target it directly with CSS?

**Comment by tarlepp** [comment]
I have similar problem, any solutions for this?

**Comment by KrunchMuffin** [comment]
I just targeted the CSS directly with, in my case...

`.bootstrap-select.btn-group .dropdown-menu li.dropdown-header {
  font-size: 20px
}`

**Comment by tarlepp** [comment]
My use case is that I need to attach different classes to specified ```optgroup``` so your solution won't work on my case :(

**Comment by caseyjhol** [comment]
Use the CSS selector `[data-optgroup="1"]`.

**Comment by caseyjhol** [comment]
Classes added to the optgroup tag now get carried over to `dropdown-header` and `opt` within an optgroup.

```html
  <select class="selectpicker" multiple>
    <optgroup label="Condiments" class="optgroup-class">
      <option>Mustard</option>
      <option>Ketchup</option>
      <option>Relish</option>
    </optgroup>
  </select>
```
results in

```html
<ul class="dropdown-menu inner" role="menu">
	<li data-optgroup="1" class="dropdown-header optgroup-class">...</li>
	<li data-optgroup="1" data-original-index="0"><a class="optgroup-class">...</a></li>
	<li data-optgroup="1" data-original-index="1"><a class="optgroup-class">...</a></li>
	<li data-optgroup="1" data-original-index="2"><a class="optgroup-class">...</a></li>
</ul>
```

**Comment by KrunchMuffin** [comment]
thanks!

**Comment by tarlepp** [comment]
nice!
