### ISSUE TITLE
Add an initialize event

### ISSUE THREAD

**Issue by markcarver** [silviomoreto/bootstrap-select#1026]
Split off from #699 (Add events to listen for) which added several events, but not an `initialize` event.

This event is needed so that other plugins (like https://github.com/truckingsim/Ajax-Bootstrap-Select) can initialize properly without doing some weird hack (like a setTimeout).

**Comment by caseyjhol** [comment]
I played around with adding this...and will implement it soon. I couldn't figure out a way to make it work without wrapping `this.$element.trigger('init.bs.select')` in a 0ms setTimeout. It might be best just to add it that way for now so it at least exists, though, and worry about optimizing it later. I'll take another look at it.
