### ISSUE TITLE
Text Input in list

### ISSUE THREAD

**Issue by shiruken1** [silviomoreto/bootstrap-select#1028]
How about a text input for "other" selections, kind of like the filtering.

**Comment by caseyjhol** [comment]
See #847 and #935.

**Comment by shiruken1** [comment]
I included data-create-item="1", but got no text input. Also, if this feature, it should be in the docs, no?

**Comment by caseyjhol** [comment]
This feature isn't added yet. I closed this issue because it is a duplicate. Sorry for the confusion!
