### ISSUE TITLE
select first option element

### ISSUE THREAD

**Issue by mycroft84** [silviomoreto/bootstrap-select#1032]
If has not selected option in select, than select the first option, like prev version by default or one option parameter for this. thx

**Comment by caseyjhol** [comment]
Can you elaborate on your issue? Does your select have a title attribute set?

**Comment by mycroft84** [comment]
I have in select one default option (value -1 and title Please, choose one - must have validation), so if not selected one option, this element will be the default value...so if you send the form the select value will it...

**Comment by mycroft84** [comment]
I rename my data-title attribute and its work fine :)
