### ISSUE TITLE
Issue after enabling, disabled options... v1.7.1

### ISSUE THREAD

**Issue by dvLden** [silviomoreto/bootstrap-select#1039]
**HTML Sample**
```
<select class="selectpicker" id="app-download" data-title="Download Application">
    <option value="android" data-icon="fa-android" data-subtext="<span class='label label-default'>.apk</span>" disabled>Android Application</option>
    <option value="ios" data-icon="fa-apple" data-subtext="<span class='label label-default'>.ipa</span>" disabled>iOS Application</option>
</select>
```

**JS Sample**
```javascript
$('#app-download')
    .children('option')
    .each(function (index, elem) {
        $(elem).prop('disabled', false);
    });

$('.selectpicker').selectpicker('refresh');
```

So this is very base sample out of my project. I am allowing only some countries to interact with `<select />` element and JS will load for those countries as well. 
But for some mischievous reason, selectpicker gets buggy after removing its disabled state.

When I select first option `option[value=android]` it will do required, but once you click that  `<select />` again, it will show that `option[value=ios]` contain `class=selected`. :unamused:
 
Preview of behaviour and short explanation:
1.  `<select />` element clicked - reveals dropdown list. [First Screenshot](http://i.imgur.com/oFljwju.png)
2. Selecting `option[value=android]` - shows that android is selected [Second Screenshot](http://i.imgur.com/6HXmN8K.png)
3.  `<select />` element clicked again - reveals dropdown with `option[value=ios]` as selected. [Third Screenshot](http://i.imgur.com/4EYbCT5.png)

Hopefully I'm clear enough with this issue. Don't know if it's experienced by anyone else as well?
Also, here's a Fiddle...
[JSFiddle Issue Sample](http://jsfiddle.net/dvLden/mrjkge7c/)

**UPDATE (1)**
This issue disappears when I remove selectpicker's title... `data-title="Download Application"`. Interesting. I am unsure how to resolve this, but I'll try. If I come up with something, I'll update this again.

**UPDATE (2)**
Unfortunately it seems like it has something to do with:
```
$('.selectpicker').selectpicker('refresh');
```

I tried removing my script for removing disabled state, leaving only snippet from above. It removed disabled state from first option element and caused this bug to occur. Now it adds `class="selected"` to the disabled element, upon selection of first one. I am out of ideas :neutral_face:

**Comment by caseyjhol** [comment]
Does `$('.selectpicker').selectpicker('render');` work? If you're simply changing the disabled state of an option, use `render()`. Obviously `refresh()` should be working, but that might help narrow down the problem.

**Comment by dvLden** [comment]
`$( '.selectpicker' ).selectpicker( 'render' )` - Does work indeed, thank you!
