### ISSUE TITLE
Make title another color

### ISSUE THREAD

**Issue by yantakus** [silviomoreto/bootstrap-select#1041]
I need to make the title behave as placeholder, so when "Nothing is selected" it is one color and when an option is selected it is another. But I didn't manage to do so, there's no different class added by javascript for these two states.

Any ideas?

**Comment by caseyjhol** [comment]
Hrmm...in the meantime, you could do something like:

````javascript
var setClass = function () {
    if (!$('.selectpicker').val()) { // if nothing is selected
        $('.selectpicker').data('selectpicker').$button.addClass('nothing-selected');
    }
};

setClass();

$('.selectpicker').on('change', function () {
    setClass();
});
````

**Comment by web2style** [comment]
@caseyjhol Thank you, it worked!

**Comment by caseyjhol** [comment]
Even better would be:

````javascript
var setClass = function () {
    $('.selectpicker').data('selectpicker').$button.toggleClass('nothing-selected', !$('.selectpicker').val());
};

setClass();

$('.selectpicker').on('change', function () {
    setClass();
});
````

**Comment by Skaronator** [comment]
Isn't this fixed by https://github.com/silviomoreto/bootstrap-select/commit/7c96845298bc76319960ee1add066d940651be6f? Just wondering when they'll release a new version.

**Comment by dakotahNorth** [comment]
Tried this ... and unfortunately, nothing happened :( 

Is there a more full example of how to set this?

**Comment by caseyjhol** [comment]
You can now use the `bs-placeholder` class.
