### ISSUE TITLE
Change event not triggered when using triggerNative method

### ISSUE THREAD

**Issue by creativecoder** [silviomoreto/bootstrap-select#1043]
Just upgraded from v1.7.1 to v1.7.2 to fix disabled option display issue.

Now change events are not triggered when selecting options, both for multiple and single select fields

**Comment by caseyjhol** [comment]
What's your browser/OS?

**Comment by creativecoder** [comment]
OSX, both current versions of Chrome and Firefox. When I swap out the new calls to `$.triggerNative` with the usual `$.trigger`, all works again.

Nothing apparently wrong with triggerNative, no errors and the dispatchEvent method returns true. But the event handlers I have registered on the change event don't fire :(

I'm delegating the event to document, not sure if that has anything to do with it.
```js
$(document).on('change', '#my_id', function(e){ ...
```

**Comment by caseyjhol** [comment]
Looks like that's the problem. 

```javascript
$('#my_id').on('change', function(e){ ...
```

is working for me, but delegating it to the document isn't working.

I'll check into it. In the meantime, use the v1.7.2 release version (https://github.com/silviomoreto/bootstrap-select/releases/tag/v1.7.2) and it should work for you for now. The development version has triggerNative implemented and isn't yet stable.

**Comment by creativecoder** [comment]
Ah, my bad: I pulled in the development version instead of release version. Thanks!
