### ISSUE TITLE
Dropdown is not clickable when debug set to false

### ISSUE THREAD

**Issue by Hizabr** [silviomoreto/bootstrap-select#1046]
The dropdown can't be opened when debug is set to false.

When the web.config file has the tag:
```
<compilation debug="false" targetFrame...
```

the dropdown menu will not be opened when the user click on it.. however it work fine when the debug tag set to true:
```
<compilation debug="true" targetFrame...
```

Any Idea ?

**Comment by caseyjhol** [comment]
Does this work with a regular Bootstrap dropdown?

**Comment by Hizabr** [comment]
Will it appear i need to call
```javascript
$('.dropdown-toggle').dropdown();
```
in javascript to solve this.
