### ISSUE TITLE
Selectpicker options are offset(hidden) and entire selectpicker is removed on second click in Magento

### ISSUE THREAD

**Issue by brianwalleshauser** [silviomoreto/bootstrap-select#1051]
I have created a gif of the problem here: http://imgur.com/v5hAEtw

I'm really not sure what is happening.  I can provide you with any information you need.

**Comment by caseyjhol** [comment]
Browser/OS? Can you link me to a demo?

**Comment by brianwalleshauser** [comment]
I figured it out.  It was a compatibility issue with prototype.js.  At least the disappearing part was.  The offset options were resolved by removing the 'dropdown-menu' class from the ul.inner.
