### ISSUE TITLE
grunt dist for 1.7.2 breaks requirejs

### ISSUE THREAD

**Issue by giero** [silviomoreto/bootstrap-select#1055]
Hi,

In my project I'm using bootstrap-select with require.js. After the latest update (https://github.com/silviomoreto/bootstrap-select/commit/41de5539e4dc1e28b57eb392226fdc43ddd3e40d) there's a problem with ```init``` function in require.js config:
v1.7.1: http://jsfiddle.net/9xr5af00/
v1.7.2: http://jsfiddle.net/okm9nhe0/
This is the same code - only bootstrap-select version is changed.

As you can see I would like to init bootstrap-select every time when I use bootstrap-select package - after that change it doesn't work anymore.

**Comment by caseyjhol** [comment]
I don't have any experience with RequireJS, but I'm assuming this has to do with #866.
