### ISSUE TITLE
data-mobile="true" works fine on mobile, but the whole dropdown menu doesn't work properly on desktop

### ISSUE THREAD

**Issue by junyawang** [silviomoreto/bootstrap-select#1058]
data-mobile="true" works fine on mobile, but the whole dropdown menu doesn't work properly on desktop.

**Comment by caseyjhol** [comment]
Can you elaborate? What about it doesn't work properly?

**Comment by junyawang** [comment]
data-mobile="true" should work only when browser width is less than 768px (for mobile). Currently if I apply data-mobile="true" and test it, it enables the device's native menu for select menus, which is great.  But when I test it on desktop browser, clicking the dropdown menu won't expand the dropdown list as it does when data-mobile="false". 

Also, I have used "Select All" and "Deselect All" (.bs-actionbox), but when I apply data-mobile="true", it doesn't have these functions available on mobile.

**Comment by caseyjhol** [comment]
`mobile()` simply enables the device's native menu. See http://silviomoreto.github.io/bootstrap-select/#mobile. You have to detect window width/device on your end and call `$('.selectpicker').selectpicker('mobile');` accordingly. If the device's native menu doesn't support additional functionality, there's nothing we can do about that - it's not possible to make alterations to the native menu.

**Comment by junyawang** [comment]
I see. Thanks!

**Comment by tuxormax** [comment]
in version 1.13.14 the select doesn't work fine. in mobiles show the options but its closed inmediatelly and in desktops doesn't show anything
