### ISSUE TITLE
Document data-selected-text-format="static"

### ISSUE THREAD

**Issue by liam-richardson** [silviomoreto/bootstrap-select#1059]
I was looking into modifying the plugin's code to use static title text and I found that it already implemented, and can be used like so:

```html
<select class="selectpicker" data-selected-text-format="static" data-title="Foo">
```

This is **not** mentioned on the [examples page](https://silviomoreto.github.io/bootstrap-select/).

The listed values for `selectedTextFormat` are:
>'values' | 'count' | 'count > #' (where # is an integer)`

Why doesn't this mention "static"? Is this an internal feature which I shouldn't be using? If not, it would be great it if wasn't hidden away in the code &ndash; please mention it on the examples page.

**Comment by caseyjhol** [comment]
The documentation needs to be updated. See #987.
