### ISSUE TITLE
Getting a checkmark in each <option>

### ISSUE THREAD

**Issue by Soraph** [silviomoreto/bootstrap-select#106]
I've recently updated the script with your current release, and after just doing a simple:
      jQuery('.selectpicker').selectpicker();
The markup is very simple:

```
 <select class="selectpicker" id="size" name="size">
   <option value="XS">XS</option>
   <option value="S">S</option>
   <option value="M">M</option>
   <option value="L">L</option>
   <option value="XL">XL</option>
   <option value="XXL">XXL</option>
  </select>
```

I get all the options followed by a checkmark, I'm doing something wrong or there is a bug?

(can't get the snippet working as expected even with the correct gitHub markdown)

![weird_check](https://f.cloud.github.com/assets/1741291/333575/9159c4de-9c5a-11e2-85f7-1fc5afd99fff.png)

**Comment by Ygilany** [comment]
I'm using the updated version of the CSS as well as the scripts, however I'm getting the same error
