### ISSUE TITLE
maxOptions didn't work after init.

### ISSUE THREAD

**Issue by vgross** [silviomoreto/bootstrap-select#1063]
I have a function to disable and enable my select + set maxOptions but unfortunately

$('#select').selectpicker('maxOptions', 2);

doesn't work for me while the disable/enable method works fine. (It seems not to be a selector issue)

here my method:
```javascript
function initChildren(e) {
    var form_child = e.parent().parent().next().find('select[id$="_children_ages"]').first();
    if(e.val() == "0"){
        form_child.prop('disabled', true);
    } else {
        form_child.prop('disabled', false);
        //TODO : Make that works
        form_child.selectpicker('maxOptions', e.val());
    }
    form_child.selectpicker('refresh');
}
```
Even if I replace e.val() by a number directly, it doesn't work, I can select more options that I set with the "maxOptions".

**Comment by caseyjhol** [comment]
maxOptions is an option, not a method. Use `form_child.selectpicker({maxOptions: 4});`
