### ISSUE TITLE
Live Search: Searching for just one char

### ISSUE THREAD

**Issue by dbrammertz** [silviomoreto/bootstrap-select#1065]
When multiple bootstrap-select componentes are used on one page and the keyboard is used to navigate, then sometimes the foucs for the live search box is not set properly. The consequence is that the live search value is not updated and the bootstrap-select just searches for the key passed in the keydown event.

It seems to be an event issue, putting the focus in a deferred function everything works fine.

Proposed patch
```
1165a1166
>                 setTimeout(function () {
1166a1168
>                 }, 10);
1175a1178
> 
```

To see it better within the keydown function:

```
if (!isActive && /([0-9]|[A-z])/.test(String.fromCharCode(e.keyCode))) {
                if (!that.options.container) {
                    that.setSize();
                    that.$menu.parent().addClass('open');
                    isActive = true;
                } else {
                    that.$newElement.trigger('click');
                }
                setTimeout(function () {
                    that.$searchbox.focus();
                }, 10);
            }
```

**Comment by jtfairbank** [comment]
Can you add a jsfddle to demonstrate this issue, and possibly your proposed fix?  Make sure to include instructions like "mash the tab key to mimic rapid keyboard navigation". ;)

**Comment by dbrammertz** [comment]
My work around doesn't work for the new version. So closing the issuse.
