### ISSUE TITLE
optGroupClass being added as undefined

### ISSUE THREAD

**Issue by KrunchMuffin** [silviomoreto/bootstrap-select#1067]
On line 558
https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L558

my option class is called `Available` and have no `optGroupClass`. When the dropdown is displayed, the first option is correct, but subsequent  ones show the class as `Availableundefined`

**Comment by KrunchMuffin** [comment]
I think I see the issue.
`optGroupClass` needs to be defined inside this IF
https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L539
since it is used in there and not the sub IF.

**Comment by KrunchMuffin** [comment]
You fixed that but I think broke another since you removed it from that sub IF statement and it is used in there.
https://github.com/silviomoreto/bootstrap-select/blob/6a0187648002c7b98f8bef23806c1cebef07d1b3/js/bootstrap-select.js#L557

**Comment by caseyjhol** [comment]
Hrmm...it shouldn't be broken. `optGroupClass` is still being set prior to that line.

https://github.com/silviomoreto/bootstrap-select/blob/6a0187648002c7b98f8bef23806c1cebef07d1b3/js/bootstrap-select.js#L539-L560

**Comment by KrunchMuffin** [comment]
Ya, ur right never mind.
