### ISSUE TITLE
Setting size to false brings an error

### ISSUE THREAD

**Issue by MrUpsidown** [silviomoreto/bootstrap-select#1068]
Hello,

When setting `size: false` I get an error:

    Uncaught TypeError: Cannot read property 'liHeight' of undefined

This happens every time the dropdown is opened or closed. It still works fine but I just get this error in the console. Am I doing something wrong?

I am using the latest version.

Another issue: `dropupAuto: true` seems to have no effect. It is always a drop down, even if the select is just a few pixels above the window bottom.

Thanks!

**Comment by caseyjhol** [comment]
`dropupAuto` only works when size is set to `auto` or an integer.

**Comment by vsn4ik** [comment]
Also need fix for: https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L1027.

**Comment by vsn4ik** [comment]
Thanks!

**Comment by MrUpsidown** [comment]
Thanks for the clarification regarding the `dropupAuto` option. I have applied your fix #1068 but still get the same error.

    Uncaught TypeError: Cannot read property 'liHeight' of undefined
        Selectpicker.setSize @ bootstrap-select.js?nq2yw3:765
        (anonymous function) @ bootstrap-select.js?nq2yw3:1007
        x.event.dispatch @ jquery.min.js?v=1.10.2:5
        x.event.add.v.handle @ jquery.min.js?v=1.10.2:5

**Comment by MrUpsidown** [comment]
Thanks!
