### ISSUE TITLE
issue in check all option

### ISSUE THREAD

**Issue by shamseerpari** [silviomoreto/bootstrap-select#1070]
Check all option not working in twitter bootstrap latest version,any one help me to find solution for this,
I think that's due to some class added with check box while loading the page

I am using new twitter boot strap admin template,they are not showing any example for check all option in there example

https://wrapbootstrap.com/themes/admin

**Comment by DrewBe121212** [comment]
Can you please post code in a js fiddle that can replicate the issue? I am running 1.7.2 and have no issues using the select all / select none options, and this includes constantly rebuilding the list of options in a select and calling refresh many times.

**Comment by caseyjhol** [comment]
Assuming this is related to #1077? If so, it's been fixed. Closing this until I get more information.
