### ISSUE TITLE
LiveSearch: Match StartsWith first

### ISSUE THREAD

**Issue by Tsaukpaetra** [silviomoreto/bootstrap-select#1076]
Some users are concerned that the search functionality selects the first found item, instead of the first match that starts with the characters typed (if any).
In other words, if I have a list of:
- Orange
- Apple
- Plum
- Orange
- etc

and I type `Pl`, The search has highlighted Apple, despite Plum being a better first match.

It's not an urgent issue, just something that conflicts with how unmodified dropdowns (at least in IE) would work.

**Comment by caseyjhol** [comment]
You'll want to set `liveSearchStyle` to `'startsWith'` (not yet documented).

**Comment by Tsaukpaetra** [comment]
Well, that does work, though I was envisioning that the search could be "contains", but the selection would move to the StartsWith's first match (if available). Does that make sense?

So, in the example I provided, Apple and Plum would be filtered in, but Plum would be selected.
