### ISSUE TITLE
Design issues in Bootstrap version 3.3.5

### ISSUE THREAD

**Issue by kvigsbo** [silviomoreto/bootstrap-select#1082]
Design broken in Bootstrap 3.3.5, such as wider dropbox and icon located outside selector box. Design not breaking when dropbox is located such as it opens up. Works perfect in Bootstrap version 3.3.4
![bootstrap-335-issue](https://cloud.githubusercontent.com/assets/11400136/8466906/b08c082a-2025-11e5-8aa0-3c10496e0984.png)

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case?

**Comment by kvigsbo** [comment]
No, sorry, when isolated using your test.html file, I find no errors.

I tested with Bootstrap 3.3.4 and 3.3.5 using both jquery 1.9.0, 1.1.0 and
1.11.2

Not sure what goes on, it happens on a couple of my projects in a CMS
setting. I'll keep digging.

Thanks.

- Kim
