### ISSUE TITLE
bug: hideDisabled + multiple

### ISSUE THREAD

**Issue by giero** [silviomoreto/bootstrap-select#1084]
Hi,

http://jsfiddle.net/exen4sv3/

1) set ```hideDisabled``` and ```multiple``` for single select
2) select some options
3) set ```'disabled'``` attribute for those selected and refresh selectpicker

Disabled options disappeared from select (which is 100% ok) but selectpicker's label behave wrong.

Hidden options are now shown as ```'false'``` (should not be listed at all) and when you set ```data-selected-text-format="count"``` they are still counted .. but they shouldn't.

The same behavior occurs during initialization: http://jsfiddle.net/309u0bnn/

Hidden options should always be treated as non-existent.

**Comment by nithish-thomas** [comment]
line 608 seems to be the cause for false coming up in the dropdown body

if (that.options.hideDisabled && (this.disabled || this.parentElement.tagName === 'OPTGROUP' && this.parentElement.disabled)) return false;

**Comment by giero** [comment]
@nithish-thomas That's it! :+1:
