### ISSUE TITLE
Display value not updating when choosing a new option

### ISSUE THREAD

**Issue by yoxalld** [silviomoreto/bootstrap-select#1089]
I am having an issue where the displayed value does not update when you choose a new option with the dropdown.

You can see an example of it at http://pdh.cakeandeatitdesigns.com/product/activated-charcoal/

You can see that the value it changing programmatically because the price updates as if you had chosen a different option. But the displayed value doesn't change.

I am using bootstrap version 3.3.2 and bootstrap select version 1.6.4

Thanks!

**Comment by caseyjhol** [comment]
I recommend trying v1.7.3.

**Comment by yoxalld** [comment]
I updated but that didn't fix the issue. I have had to just remove the styled dropdowns for the time being. Thanks for the help though!

**Comment by caseyjhol** [comment]
Any chance you have any conflicting javascript?
