### ISSUE TITLE
Error prototype.js on Magento

### ISSUE THREAD

**Issue by minhluan259** [silviomoreto/bootstrap-select#1090]
bootstrap-select is working. But after click, error messages appear
![capture](https://cloud.githubusercontent.com/assets/7834473/8575680/87332a74-25c7-11e5-90d6-3f7653643172.PNG)

> prototype.js
> https://github.com/engineyard/magento-ce-1.9/blob/master/js/prototype/prototype.js

**Comment by caseyjhol** [comment]
What version of bootstrap-select are you using?

**Comment by minhluan259** [comment]
I using bootstrap-select version 1.7.3

**Comment by minhluan259** [comment]
I found in the code 
for (var i in options) 
and
for (k in o)
is very bad
http://stackoverflow.com/questions/2265167/why-is-forvar-item-in-list-with-arrays-considered-bad-practice-in-javascript
Please update your code, it will be fix this issue

**Comment by caseyjhol** [comment]
That's only relevant when iterating over an array. In both cases, we're iterating over an object and need access to the key.

**Comment by Martijnvanhoof89** [comment]
I was wondering if there is a workaround. As posted by minhluan259 there is an issue with the prototype.js library. It triggers prototype when opening the dropdown.

prototype.js:883 Uncaught TypeError: this.each is not a functionfindAll @ prototype.js:883y @ bootstrap-select.js:847setSize @ bootstrap-select.js:884(anonymous function) @ bootstrap-select.js:1066dispatch @ jquery.js:4737v.handle @ jquery.js:4549
prototype.js:1937 Uncaught TypeError: Cannot set property 'display' of undefined

Thanks in advance,
Martijn

**Comment by nelero** [comment]
Same bug here
a fix would be helpful

**Comment by Tomasz-Silpion** [comment]
Update prototype to 1.7.3 version and it's gone

**Comment by duepi** [comment]
Update prototype to 1.7.3 version and it's gone

**Comment by caseyjhol** [comment]
Looks like this is fixed in Prototype v1.7.3.
