### ISSUE TITLE
Stop selecting text on the menu

### ISSUE THREAD

**Issue by Tomas-M** [silviomoreto/bootstrap-select#1092]
Bootstrap does not by default care about selected text on dropdown menu, because clicking the dropdown menu usually hides it. However, bootstrap-selects with multiple selection keep the menu open for the entire time, and sometimes if I click very fast, I get text selected, like on this image
![sample](https://cloud.githubusercontent.com/assets/2259370/8594625/e12e54e2-2642-11e5-9992-feeb3653a3f7.png)
:
This is annoying. To disable the text selection, it is possible to add this style:

.dropdown-menu {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    outline: none;
}

I'm unsure if this should be rather submitted to twitter-bootstrap developers, but I think they won't care. You should :)

**Comment by avindra** [comment]
You boys should be using autoprefixer for those vendor prefixes.
