### ISSUE TITLE
Release 1.7.3 Nuget package

### ISSUE THREAD

**Issue by pseabury** [silviomoreto/bootstrap-select#1096]
1.7.3 has not yet been pushed to Nuget.

https://www.nuget.org/packages/bootstrap-select/

**Comment by taspeotis** [comment]
I too would like the new version on NuGet, please

**Comment by taspeotis** [comment]
Can we get 1.7.3 and 1.7.4 updated on NuGet, please

**Comment by caseyjhol** [comment]
v1.7.5 nuget package released.

**Comment by taspeotis** [comment]
Thank you @caseyjhol
