### ISSUE TITLE
Windows 8 - Chrome, dropdown will not close

### ISSUE THREAD

**Issue by ProxyTech** [silviomoreto/bootstrap-select#1099]
I'm experiencing some very strange behaviour, but only on Chrome and ONLY on windows 8! It's Version 45 of Chrome on win8 (desktop mode). The dropdown refuses to close when clicking outside of the dropdown, and performs a bit strangely when attempting to close via the "cross".... entire drop-down menu will shift a few pixels to the right.

Is anyone else able to reproduce this behaviour?

My dropdown settings below:

autocomplete="off"
multiple
data-selected-text-format="count>3"
data-container="body"
data-header="Select Items"
data-width="100%"
data-action="/Report/Action"

**Comment by sandeep1456** [comment]
I'm also facing this issue for multi-select mode on chrome 46.0.2490.86 and windows 8

**Comment by throrin19** [comment]
I have this issue on IOS 8

**Comment by caseyjhol** [comment]
What version of bootstrap-select are you using?

**Comment by quasipickle** [comment]
I don't mean to necro-post, but this is happening for me too.  I'm using v 1.10.  I'm using bootstrap-select in multiple spots though, and it's only happening on one of them, so it might be a configuration issue on my end.

**Comment by throrin19** [comment]
1.7.3

**Comment by quasipickle** [comment]
I was having this problem too - upgrading to the latest version fixed it.

**Comment by caseyjhol** [comment]
Closing this unless others can confirm that this issue is still ongoing in the latest version of bootstrap-select.
