### ISSUE TITLE
How to remove caret class ?

### ISSUE THREAD

**Issue by gablu** [silviomoreto/bootstrap-select#1100]
after applying class="selectpicker" in my select list it working fine , I just want to remove the  'caret class'  can some one help me to do that 
![se](https://cloud.githubusercontent.com/assets/11157455/8716217/e2b80f9c-2bab-11e5-98ca-b3f8f699d5e6.GIF)

**Comment by caseyjhol** [comment]
This is a new feature, and is not yet in an official release, but in the options, you set:

```js
$.fn.selectpicker.defaults = {
    template: {
        caret: ''
    }
}
```

or, in your CSS you can do

```css
.bootstrap-select .bs-caret {
    display: none;
}
```

**Comment by pasevin** [comment]
good one, thanks! i think should be closed now :]

**Comment by jaychacko** [comment]
@caseyjhol Thats not working for me. I have done this and made the icon i want showed up but cant remove the default carret 
`.dropdown-toggle::after {
  font-family: "Ionicons";
  display: inline-block;
  content:'\f123';
  width: 0;
  height: 0;
  margin-left: .255em;
  vertical-align: .255em;
  border-top: .3em solid;
  border-right: .3em solid transparent;
  border-bottom: 0;
  border-left: .3em solid transparent;
}`
![image](https://user-images.githubusercontent.com/25227854/51130851-a852c800-17f3-11e9-8b1f-1c40345fc03f.png)

`.bootstrap-select .bs-caret {
    display: none;
}` not working for me either

**Comment by caseyjhol** [comment]
@jaychacko What version of Bootstrap are you using?

**Comment by jaychacko** [comment]
> @caseyjhol  What version of Bootstrap are you using?

using bootstrap 4.0.0
Check out my full code attempt
https://github.com/jaychacko/bootstrap-select

**Comment by caseyjhol** [comment]
@jaychacko Bootstrap 4 adds a caret automatically via CSS (`.dropdown-toggle::after`) using the border trick, you'll need to disable it that way. Remove all references to borders in that CSS rule and it should fix it.

**Comment by jaychacko** [comment]
@caseyjhol wow that worked, thanks
