### ISSUE TITLE
data-hidden and form submit

### ISSUE THREAD

**Issue by ChristianGiupponi** [silviomoreto/bootstrap-select#1104]
Hi,
I have a form that use this plugin and I have set the first element with the data-hidden attribute:

    <select class="selectpicker" name="sesso">
                <option data-hidden="true">Sesso</option>
                <option value="m">Maschio</option>
                <option value="f">Femmina</option>
            </select>

The problem is that when I submit the form if the select is set to the first element, the form will process that element.

In my example I will get `sesso=Sesso`but my goal is do not have any in my php script if no option is select.

How can I do that?

**Comment by bojcheski** [comment]
why not processing that on php end... like 
if (in_array($_POST['sesso'], array('m', 'f')) {
     //process it
}

**Comment by ChristianGiupponi** [comment]
Yeah but when I submit the get parameter will create a url for a search and I do not want to put in the url data that are not useful for the search.

Any other solution? Otherwise if this is the only option I will do that and then I will recreate a redirect

**Comment by caseyjhol** [comment]
```html
<select class="selectpicker" name="sesso">
    <option data-hidden="true" value="">Sesso</option>
    <option value="m">Maschio</option>
    <option value="f">Femmina</option>
</select>
```
or
```html
<select class="selectpicker" name="sesso" title="Sesso">
    <option value="m">Maschio</option>
    <option value="f">Femmina</option>
</select>
```
