### ISSUE TITLE
The problem with the width in IE8

### ISSUE THREAD

**Issue by Psihobolt** [silviomoreto/bootstrap-select#1107]
![img2](https://cloud.githubusercontent.com/assets/13366217/8848875/c36d3408-3143-11e5-960a-dacaba7eaf0a.jpg)
How fix it? Help me please

**Comment by Psihobolt** [comment]
@caseyjhol @silviomoreto help me please!

**Comment by silviomoreto** [comment]
Please read the guidelines to open issues: https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md#bug-reports
Provide at least a live example to understand the problem and add more information. 

Although, this seems to not be an issue of bootstrap, so I suggest to ask a question on stackoverflow.

**Comment by Psihobolt** [comment]
@silviomoreto Sorry for the incomplete information!
I have IE8, and my code
```
<div class="container">
  <div class="row">
    <div class="col-md-6">
       ...
    </div>
   
    <div class="col-md-6">
       <select class="selectpicker form-control" multiple>
          <option>The very very very very long text 1</option>
          <option>The very very very very long text 2</option>
          ...
          <option>The very very very very long text 10</option>
       </select>
    </div>
  </div>
</div>
```

In Firefox and Chrome select properly displayed, and the width is 100%. But in IE it is not displayed correctly. As shown above in the picture. A similar problem is described in the issue #285 .
Therefore, I would like to know whether there was any problem is the solution? Either I got the idea to use the property "data-selected-text-format=count>2" and for select to hang and display a tooltip selected elements in it. This will solve the problem with the width in IE. But, I can not initialise the tooltip, as shown in the issue #938 . Please help me at least. council.

**Comment by Psihobolt** [comment]
@caseyjhol @silviomoreto You will not help me advice?

**Comment by silviomoreto** [comment]
@Psihobolt , right now, there are 107 open issues. It is humanly impossible to help all the users. When I have some free time I can see your point, but I do not know when this will be. Sorry about that.

If you have to hurry, I suggest to find another ways:
- Make a question on stackoverflow about that
- Try to solve that, fix the bootstrap-select code, and make a pull-request

**Comment by Psihobolt** [comment]
@silviomoreto I beg your pardon. I understood you. I will try to find a solution

**Comment by silviomoreto** [comment]
Don't mind @Psihobolt =) 
If you found the solution before us, please post it here or create a pull request!
