### ISSUE TITLE
Handlebar and Boostrap-Select

### ISSUE THREAD

**Issue by PrinceShanky** [silviomoreto/bootstrap-select#1109]
When I use handlebar engine to render the <option></option> part from a SQL database table, it looks the HTML gets properly rendered. I have verified it by looking into the developer tools. But the multi-select does not show when I the option drop-down opens. 

It looks like there is another class named "dropdown-menu open" that contains the search elements. 

My question is - while using Handlebar I am unable to view the drop-down containing the search elements but when i directly hard-code the value inside the <select></select> tag it works fine. 

It would be great if you can let me know a solution for this.

**Comment by PrinceShanky** [comment]
![silivo-aspx-withhandlebars](https://cloud.githubusercontent.com/assets/13508322/8894320/5f5fca14-33cf-11e5-9470-847439b6882d.png)
![silivo-aspx-withouthandlebars](https://cloud.githubusercontent.com/assets/13508322/8894321/61162aba-33cf-11e5-9b34-4ec656d44c29.png)

**Comment by caseyjhol** [comment]
I don't use handlebar. Any chance you can link me to a JSfiddle/plunker example so I can play around with it? Are you using `selectpicker('refresh')` at any point? Using AngularJS, you have to listen for any changes made to the select and then call `selectpicker('refresh')` accordingly.

**Comment by PrinceShanky** [comment]
Is it okay if I can attach the project file ? That will give a better view of what I am talking about ?

**Comment by jtfairbank** [comment]
I'm using handlebars right now and everything works fine.  I'd be happy to look into this one if you can provide a JSfiddle example, or share your handlebars code / rendered html in the thread.

Is this something that happens when the page is loaded? Or are you dynamically changing the options based on user interaction or the results of an ajax call?

**Comment by caseyjhol** [comment]
Closing until more info can be provided.
