### ISSUE TITLE
OptGroup : Quickselect Not Functioning Correctly

### ISSUE THREAD

**Issue by itvweb02** [silviomoreto/bootstrap-select#1111]
Hopefully I am using the correct terminology here when I say "Quickselect". For clarification, here is an example: 

Imagine a select field that has all US states as options.
If a user hits the "C" key when focused on that select field,  "California" should be the first option that is selected. If the user hits the "C" key again, then "Colorado" should be selected. And so on.
This functionality works inherently on any normal HTML select field.

However, if you use an option group with the bootstrap-select plugin, the Quickselect functionality breaks completely. It does not select the correct option based on alphabetical order. It seems to arbitrarily focus on random options. This is definitely a usability and accessibility issue.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case?

**Comment by itvweb02** [comment]
Here is a jsFiddle : https://jsfiddle.net/sk3d365v/3/
