### ISSUE TITLE
Single selection skips options when using keyboard navigation.

### ISSUE THREAD

**Issue by serpi90** [silviomoreto/bootstrap-select#1117]
Single selection skips options when using keyboard navigation.

https://jsbin.com/tiqimeweqo/1/edit?html,output

If you use key down, it jumps from 2nd to 5th to 8th option.
If you use key up, it alternates between 1st and 2nd options.

**Comment by caseyjhol** [comment]
this was fixed in commit 6f9f93bfd934a35d8618040f85642be16c712247
