### ISSUE TITLE
Min-height issue

### ISSUE THREAD

**Issue by frlinw** [silviomoreto/bootstrap-select#1119]
Hi,

linked to https://github.com/silviomoreto/bootstrap-select/issues/615 and https://github.com/silviomoreto/bootstrap-select/issues/65

There is an issue with min-height when the "blank" option is hidden (display:none or bootstrap "hidden" class)
The height is greater than the content because the height of the hidden option is added to minHeight 

```
<select selectpicker data-width="100%" data-none-selected-text="">
     <option class="hidden"></option>
     <option>Option 1</option>
     <option>Option 2</option>
</select>
```

![image](https://cloud.githubusercontent.com/assets/11896237/9100774/df657ff8-3bde-11e5-959e-dc9c0551158f.png)

can you do something for this ?

Thanks a lot

**Comment by frlinw** [comment]
Problem is solved when you use the data-size attribute... magic

**Comment by caseyjhol** [comment]
This is also fixed in newer versions of bootstrap-select (I'm not sure what version you're using).
