### ISSUE TITLE
Select options in order.

### ISSUE THREAD

**Issue by jaycruz17** [silviomoreto/bootstrap-select#1123]
How can I view the values of the selected options in order properly?
I used the the changed.bs.select function to do this. Please help me.
For example: 
```
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
```
My selection sequence is `2, 3, 1`.
I want to get the val() of `["2", "3", "1"]` but it gives me `["1", "2", "3"]`.

```
$('#myselect').on('changed.bs.select', function () {  
    alert($(this).val());
});
```
I saw in this [link] (https://github.com/silviomoreto/bootstrap-select/issues/603) that this is possible.
This issue was archived but I don't know how to do it. Thank you in advance.

**Comment by caseyjhol** [comment]
changed.bs.select passes through event, clickedIndex, newValue, oldValue. true if selected and false if not selected

```js
$('#myselect').on('changed.bs.select', function (event, clickedIndex) {  
    alert(clickedIndex);
});
```

You can use that to determine the order of selected options. `val()` is a jQuery function and is not affected by bootstrap-select.
