### ISSUE TITLE
Don't always align to left:0

### ISSUE THREAD

**Issue by CCInc** [silviomoreto/bootstrap-select#1127]
I'm not very sure how to word this, but if you'll look at [this](http://jsfiddle.net/30jLske3/) you can see that the long options cause a horizontal overflow due to the css value left:0 always active. 

![Image of bootstrap-select behavior](http://i.snag.gy/g3Ie8.jpg)

This is in contrast to the [native select behavior](http://jsfiddle.net/cp11p462/) where the dropdown simply aligns to the right.

![Image of native behavior](http://i.snag.gy/wVOh7.jpg)

I feel it would be better to implement this behavior, or at least give the user a choice. It would be a very simple fix.

Thanks!

**Comment by caseyjhol** [comment]
You can set `dropdownAlignRight` or `data-dropdown-align-right` to `true` to manually align the menu. However, I would like to implement a method to do it automatically (similar to dropupAuto).

**Comment by CCInc** [comment]
I just saw [this](https://github.com/silviomoreto/bootstrap-select/pull/1016) pull request, I'm guessing that is similar to the code needed for this issue?
