### ISSUE TITLE
Is Documentation Updated?

### ISSUE THREAD

**Issue by jnfsmile** [silviomoreto/bootstrap-select#1128]
At http://silviomoreto.github.io/bootstrap-select/

noneSelectedText, for example, is not mentioned there

**Comment by caseyjhol** [comment]
The documentation is very outdated. It needs a complete overhaul, but we haven't had the time to update it yet.

**Comment by jnfsmile** [comment]
We'll leave it as an open issue?

**Comment by jtfairbank** [comment]
+1 Could you add the documentation as a github project?  I find I often don't have time to add to code (need to think of many tests, just want to get the issue filed and get back to work).  But adding to documentation is quite easy and very fulfilling.
