### ISSUE TITLE
Multi render

### ISSUE THREAD

**Issue by frlinw** [silviomoreto/bootstrap-select#1133]
Hi,

I'm using bootstrap-select with angular and it works perfectly exept in one case.
When I load a template into a modal, the select is rendered twice, the first is the right select and the second is empty

![image](https://cloud.githubusercontent.com/assets/11896237/9447605/95d87304-4a98-11e5-8838-6b1b1ae5d3c1.png)

Any idea ?

**Comment by moneytree-doug** [comment]
It would help to have a plnkr

**Comment by frlinw** [comment]
I developed my own bootstrap select in angular way.
I close the issue
