### ISSUE TITLE
Change options after initialization

### ISSUE THREAD

**Issue by lowerends** [silviomoreto/bootstrap-select#1134]
Is there a way to change the options after initialization? With "change" I mean adding and deleting options as well as replacing all the options by new options.

**Comment by caseyjhol** [comment]
http://silviomoreto.github.io/bootstrap-select/#refresh

**Comment by lowerends** [comment]
I know about the `refresh` method, but does it mean that new options should be added to the DOM directly and then call the `refresh` method on the selectpicker?

**Comment by caseyjhol** [comment]
Yes - add to DOM using normal jQuery methods, and then call `refresh`.

**Comment by lowerends** [comment]
Ok, thanks for confirming.
