### ISSUE TITLE
CSS does not apply

### ISSUE THREAD

**Issue by muratbastas** [silviomoreto/bootstrap-select#1136]
Hello! I included bootstrap.css and bootstrap-select.css latest version.
```html
<!-- this is head -->
<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/js/plugins/bootstrap-select/css/bootstrap-select.css">
<!-- this is body -->
<select name="kategori" class="selectpicker" title="Seçiniz">
    <option value="1">Defter</option>
    <option value="2">Kitap</option>
    <option value="3">Ajanda</option>
    <option value="4">Davetiye</option>
    <option value="5">Kartvizit</option>
    <option value="6">Broşür</option>
</select>
<!-- this is footer -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/js/plugins/bootstrap-select/js/bootstrap-select.js"></script>
<script src="text/javascript">
$(function() {
    'use strict';
    $('.selectpicker').selectpicker();
});
</script>
```
I added `!important` word to all properties in bootstrap-select.css but looks like at following.

<img width="341" alt="ekran resmi 2015-08-27 17 48 58" src="https://cloud.githubusercontent.com/assets/1137480/9523753/1c85dd86-4ce4-11e5-8dae-8e35c2fd3230.png">

How can i fix it?

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case?

**Comment by muratbastas** [comment]
Hi @caseyjhol demo link is here. http://murat.omgmedya.com/index/test

**Comment by caseyjhol** [comment]
You need to add `rel="stylesheet"` to your link tag:

```html
<link rel="stylesheet" href="/modules/js/plugins/bootstrap-select/css/bootstrap-select.css">

**Comment by muratbastas** [comment]
Ty very much. :+1:
