### ISSUE TITLE
OptGroup : Up & Down Navigation Not Functioning Correctly

### ISSUE THREAD

**Issue by Rumeth** [silviomoreto/bootstrap-select#1137]
This is almost similar to Issue #1111. The only difference that I can see i that bootstrap-select.js is loaded after bootstrap.js. Because of the load order, the up/down navigation goes haywire.

Also, the navigation is looped for normal selection but not for option groups. Shouldn't it be consistent?

I have attached the jsFiddle from Issue #1111 & for my scenario.
Issue #1111 : https://jsfiddle.net/sk3d365v/3/
New : https://jsfiddle.net/dLamvx1j/3/

**Comment by caseyjhol** [comment]
Please use the newest version of bootstrap-select.
