### ISSUE TITLE
Not working well on mobile-device / Android

### ISSUE THREAD

**Issue by typoworx-de** [silviomoreto/bootstrap-select#1148]
On mobile devices I would expect, that the 'mobile' option will trigger the native select-feature (as also done by usual HTML-Select).

This does not work!

The rendered Bootstrap-Select looks fine at first, but I was unable to select any value from drop-down. The value is not shown/saved properly.

Tested on Android 4, Chrome Engine.

Can anyone confirm this?

I would prever to handle triggering of Bootstrap-Select by myself - and not by the bootstrap-select plugin while loading. This way one could decide for mobile-devices to use other alternatives or let the native select stand as it is.

**Comment by caseyjhol** [comment]
In the future, please search the issues before creating a new one. http://silviomoreto.github.io/bootstrap-select/#mobile
