### ISSUE TITLE
I Want Live search on my old selectpicker

### ISSUE THREAD

**Issue by VenubabuSunkara** [silviomoreto/bootstrap-select#1155]
Hi team.We re developed one application i used old select-picker now live search functionality implemented i want to add that functionality  can you please verity my JS and please send me latest js with supporting my application

my website :https://www.travelauto.com/car-plus-driver-limo.html      
first citys dropdown i want live search.please send me reply

**Comment by caseyjhol** [comment]
Use the data-live-search="true" attribute.

**Comment by VenubabuSunkara** [comment]
that tag not supported i already used

and also i changed some code on latest js
i already send those changes

**Comment by caseyjhol** [comment]
Then you need to upgrade to a newer version of bootstrap-select. I can't insert new functionality into an old version of the plugin.
