### ISSUE TITLE
Why there is duplicate of dropdown that hides with .bs-select-hidden appeared in 1.7.* ?

### ISSUE THREAD

**Issue by craft37** [silviomoreto/bootstrap-select#1157]
For what reason architecturally?
Silvio, please describe if it's not problem.
Thanks.

**Comment by dargue3** [comment]
just had this problem, make sure to add rel="stylesheet" to wherever you pull in the bootstrap-select.css file.

**Comment by caseyjhol** [comment]
Previously, the select was hidden using jQuery `.hide()`. Adding a class is faster, so the bs-select-hidden class is now being used instead.
