### ISSUE TITLE
Add option to display optgroup caption for selected item

### ISSUE THREAD

**Issue by klewin** [silviomoreto/bootstrap-select#1158]
Rather than use the `showSubtext` option, add a new option `showOptgroupCaption` that will include the caption with the selected option.

This simplifies and adds clarity when an option is included in multiple groups.

For example:

Category 1
    - Item 1
    - Item 2
    - Other

Category 2
    - Item 3
    - Item 4
    - Other

Displaying `other` as the selected text is ambiguous.

Possible solution is to use the same sub text display to show the optgroup caption:

`*Other* Category 2 `

**Comment by acshef** [comment]
For a workaround, see http://silviomoreto.github.io/bootstrap-select/#title
> You can also use the `title` attribute as an alternative to display when the option is selected

So for Item 1, Category 1, you could add `title="Item 1 (Category 1)"`

**Comment by klewin** [comment]
Thanks.  I was able to get this working.

`selectedTextFormat` must be set to **'static'**

Then setting the title and rendering worked properly:

```
$('.selectpicker')
   .selectpicker({ title: 'new title' })
   .selectpicker('render');
```
