### ISSUE TITLE
[enhancement] Filter, check, and uncheck all option

### ISSUE THREAD

**Issue by amitava82** [silviomoreto/bootstrap-select#116]
Thanks for the plugin, it is really amazing! Is it possible to have option like this:

![image](https://f.cloud.github.com/assets/1279530/390357/9f8a3d52-a73d-11e2-84fe-1ca669f6d039.png)

For a long list of select options it is really helpful for the user.

**Comment by gideonapollob** [comment]
###### Environment
* Windows 7
* jQuery 1.12.4
* Bootstrap 3.3.7

###### Detail:
When [Select/deselect all options](http://silviomoreto.github.io/bootstrap-select/examples/#selectdeselect-all-options) customize menu is enabled, and you press the <kbd>Select All</kbd> button, will select all option without considering `data-max-options` property of the `<optgroup>` as shown in [this jfiddle](https://jsfiddle.net/gabardelas/aq9Laaew/108864/). When the <kbd>Select All</kbd> button is pressed, is should only select one (preferrably the first `<option>` of that `<optgroup>`), as inicated by `data-max-options` property.
