### ISSUE TITLE
Dropup: leave searchbox in place of original field

### ISSUE THREAD

**Issue by lowerends** [silviomoreto/bootstrap-select#1163]
Is there a way to leave the searchbox in the position of the original field when the `dropup` class is applied to the selectpicker? Is this possible via CSS? Any clues are welcome!

Thanks

**Comment by jaridmargolin** [comment]
Please note that I do not feel good about this code.... however it works for my current use case.

In short, I move the search component outside of the menu container. I then toggle between displaying the search component and the button by plugging into the event system. There is some extra cruft to display the caret in the input view.

I'm still trying to determine if bootstrap-select is the right solution for my needs. If I decide to move forward with tis plugin I will most likely address this problem with a proper PR (no promises).

```
$('.selectpicker').selectpicker({
      'liveSearch': true,
      'liveSearchStyle': 'startsWith',
      'styleBase': 'form-control',
      'style': 'input-md'
    });

    var searchbox = $('.bs-searchbox').each(function (key, el) {
      var $el = $(el);
      var $root = $el.closest('.bootstrap-select');
      var $input = $el.find('input');
      var $btn = $root.find('button');
      var $text = $btn.find('.filter-option');
      var $caret = $root.find('.bs-caret').clone();

      $root.prepend($el);
      $el.css({
        'padding': '0px'
      });
      $el.hide();

      $el.append($caret);
      $caret.css({
        'position': 'absolute',
        'top': '50%',
        'right': '12px',
        'margin-top': '-11px',
        'cursor': 'pointer'
      });
      $caret.on('click', function () {
        $root.trigger('show.bs.dropdown');
      });


      $root.on({
        'hide.bs.dropdown': function (e) {
          $btn.show();
          $el.hide();
        },
        'show.bs.dropdown': function (e) {
          $btn.hide();
          $el.show();
          $input.attr('placeholder', $text.text());
        }
      });
    });
```

**Comment by lowerends** [comment]
I only now found the time to try your solution, and it works perfectly. Thanks!
