### ISSUE TITLE
slow page loading

### ISSUE THREAD

**Issue by phoenix298** [silviomoreto/bootstrap-select#1164]
I add from 1 to 1000 from a continuous loop. This page loading slowly

<select id="speed" name="speed" data-width="auto" class="form-control selectpicker">
<script type="text/javascript" language="javascript">
        for (var i = 1; i <= 1000; i++) {
             document.write('<option value="' + i ' + '">' + i + '</option>');
         }
</script>
</select>

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by caseyjhol** [comment]
Without seeing your code, I'm going to assume you're calling `refresh()` for every loop. Add all of the options in the loop, and then call `refresh()` once at the end. Closing this until you can provide more info.
