### ISSUE TITLE
require doesn't work properly with v1.7.4

### ISSUE THREAD

**Issue by arthur-feral** [silviomoreto/bootstrap-select#1165]
Hi,
I'm using your plugin v1.7.3, and everything works fine. I'm using require to import your lib in a js module, and then [browserify](https://www.npmjs.com/package/browserify) to compile the main javascript file.
Passing to v1.7.4, it seems that bootstrap-select isn't exported correctly, and then not available to use as jQuery plugin.
I'm suspecting [this commit](https://github.com/silviomoreto/bootstrap-select/commit/964a458f969c2de760c225a63b2f9bf2b9c905d3) ...

**Comment by thisispaul** [comment]
+1 same problem here

**Comment by caseyjhol** [comment]
RequireJS is working for me in the latest version.
