### ISSUE TITLE
Optgroups select deselect childrens 

### ISSUE THREAD

**Issue by samphp90** [silviomoreto/bootstrap-select#1170]
Hi i want option to select all children under the optgroup options. I have did some custom code for it but it's not working properly it's not giving me the selected values.
![2015-10-06 15-16-12](https://cloud.githubusercontent.com/assets/6873770/10305331/4237af96-6c3d-11e5-815f-9bf815734777.png)

Do you have any solution for this.

**Comment by caseyjhol** [comment]
See #737.

**Comment by samphp90** [comment]
Hi @caseyjhol,
Thanks for helping me out. It's working perfectly. :dancers:
