### ISSUE TITLE
Customizing the text when multiple options are selected [implement doesn't works]

### ISSUE THREAD

**Issue by C0ZEN** [silviomoreto/bootstrap-select#1179]
I've found this question : #797 which is now close.
I've got a similar question/request.
I tried to change the text display by creating some new option like that : 

    itemsSelected: null,
    countSelectedText: function (numSelected, numTotal) {
                return (numSelected == 1) ? '{0} item selected' : '' + itemsSelected + '';
    },
And of course call and implement it from js script like that : 

    $('.selectpicker').selectpicker({
        itemsSelected: '<?php echo ITEMS_SELECTED; ?>' // value change with language
    });
But it doesn't work. The value don't change. As far as I know the only way which is working is the official one : a simple string.

    // All KO
    return (numSelected == 1) ? '{0} item selected' : '' + itemsSelected + '';
    return (numSelected == 1) ? '{0} item selected' : itemsSelected;
So if someone can tell me how can I handle that and maybe add this option officially for countSelectText and maxOptionsText it will be wonderful.
Thanks.

**Comment by caseyjhol** [comment]
What are you trying to do?

**Comment by C0ZEN** [comment]
I just need to change the text if the language change (like you see from php constants). So I use selectpicker's options do to that but it seems that the return statement doesn't works in the list of options if I put an other type of value than a simple string... In other part of the .js function, we use a simple 'this.options.var' to display them but it is not working in countSelectedText because it's in the options part.  
So I just want to know if there is an other solution to do it directly from the options declaration of if I need to do it later in the code - and if it's later in the code, where ?!,- .

**Comment by C0ZEN** [comment]
Ok I found the solution.

**Comment by caseyjhol** [comment]
You need to also set `selectedTextFormat` to `'count'` or `'count > x'` to use countSelectedText.
