### ISSUE TITLE
Set value returned via JSON

### ISSUE THREAD

**Issue by brunogemelli** [silviomoreto/bootstrap-select#1180]
Hi, I'm trying to set a value to selectpicker, without success.

if I set this manually, it works:
ex:
      $('.selectpicker').selectpicker('val', ['181', '45'] );
      $('#formulario #idspessoacontato').selectpicker('render');

but when trying to set with dynamic value (in string), it didn't work:
ex: 
     var stringWithValue = "['181', '45']";
      $('.selectpicker').selectpicker('val', stringWithValue );
      $('#formulario #idspessoacontato').selectpicker('render');

What am I doing wrong??

Thanks.

**Comment by DarkMerge** [comment]
in first code u gave an array, in second - string. Maybe problem with this types?

**Comment by brunogemelli** [comment]
Sure. Great!

Thanks @DarkMerge !
