### ISSUE TITLE
Live Search Select All select All instead of Filtered component. 

### ISSUE THREAD

**Issue by goyatparmod** [silviomoreto/bootstrap-select#1185]
Hi i am using bootstrap select with following configuration.

<select id="formula-search" title="Prompt,Formula,Fields"
                        class="show-tick  selectpicker"
                        data-size="auto" data-live-search="true"
                        data-live-search-placeholder="Search"
                        data-actions-box="true"
                        multiple ng-multiple="true"
                        ng-model="selectedBindings"
                        ng-options="global.Field  group by global.Field_type
                                    for global in globalFieldNames | filter:searchText">
                    <option id="selected_field"></option>
</select>

Problem i found when we search and then press select All it does not only selected filtered item it select all item in list.Below screen shot i am just selecting 3 item.

￼
![screenshot](https://cloud.githubusercontent.com/assets/13874876/10699430/fae629f8-7973-11e5-9e95-efa2aa3f95d3.png)

But in this screen show it shows it select all item in list. 

https://www.dropbox.com/s/lendw5msivl9jrc/Screenshot%202015-10-23%2010.54.28.png?dl=0

I did a work around in bootstrap-select.js selectAll function But i am new to javascript and was not confident about my fix.
Here 

    selectAll: function () {
      this.findLis();
      this.$element.find('option:enabled').not('[data-divider], [data-hidden]').prop('selected', true);
      this.$lis.not('.divider, .dropdown-header, .disabled, .hidden').addClass('selected');

      var $list = this.$lis;
      this.$element.find('option').each(function (index, value) {
        value.selected = false;
        if (index > 0 && value.textContent != ' ') {
          var $list_element = $.grep($list,function(e){
            return e.textContent ==value.textContent;
          });
          try {
            value.selected = !($list_element[0].classList.contains('hidden'));
          }
          catch (e) {
            alert('An error has occurred: ' + e.message + index);
          };
        };
      });

      this.render(false);
    },

Appreciate any help to fix it.

**Comment by caseyjhol** [comment]
This was fixed a few days ago, but is now available in v1.7.5. In the future, when submitting a bug report, please:

See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.
