### ISSUE TITLE
'title.replace' issue

### ISSUE THREAD

**Issue by aydn** [silviomoreto/bootstrap-select#1193]
![Capture 1](http://i.hizliresim.com/p9MrAo.png)
-
![Capture 2](http://i.hizliresim.com/kJ7VQJ.png)

IDK why but I think $.attr returns Number instead of a String type

**Comment by miqmago** [comment]
This happens when a numeric value is assigned as the selectpicker value:

```js
$('.mySelectPicker').selectpicker();
$('.mySelectPicker').val(1);
$('.mySelectPicker').selectpicker('refresh');
```
