### ISSUE TITLE
Accent-insensitive search: is it possible?

### ISSUE THREAD

**Issue by PaulJBis** [silviomoreto/bootstrap-select#1195]
Hello:

Sorry for posting here, since what I'm asking isn't strictly a bug report or a feature request, but... I just wanted to know whether, while using "data-live-search", the search could be made to work in accent-insensitive mode. I just saw this issue:

https://github.com/silviomoreto/bootstrap-select/issues/767

But I don't know whether it's been finally implemented or not. So... does this feature currently exist?

Thanks.

**Comment by caseyjhol** [comment]
This isn't in the documentation, but set `liveSearchNormalize` to `true`.
