### ISSUE TITLE
Numpad keys not accepted

### ISSUE THREAD

**Issue by lowerends** [silviomoreto/bootstrap-select#1204]
When trying to type numbers with the numpad part of the keyboard, it looks like the dropdown text field doesn't accept these keys (nothing appears in the text box). Is there any workaround or am I missing something here?

Thanks

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by caseyjhol** [comment]
This was fixed in v1.7.5.

**Comment by lowerends** [comment]
Thanks!
