### ISSUE TITLE
Feature request (or, please point me in the right direction)

### ISSUE THREAD

**Issue by shiruken1** [silviomoreto/bootstrap-select#1205]
Hey folks! I really love what you've done, and have used it for it's simplicity of code. I've begun learning Angular for a new project, and would like to use what you've built along with it, but it seems to be incompatible with the [UI-Bootstrap project](https://github.com/angular-ui/bootstrap)

Are there any plans to port/integrate this project with Angular? If not, where could I start with that?

Thanks!

**Comment by sovattha** [comment]
Hello, I don't know if it suits your needs but I personally use this project: 
https://github.com/joaoneto/angular-bootstrap-select

**Comment by jybleau** [comment]
FTR
Unfortunately, joaoneto's repository is not maintained anymore.

Creating my own directives was easier for me.

With repeat:
```
<select class="selectpicker" select-picker-bind-change-directive>
   <option ng-repeat="item in items" repeat-select-picker-directive>
      {{item}}
   </option>
</select>
```
I use a directive like this with $timeout to trigger the digest cycle:
```
  .directive('repeatSelectPickerDirective',
  ['$timeout',
    function ($timeout) {
      return function (scope, element, attrs) {
        if (scope.$last) {
          $timeout(function renderAfterPopulate() {
            $(element).parent().selectpicker('render')
          })
        }
      }
    }
  ])
```

If I bind to an event, I use a directive on the select tag:
```
.directive('selectPickerBindChangeDirective',
  ['$timeout',
    function ($timeout) {
      return function (scope, element, attrs) {
        $timeout(function bindOnChange() {
          element.on('changed.bs.select', function (event, index) {
            $timeout(function () {
              ...
            })
          })
        })
      }
    }
  ])
```

**Comment by caseyjhol** [comment]
I forked angular-bootstrap-select and created my own version that I actively maintain: https://github.com/caseyjhol/ng-bootstrap-select. I'm open to pull requests. The main advantage is the addition of support for option attributes (data-icon, data-content, title, etc.). The examples need to be updated as well.
