### ISSUE TITLE
Caret rendering strange in Internet Explorer

### ISSUE THREAD

**Issue by SeanSobeySage** [silviomoreto/bootstrap-select#1211]
Hi,

Since upgrading my bootstrap version to latest 3.3.5 I have started to see the dropdown caret looking strange in IE 10.

![capture](https://cloud.githubusercontent.com/assets/9336299/11332759/063c3f7a-91d1-11e5-825d-a89b15ab47e8.PNG)

I am not very familiar with css intricacies but it seems 'position: absolute' is contributing to this. Also, when the browser is small the issue goes away.

Bootstrap itself has addressed this issue here:
https://github.com/twbs/bootstrap/issues/16203
https://github.com/twbs/bootstrap/issues/17455
https://github.com/twbs/bootstrap/pull/16384
https://github.com/twbs/bootstrap/pull/16258

**Comment by caseyjhol** [comment]
This seems like an issue related to Bootstrap, and not bootstrap-select.
