### ISSUE TITLE
Invisible select is focusable when using data-mobile="true"

### ISSUE THREAD

**Issue by tbird2** [silviomoreto/bootstrap-select#1213]
To reproduce:
1. Open test.html from the bootstrap-select download.
2. Tab down to the select that says 'With data-mobile="true" option' under it.
3. Tab once more.
Notice that nothing appears to be highlighted. Now the invisible select element actually has the focus. You can use the arrow keys and type return to select different options for example. Maybe it should have tabindex=-1.

It happens in Firefox, Safari, and Chrome on Mac OS and Windows, and maybe every browser that supports tabbed navigation.

**Comment by caseyjhol** [comment]
Appears to have been fixed.
