### ISSUE TITLE
Duplicate on Chrome (v.43) and Firefox (v.42)

### ISSUE THREAD

**Issue by EtienneSerr** [silviomoreto/bootstrap-select#1215]
Greetings.

I put bootstrap-select 1.7.7 in my project and tried the very first example : 

<select class="selectpicker">
    <option>Mustard</option>
    <option>Ketchup</option>
    <option>Relish</option>
</select>

Unfortunately I always end up with this result : 
![bootstrapselect](https://cloud.githubusercontent.com/assets/15891982/11442567/ad1915e6-9516-11e5-9d61-368bfb94616f.PNG)

I also tried with the version 1.7.2 but I have the same result. Do you have any idea why I have this ?

Thank you in advance for your answer.

**Comment by Leon-O** [comment]
Can you put a jsfiddle link that duplicate the issue?

**Comment by caseyjhol** [comment]
Did you also update the CSS?

See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by caseyjhol** [comment]
Closing this until you can provide additional info.
