### ISSUE TITLE
Dynamic elements

### ISSUE THREAD

**Issue by joshuaadickerson** [silviomoreto/bootstrap-select#1216]
This is a question.

How do I use bootstrap-select on multiple dynamically created elements? It seems to either not show up or won't let me change the value of the select box.

**Comment by magna25** [comment]
if you would like to populate the options dynamically..something like below should work..
```
function dynamic(start, end, class){
for(i=start,i<=end;i++){
    $(class).append('<option>+i+</option>');
}
$(c).selectpicker();
}
dynamic(1, 30, '.className');
```

**Comment by joshuaadickerson** [comment]
I want to add selects dynamically. I want to add groups of parameters to a
form and use a select to say whether they should be treated as a string or
raw.

**Comment by caseyjhol** [comment]
After appending the new select, just call `$('#newSelect').selectpicker();`
