### ISSUE TITLE
Optgroup label missing when first option is disabled

### ISSUE THREAD

**Issue by clausbruun** [silviomoreto/bootstrap-select#1218]
Consider this example:
```html
<optgroup label="Water">
  <option value="1" disabled>one</option>
  <option value="2">two</option>
</optgroup>
```
When first option is disabled then the optgroup label is hidden.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by Khrysller** [comment]
link to reduced test case is: https://css-tricks.com/reduced-test-cases/
