### ISSUE TITLE
btn-link with data-toggle="modal" doesn't work in selectpicker header

### ISSUE THREAD

**Issue by brainx64** [silviomoreto/bootstrap-select#1226]
Please look at the example: http://jsfiddle.net/rtp6dt5n/

There are two btn-links with data-toggle="modal", one in the header of select picker, another - independent. Both have the same html. The one in the header of selectpicker does not toggle modal dialog. The independent one works fine. Why?

**Comment by brainx64** [comment]
By the way, please notice the clearfix workaround in my example. Selectpicker header looks awful without it.

**Comment by brainx64** [comment]
Just found the peace of code that prevents any element in the header from being clicked:

```javascript
  this.$menu.on('click', 'li.disabled a, .popover-title, .popover-title :not(.close)', function (e) {
	if (e.currentTarget == this) {
	  e.preventDefault();
	  e.stopPropagation();
	  if (that.options.liveSearch && !$(e.target).hasClass('close')) {
		that.$searchbox.focus();
	  } else {
		that.$button.focus();
	  }
	}
  });
```

Any ideas for workaround?

**Comment by caseyjhol** [comment]
```js
  $('#mySelect').data('selectpicker').$menu.on('click', 'li.disabled a, .popover-title, .popover-title :not(.close)', function (e) {
      $('#myModal').modal('show');
  });
```

**Comment by brainx64** [comment]
Thanks a lot for the idea! My final implementation also solves the problem with "li.disabled a" (disabled options) that loses original click handler as well and starts toggling modal when clicked. JSFiddle example updated: http://jsfiddle.net/rtp6dt5n/1/
