### ISSUE TITLE
Can't select option with spacebar

### ISSUE THREAD

**Issue by clausbruun** [silviomoreto/bootstrap-select#1234]
It's not possible to select/deselect options with [spacebar] when using __data-live-search="true"__. Looks like it searches for a _"space"_, even though the search field don't have focus.

Reduced test case: http://jsfiddle.net/clausbruun/dexL1Lme/3/

**Comment by caseyjhol** [comment]
This is the expected functionality. The search field always has focus. This allows you to search for a phrase without having to reselect the search field. It would be annoying if you were searching for, for example, "Kansas City" and it automatically selected whatever option was highlighted as soon as you pressed the spacebar.
