### ISSUE TITLE
Display issues with disabled selects in 1.8.x

### ISSUE THREAD

**Issue by Bazze** [silviomoreto/bootstrap-select#1235]
Hello!

I'm getting some graphical issues (and perhaps more?) after upgrading to 1.8.x. See image & source below. Seems to be a width issue and it only appears when disabled.

![1.8.x issues](http://i.imgur.com/9FwyPjF.png)

```html
<select 
	type="select" 
	class="bootstrap-select form-control" 
	label="Label here" 
	multiple="" 
	data-actions-box="true" 
	data-live-search="true" 
	disabled="" 
	data-selected-text-format="count>3" 
	tabindex="-98">
</select>
```

**Comment by caseyjhol** [comment]
What's your browser/OS?

**Comment by Bazze** [comment]
I had this issue in both Chrome & Safari:

Chrome:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
```

Safari:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
```

**Comment by nick6482** [comment]
Microsoft Edge 25.10586.0.0 on Windows 10 -  has same problem.
Firefox v42.0, v43.0 on Windows 10 -  has same problem.
