### ISSUE TITLE
LiveSearch Placeholder Text

### ISSUE THREAD

**Issue by tomaszbujnowicz** [silviomoreto/bootstrap-select#1241]
It would be nice to add an option where we can define the placeholder text on the liveSearch input field. 

The workaround for now is to use jQuery .attr('placeholder', .. function

**Comment by vladimirjohn** [comment]
I agree. It's a great addition for this one.

**Comment by caseyjhol** [comment]
You can already do this using the option `liveSearchPlaceholder` - not yet added to the documentation.
