### ISSUE TITLE
Bootstrap Select for Bootstrap 4

### ISSUE THREAD

**Issue by SatanicGeek** [silviomoreto/bootstrap-select#1242]
Hello !

I just want to know when do you release a version for Bootstrap 4.

I work on a project that will be deployed in a short time and to save time, we work with Bootstrap 4.

I tried to use the latest version but there are several problems. The list is displayed on the side with no style. I replaced btn-default by btn-secondary . I think the worry comes from the dropdown class.

I will try to change the js to work with Bootstrap 4.

**Comment by AndreaLombardo** [comment]
I'm interested too.
Thanks

**Comment by trippo** [comment]
I had a ugly fix but work fine until the stable release.
You can add to css file:
```
.bootstrap-select  li.selected a{
	background: #3086E4;
	color: white;
}
.bootstrap-select  li.selected a:hover{
	background: #256CB8;
}
```

And on js file add classes line
```
var generateA = function (text, classes, inline, tokens) {
	      classes += " dropdown-item";
```
and on Selectpicker.DEFAULTS declaration
```
    style: 'btn-secondary',
```

**Comment by caseyjhol** [comment]
Duplicate of #1135.

**Comment by gordett** [comment]
yehhh we need it

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Comment by ibraheem-ghazi** [comment]
i have created a new select js library called ```four-boot```
inspired from Bootstrap select 
check it here:
[FourBoot Select Picker](https://ibraheem-ghazi.github.io/four-boot/)

**Comment by abishekaasaari** [comment]
It looks **Great** @IbraheemAlnabriss

**Comment by ghardy2k** [comment]
i'm having a problem where the dropdown doesn't show my options.  however, if i inspect the page, i do see the options got filled in, it just wont show them when i click the dropdown.
