### ISSUE TITLE
With livesearch, when keypress, focus to search field isn't working

### ISSUE THREAD

**Issue by HenriqueSPin** [silviomoreto/bootstrap-select#1245]
I did wrapped the `.focus()` method on a `setTimeout` in line 1455. And give to the searchbox a new value of what was typed.
```javascript
setTimeout(function() {
    that.$searchbox.val(String.fromCharCode(e.which)).focus();
}, 0);
```

**Comment by authanram** [comment]
Solution: return; right after that.$searchbox.focus(); at line 1480 (v1.10.0).
We're in (!isActive ...) { ... }. So no further processing is needed after focusing the the search field.
