### ISSUE TITLE
Custom scroll theme

### ISSUE THREAD

**Issue by Pantela777** [silviomoreto/bootstrap-select#1252]
I use very nice scrolling plugin "**mCustomScrollbar**" https://github.com/malihu/malihu-custom-scrollbar-plugin
How I can to join "**bootstrap-select**" plugin:
![Scr](http://i.imgur.com/NdYRYAh.png)

**Comment by caseyjhol** [comment]
You'll probably have to modify the source code a bit (the `createDropdown` function). You might want to check on StackOverflow.
