### ISSUE TITLE
Call function when load

### ISSUE THREAD

**Issue by Pantela777** [silviomoreto/bootstrap-select#1261]
How I can to call function when **selectpicker()** is finish load data. I have big data, and page is broke, because first load data, and than add styles...

**Comment by caseyjhol** [comment]
See the `loaded.bs.select` event in the documentation: http://silviomoreto.github.io/bootstrap-select/options/#events

**Comment by Pantela777** [comment]
At documentation I see same event which can help to load styles... Can you tell me which event and how I can use? This is my problem... http://i.imgur.com/yWg840N.png

I just use this:
```
	$(function(){
		$('.selectpicker').selectpicker({
		});
	});
```
