### ISSUE TITLE
Rendering Problem

### ISSUE THREAD

**Issue by madrianr** [silviomoreto/bootstrap-select#1264]
Hi,
I have installed bootstrap-select with NuGet but it does'nt work as expected (see attached picture)

![dropdown](https://cloud.githubusercontent.com/assets/10518186/12457502/234d2028-bfa5-11e5-973f-626d580683e0.PNG)
![dropdown1](https://cloud.githubusercontent.com/assets/10518186/12457569/865ecf36-bfa5-11e5-8f62-fafe17f94d6e.PNG)

any idea why this rendering problem exists?

I use Asp.Net MVC 5:
@Html.DropDownListFor(model => model.Beratungsart, null, "", new { @class = "form-control selectpicker" })

regards Robert

**Comment by caseyjhol** [comment]
It looks like the CSS isn't being loaded. Might be a problem with the latest version on Nuget. Does v1.9.3 on Nuget work for you?

**Comment by madrianr** [comment]
Hi,

 

No, also version 1.9.3 and 1.8.1 doesn’t work…

 

I include bootstrap-select.js in my bootstrap Bundle…

 

            bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include(

                "~/Scripts/bootstrap.js",

                "~/Scripts/respond.js",

                "~/Scripts/bootstrap-select.js"));

 

Robert

 

Von: Casey Holzer [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. Januar 2016 23:13
An: silviomoreto/bootstrap-select
Cc: Robert Madrian (madrian e-dbsolutions)
Betreff: Re: [bootstrap-select] Rendering Problem (#1264)

 

It looks like the CSS isn't being loaded. Might be a problem with the latest version on Nuget. Does v1.9.3 on Nuget work for you?

**Comment by madrianr** [comment]
I have found the problem – I have forget to include the CSS: 

 

            bundles.Add(new StyleBundle("~/Content/css").Include(

                "~/Content/bootstrap.css",

                "~/Content/bootstrap-select.css",

                "~/Content/kendo.css",

                "~/Content/Site.css"));

 

thanks

 

robert

Von: Casey Holzer [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. Januar 2016 23:13
An: silviomoreto/bootstrap-select
Cc: Robert Madrian (madrian e-dbsolutions)
Betreff: Re: [bootstrap-select] Rendering Problem (#1264)

 

It looks like the CSS isn't being loaded. Might be a problem with the latest version on Nuget. Does v1.9.3 on Nuget work for you?
