### ISSUE TITLE
when live-search is enabled on a multiselect, and the dropdown is long enough to scroll, clicking to select an item resets scroll position

### ISSUE THREAD

**Issue by kjhangiani** [silviomoreto/bootstrap-select#1266]
This is a pretty annoying bug - when live search is enabled, and the dropdown list is long enough to have a scroll, clicking on an item when the list is scrolled down resets the scroll position back to the top of the dropdown, and focuses on the search field

I'm guessing there's some code to refocus on the input after each selection, however this makes the dropdown fairly annoying to use if the user scrolls down to select items.

The examples on your homepage all have too few items to test this behavior, but if you add a multiselect with live search and lets say the 50 states, you'll see the behavior in question.  Refocusing on the input is fine, but only if the input is positioned above the scrollable area so it does not disappear as the user scrolls down.

With live search, if I want to scroll down the list and select 3-4 items near each other, I will have to rescroll the list after each selection.

Is there an option to disable the refocus on livesearch? or a way to restructure the html/css of the livesearch input so it's not part of the scrollable area?

**Comment by Sudaraka007** [comment]
figured it out. jst have to add on touchstart event to the click event

**Comment by kjhangiani** [comment]
@Sudaraka007 could you be more specific? A gist or a fork or a PR? I'm going to have to investigate this next week but if you have a solution then I'm definitely interested!

**Comment by caseyjhol** [comment]
I can't replicate this in v1.9.4 using Chrome.

See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by Kayun** [comment]
@kjhangiani +1

**Comment by Kayun** [comment]
#1298

**Comment by caseyjhol** [comment]
Can somebody _please_ provide me with an example of this? Or at least provide your environment details?

**Comment by caseyjhol** [comment]
Closing this until somebody can explain what the problem is or provide an example.

**Comment by ghost** [comment]
So this is happening to me too on IE11. Only when live search is active and there are enough elements to need a scrollbar

![dc73ffe006ea516c0c4c037b26ece210](https://user-images.githubusercontent.com/20707722/46192041-0ff30f00-c2fa-11e8-9d45-5dbcb5c94f72.gif)

After investigating a bit it looks like in IE it fires the $searchbox.on('input propertychange') function. This does not happen in chrome/edge.

![ie](https://user-images.githubusercontent.com/20707722/46192179-7c6e0e00-c2fa-11e8-9676-05b7227895c0.PNG)

Edit: So after removing the liveSearchPlaceholder:'XXXXX', property on selectpicker.defaults it doesnt happen anymore.

**Comment by vertamin** [comment]
So after deleting the liveSearchPlaceholder:'XXXX' property on selectpicker.defaults it doesn't happen anymore.
