### ISSUE TITLE
data-min-options

### ISSUE THREAD

**Issue by Khrysller** [silviomoreto/bootstrap-select#1270]
Can we have a `data-min-options`? So we can set the minimum options allowed to select just like in `data-max-options`?

**Comment by caseyjhol** [comment]
This has already been discussed in #1010 and #1022.

> I'm not really sure how something like this would be implemented as a feature. This is a validation thing on your end, and you'll want to check that the select has an option selected before submitting the form.

> Hrmm...that seems like poor UX. What if they want to deselect that option and select another option?
