### ISSUE TITLE
An option to close the menu

### ISSUE THREAD

**Issue by lovedota** [silviomoreto/bootstrap-select#1271]
Hi @silviomoreto 
It will be nice if we have an option to close the menu by *$(select).selectPicker('close')* *$(select).selectPicker('open')*

Thanks !

**Comment by silviomoreto** [comment]
@lovedota for sure that would be great if we have this option. Can you do that and create a pull request?

**Comment by caseyjhol** [comment]
You can now do this using the `toggle` method. http://silviomoreto.github.io/bootstrap-select/methods/#selectpickertoggle

**Comment by nowherenearithaca** [comment]
but what if you don't know if it's open or closed, and want to make sure it is closed?

**Comment by rajvasani** [comment]
> You can now do this using the `toggle` method. http://silviomoreto.github.io/bootstrap-select/methods/#selectpickertoggle

I'm interested in this too.
How can we know that dropdown is open or closed?
