### ISSUE TITLE
Live search slow in IE

### ISSUE THREAD

**Issue by Robelind** [silviomoreto/bootstrap-select#1275]
Hi.
I'm populating the select with about 3000 entries and when using live search in IE11, the experience is quite bad. When writing e.g. 3 characters it takes literally seconds for the select to do the search.
Doing the same thing in Firefox shows acceptable performance.

Bootstrap-select 1.9.4, Windows 7, jQuery 2.14, Bootstrap 3.3.5

**Comment by MOKuper** [comment]
I also am experiencing the same difficulty with a little over 4000 records. Chrome is really slow at live search, taking 6 seconds or more when fully typing a name. In firefox it is still slow, but remarkably better. 

Using Bootstrap-select 1.10.0, mac el captan, jquery 1.11.3, bootstrap 3.3.2

**Comment by git-volver** [comment]
In fact, all browser I tested is so slow when the records are over 2 thousands... Big problem for my system...

Using Bootstrap-select 1.10.0, jquery 1.12.2, bootstrap 3.3.6

**Comment by omggga** [comment]
Check function with delegating on "input propertychange" event.
There are lots of work with DOM: filtering (2 times), escape function, replacing and html inserting and other. If you have more than 1000 entries and some optgroups, it works very slow in all browsers.

The only way i see now is to set throttling and increasing live-search keyword length from zero to 3 or more. Thats not removing the problem, but resolving some user UI lag questions.

**Comment by ataft** [comment]
Are there any updates on the performance issues?

I opened issue https://github.com/silviomoreto/bootstrap-select/issues/1229, suggesting virtualization when scrolling on large lists ([ag-grid](https://www.ag-grid.com/) does this very well). Perhaps ambitious, but having the ability to load from JSON (issue https://github.com/silviomoreto/bootstrap-select/issues/1151), live search against the JSON, and have virtual scrolling would solve all the performance issues and allow for very large lists. Perhaps some of that is covered by the Ajax Bootstrap Select clone, referenced in issue https://github.com/silviomoreto/bootstrap-select/issues/953, but I don't need ajax search. It would be great to not even have to have the SELECT in the DOM.

Again, this might be too ambitious, but would enable people to have as many bootstrap selects as they want with as many options as they want without any issues.

**Comment by xssunircomercial** [comment]
Help me
https://github.com/silviomoreto/bootstrap-select/issues/1650

**Comment by caseyjhol** [comment]
I just added a virtual scrolling feature (which results in instant searching) in the [virtual-scrolling](https://github.com/silviomoreto/bootstrap-select/tree/virtual-scrolling) branch. It's still a WIP, and there are a few features missing, some I'm aware of (the startsWith feature for example), and some I'm sure I'm not. Try it out - I'm looking for feedback. Please post all findings in #1229.

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
