### ISSUE TITLE
Customize token separator in multiple select.

### ISSUE THREAD

**Issue by nuukcillo** [silviomoreto/bootstrap-select#1281]
Hello, 

I have a select with people full name in this format:
 _"Surname, Name"_. 
So when I made a multiple select they appear like this:
 _"Doe, John, Ren, Kylo, Solo, Han"_

So, is there a way to change the token separator?

**Comment by caseyjhol** [comment]
Yes, use `multipleSeparator`. http://silviomoreto.github.io/bootstrap-select/options/
