### ISSUE TITLE
Is there a way to apply custom css to select options?

### ISSUE THREAD

**Issue by regimani27** [silviomoreto/bootstrap-select#1282]
I am using bootstrapselect with AngularJs and need to highlight some options based on the JSON property. For eg. If the status of a particular option is 'Locked' then that option need to be displayed in red color. I couldn't find an option in the docs. 

Any help would be appreciated.

**Comment by caseyjhol** [comment]
You can add a class and/or set a style on individual options.

http://silviomoreto.github.io/bootstrap-select/examples/#style-individual-options

```html
<option class="red" style="font-weight: bold;">Locked</option>
```

Also, it's still a WIP and the documentation needs to be updated, but if you're using bootstrap-select with Angular, I recommend checking out my directive https://github.com/caseyjhol/ng-bootstrap-select

**Comment by wreid306** [comment]
Adding to this, is there any way of acheiving this using an asp:DropDownList instead of a select
