### ISSUE TITLE
How to get the val by click 'SelectAll'

### ISSUE THREAD

**Issue by vlux** [silviomoreto/bootstrap-select#1284]
I used the code below to get the selected val.
```
var sl = $("#id")
sl.on("changed.bs.select", function(e) {
		console.log(sl.val())
	})
```
But when I click the 'SelectAll', the console didn't log so how can I get the all values by the 'SelectAll'

Thank you guys!

**Comment by caseyjhol** [comment]
Currently `changed.bs.select` isn't fired when "Select All" or "Deselect All" are clicked. It should be, but that event is mainly used so you can know which option was actually changed when the select value is changed (not possible with jQuery's `change` event). I'll fix this in an upcoming update.

You can fix it in your own code by adding `that.$element.trigger('changed.bs.select');` after [line 1248](https://github.com/silviomoreto/bootstrap-select/blob/master/dist/js/bootstrap-select.js#L1248)

**Comment by vlux** [comment]
It works! :+1: 
Thank you casey. Hope the Bootstrap-Selec' Long Live :)

**Comment by crevete** [comment]
@caseyjhol Your fix is not exactly correct. If I select all options, then I call ```selectAll```, the ```changed.bs.select``` event should not be fired. It should ONLY be fired when the value are really changed. Same issue with ```deselectAll```.

**Comment by aval-sarri** [comment]
How do I get if selectAll or DeselectAll is clicked, in changed.bs.select event? I see undefined

**Comment by dipan-provlg** [comment]
We have separate issue for this and it is [here ](https://github.com/silviomoreto/bootstrap-select/issues/1375). Is there anything at this moment for catching `Select All` or `Deselect All`?
