### ISSUE TITLE
optgroup labels not displaying if optgroup added via Jquery?

### ISSUE THREAD

**Issue by pgoldweic** [silviomoreto/bootstrap-select#1288]
I only seem to get the optgroup labels displayed if they were added statically in the HTML. However, when building dynamic menus, I seem to be unable to get them displayed (the only thing that displays is a divider line). Am I missing something or this is actually a bug? Thanks.

**Comment by dgirgenti** [comment]
You need to call `.selectpicker()` again to re-generate the markup. There is nothing listening for changes to the initial `<select>`

**Comment by pgoldweic** [comment]
I see. Thanks!

**Comment by shostack** [comment]
I have the same problem but it's not fixed by calling .selectpicker('refresh'). I can see the optgroup entries in the select html but they're not carrying over to the dropdown menu li though the options are.
