### ISSUE TITLE
Auto close the menu if maxOptions is set to 1

### ISSUE THREAD

**Issue by Pantela777** [silviomoreto/bootstrap-select#1290]
I use this option, but want to auto close option block, because **data-max-options="1"**
```<select name="user" data-container="body" class="selectpicker show-menu-arrow" data-max-options="1" title="-Select-" multiple>```

I use this option method, because if I use without "**multiple**" I can't choice empty options.
I find this, but how can add **data-max-options** option?

**Comment by Pantela777** [comment]
I add **that.options.maxOptions == false** and it's work, please add to next update version.
```// Don't close on multi choice menu
if (that.multiple && that.options.maxOptions == false) {
  e.stopPropagation();
}```

**Comment by caseyjhol** [comment]
Just do this instead:

```html
<select name="user" data-container="body" class="selectpicker show-menu-arrow" title="-Select-">

**Comment by ottokupradze** [comment]
I try this way, but have problem, when I want to unchecked choose option, it's impossible...

**Comment by Pantela777** [comment]
I try this way, but have problem, when I want to unchecked choose option, it's impossible...

**Comment by caseyjhol** [comment]
Ah, ok - I see the issue now. I can integrate this into the next version, but I'll use `if (that.multiple && that.options.maxOptions !== 1)` instead.
