### ISSUE TITLE
getListOfSelectedIndex

### ISSUE THREAD

**Issue by akaban01** [silviomoreto/bootstrap-select#1292]
As .val returns a list of selected values, is there a function which returns list of selected index or access to (something similar to) selectedIndex property which has list of selected index?
In my case, I have an array of json objects which is huge, if I have the index then I would need to search through the whole array.

**Comment by linkzyr** [comment]
hello!
how do dou solve  this  issues？

**Comment by akaban01** [comment]
set value as index number
<option value="0" ...
