### ISSUE TITLE
select element no longer hidden since v1.8.0

### ISSUE THREAD

**Issue by MichaelMerkel** [silviomoreto/bootstrap-select#1295]
hi.

i just realized that beginning with v1.8.0 the following lines in the .css file are no longer available:

`
select.bs-select-hidden,
select.selectpicker {
  display: none !important;
}
`

this leads to a somewhat "flickery" display if you have a larger site using a select picker. because the select-element may be rendered first (and really displayed) before the actual select-picker button is created and rendered. causing the select element to be visible for ~1 second before the screen page is redrawn.

why has this been removed? can this be readded?
(i readded it on my own page to get rid of the problem)

thanks in advance and regards
michael

**Comment by ducman** [comment]
+1 on this. I'm on v1.9.4 and the original select element is visible along with the bootstrap select.

The css line that @MichaelMerkel  mentioned was removed while additional css lines ```.bootstrap-select > select``` was add (hence the demo site is working). My original select is a sibling of ```.bootstrap-select``` instead of a child.

**Comment by MichaelMerkel** [comment]
thanks @caseyjhol !!
working fine again.

regards....
michael
