### ISSUE TITLE
Check Mark

### ISSUE THREAD

**Issue by saccccchin** [silviomoreto/bootstrap-select#1301]
I was trying to update the selectpicker to lastest version. 
I feel like i found a bug with check mark that appears in the option. 
Javascript appends check mark with i tag and css targets span with span.check-mark

**Comment by caseyjhol** [comment]
A `span` tag is appended...not an `i` tag.

https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L524
