### ISSUE TITLE
Thanks, and please add link to solveforall.com

### ISSUE THREAD

**Issue by jtsay362** [silviomoreto/bootstrap-select#1304]
Hi! And thanks for making this component which is so much better than ordinary HTML selects.

I'm using bootstrap-select in my customizable, ad-free, private, and hackable search engine, which is at solveforall.com. I use it in a custom React component which wraps it (would you be interested in this by the way? I could give it to you as a code example, or maybe make my own NPM module). The component is used to select many things, most notable sharing destinations and custom search engines to configure. 

Would you please add a link to my site? A logo can be downloaded here:
https://solveforall.com/resources/images/apple-touch-icon-72x72-precomposed-v2.png

Thank you for your consideration.

**Comment by caseyjhol** [comment]
Any chance you have a logo that also has text with it? And yea, feel free to link me to the React component if you've made a repo for it. I'm planning on adding an integrations/plugins section for bootstrap-select to link to integrations others have made, so that would be great.

**Comment by jtsay362** [comment]
Casey, thanks for the reply. What resolution would you like? I can create one custom for your sizing requirements.

I will definitely link back once I publish the React component. By the way, you've been on my acknowledgment page for a while now: https://solveforall.com/acknowledgments

**Comment by caseyjhol** [comment]
Looking at it again, that resolution isn't bad, but might as well double it (296x84).

**Comment by jtsay362** [comment]
Here you go. Thanks in advance!
![solveforall_logo_with_text_296x84](https://cloud.githubusercontent.com/assets/1079646/13192597/9426efec-d722-11e5-8192-1516467f054e.png)

**Comment by jtsay362** [comment]
Awesome, thanks so much!
