### ISSUE TITLE
Anyone can solve Bootstrap Select combining with Cascading.js filter?

### ISSUE THREAD

**Issue by faliqaiman** [silviomoreto/bootstrap-select#1307]
Im stuck while using bootstrap select and cascading.js to make it more dynamic in searching option.

Here's my fiddle that stuck, [jsfiddle](https://jsfiddle.net/faliqaiman/6mnhgc1d/)

And this my second try, but it won't solve also, [jsfiddle](https://jsfiddle.net/2pza5/1292/)

Any chance can it done here?

Thank you.

**Comment by caseyjhol** [comment]
I'm confused - what is your issue?

**Comment by faliqaiman** [comment]
Would like to use bootstrap-select with cascading.js

Please see jsfiddle..

**Comment by caseyjhol** [comment]
I saw the jsFiddle. What is the expected outcome? What is happening instead?

**Comment by faliqaiman** [comment]
Would like to create filter selection, and integrated with cascading.js.

![bs-select-cascading-01](https://cloud.githubusercontent.com/assets/16832340/13339544/850950f8-dc64-11e5-94e1-945588aaa5f3.jpg)

When user click option 1, then can go to the option 2. something like nested selected.

After both option selected, the table below will filtering with the selected option.

It's a filtering function, by using bootstrap-select + cascading.js + jQuery filter.

Any chance to make this happen?

**Comment by jnacaratto** [comment]
Hello, I did a test and found the solution, after $ locations.html (html); You must add $ ('# location'). Selectpicker ('refresh'); This method updates the selectpicker and renders it, Regards

**Comment by faliqaiman** [comment]
@jnacaratto thanks! it's works.
