### ISSUE TITLE
How to preselect values?

### ISSUE THREAD

**Issue by Johnnychaos** [silviomoreto/bootstrap-select#1308]
I would like to preselect values using HTML but adding "selected" to option tag doesn't seem to work.

**Comment by caseyjhol** [comment]
Setting the selected attribute works in my implementation. What does your code look like? See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by Johnnychaos** [comment]
Sorry, my fault. I was calling "deselectAll" somewhere in my script.
