### ISSUE TITLE
Live search got stuck, on some chars

### ISSUE THREAD

**Issue by authanram** [silviomoreto/bootstrap-select#1310]
Hi there, 

don't know if the issue was already posted here before. I've read a lot of issues here, but can't find it.

Example-URL: https://silviomoreto.github.io/bootstrap-select/examples/
Tested in Chrome 48 and Firefox 44 (both on Mac El Cpt.)

How to reproduce:
1. go the url above
2. scroll down to the section "Live search"
3. click the select (at the section "Live search"), just to focus it
4. tab (with the keyboard) to the next select element at the section "Key words"
5. hit the char "h" on your keyboard

Now the live search field is not focused and something is completely wrong with the select element.

The funny thing is, this will happen only with some chars. So please use the char "h" to reproduce that. If you type "a" everything is fine.

The biggest shit with that is, if the user runs into this issue and hits "backspace" on the keyboard, the browser will navigate back and all entered form data will be lost. *hmpf*

I've discovered that today because of a tracking analysis on my online service. I've recognized that a lot of users start filling a form, navigate back to the page before, navigate forward again to the form and send it afterwards. That means, a lot users called the same url twice or more. Regarding that i've had a closer look to that form and found that issue.

So, for me/my service, this is a tremendous issue at the moment, because the conversion is decreasing because of that. ^^

**Comment by authanram** [comment]
Solution: return; right after that.$searchbox.focus(); at line 1480. We're in (!isActive ...) { ... }. So no further processing is needed after focusing the the search field.

**Comment by caseyjhol** [comment]
Good catch - thanks for posting the solution.
