### ISSUE TITLE
.val() not working in the last version?

### ISSUE THREAD

**Issue by Khrysller** [silviomoreto/bootstrap-select#1311]
In version 1.7.6 I could get values from a select and transfer to a input using:

**From:**
```
<select value="" name="Categoria" id="Categoria" class="selectpicker Categoria" data-style="btn-primary" data-width="100%" data-selected-text-format="count>3" title='Select the Category(ies)' multiple>
	<option value="A" disabled>A</option>
	<option value="B" selected>B</option>
	<option value="C" selected>C</option>
</select>
```

**To:**
`<input type="hidden" class="ChangeCategory" name="ChangeCategory" value="Low, Minor, Major">`

**Using:**
```
var f2 = function(){
$('.ChangeCategory').val($(".Categoria").val());
}
f2();
```

In the last version it doesn't work anymore.

**Comment by caseyjhol** [comment]
There's no reason why this wouldn't work, as you're still using the standard jQuery `.val()` method. Can you link to a jsFiddle?

**Comment by MuTLY** [comment]
There's two "selected" options there. This isn't valid HTML code, and that's probably why his code isn't working.

**Comment by AshPowell** [comment]
Isn't working for me either - regardless of selected value, jquery returns that the value is empty, was working fine before

**Comment by AshPowell** [comment]
sussed it, selecting just the class name for the value actually returns 2 values, the one you expect then an empty (I'm assuming the classes are duplicated) - If you target select. yourclass then it'll return as you expect, for example:

`$('select.ChangeCategory').val();` instead of `$('.ChangeCategory').val();`
