### ISSUE TITLE
Click on dropdown button, no list of options opens

### ISSUE THREAD

**Issue by daN4cat** [silviomoreto/bootstrap-select#1312]
Connected to #1306 (the posting after it was closed), I've the same issue.
If I click on the dropdown button no list of options opens.

Checking with Chrome Inspector I can see that `<div class="btn-group bootstrap-select show-menu-arrow fit-width">` is "refreshed" on click but no `open` is added.
If I manually add the `open ` the drop down option list opens, that's what happens on your example page.

I use 1.10.0, js & css. I use a bootswatch flatly bootstrap 3 css theme and js.

I do not really understand what's wrong, here the html from the rendered page:

```

<form action="<..url..>/change_mode" id="mode_form" method="post" accept-charset="utf-8">
	<label id="mode_label">Register Mode</label>
	<div class="btn-group bootstrap-select show-menu-arrow fit-width">
		<button type="button" class="btn dropdown-toggle btn-info btn-sm" data-toggle="dropdown" title="Sale" aria-expanded="false">
			<span class="filter-option pull-left">Sale</span>
			&nbsp;
			<span class="bs-caret"><span class="caret"></span></span>
		</button>
		<div class="dropdown-menu open" style="max-height: 548px; overflow: hidden; min-height: 0px;">
		<ul class="dropdown-menu inner" role="menu" style="max-height: 536px; overflow-y: auto; min-height: 0px;">
			<li data-original-index="0" class="selected"><a tabindex="0" class="" style="" data-tokens="null"><span class="text">Sale</span><span class="glyphicon glyphicon-ok check-mark"></span></a></li>
			<li data-original-index="1"><a tabindex="0" class="" style="" data-tokens="null"><span class="text">Return</span><span class="glyphicon glyphicon-ok check-mark"></span></a></li>
		</ul>
		</div>
		<select name="mode" onchange="$('#mode_form').submit();" class="selectpicker show-menu-arrow" data-style="btn-info btn-sm" data-width="fit" tabindex="-98">
			<option value="sale" selected="selected">Sale</option>
			<option value="return">Return</option>
		</select>
	</div>
</form>
```

**Comment by daN4cat** [comment]
As additional note, I use `smalot-bootstrap-datetimepicker` and `jasny-bootstrap` widgets and there are no issues. They work fine.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by daN4cat** [comment]
1. I don;t seem to find any other issue than the one reference (where I don't see any solution)
2. I used the latest master
3. OS: Windows 7, Browser: Google Chrome (latest), jQuery: 1.12.1, jQueryUI: 1.11.4, bootswatch-dist: 3.3.6-flatly, bootstrap-select:1.10.0 (with latest master as of today).

4. & 5. I'll see if I'm able to reproduce something and post here a link.

**Comment by daN4cat** [comment]
Here the issue on jsFiddle: https://jsfiddle.net/FrancescoUK/y8rb81er/3/#&togetherjs=haASb47QKm

**Comment by daN4cat** [comment]
jsFiddle is really messy... it's difficult to understand when something is saved or not.

**Comment by daN4cat** [comment]
I think I found the culprit, it's the bower & grunt scripting in opensourcepos that is pulling in two versions on boostrap.js in the global opesourcepos.js.

I close this issue here.

**Comment by theshadow124** [comment]
I know this is closed, but thanks for posted this, was having the same issue, loaded bootstrap, then datatables, but datatables was loading bootstrap as well, then I loaded bootstrap-select and it killed things.

**Comment by erensogut** [comment]
Closed but help me a lot.It works like a miracle.Thx

**Comment by PisaJan** [comment]
Thanks for this post it helped a lot!
