### ISSUE TITLE
Problem loading bootstrap-select items using jquery

### ISSUE THREAD

**Issue by ffkammer** [silviomoreto/bootstrap-select#1317]
Hi,

I've 3 selects on my form and I'm loading the items using jquery from a database.

Sometimes (just sometimes) the items aren't loaded into the Boostrap-Select. If I remove the selectpicker class from the selects everthink works fine all the time. The biggest problem is that I don't receive any error.

Someone had this problem? Are there a solution for it?

I'm creating the selects as bellow:

```
<select name="cmbStatus" id="cmbStatus" class="selectpicker" multiple title="Status da OS">
  <option value=""></option>
</select>
<select name="cmbTipoOS" id="cmbTipoOS" class="selectpicker" multiple title="Tipo de OS">
  <option value=""></option>
</select>
<select name="cmbResp" id="cmbResp" class="selectpicker" multiple title="Responsável"></select>
```

And I'm loading the items with jQuery like bellow:

```
$.getJSON('/php/select.php', function(result) {
  $.each(result, function() {
    $('#cmbStatus').append($("<option/>").val(this.value).text(this.name));
  })
});
```

On this image you can see of of the selects without any item.

<img width="1187" alt="captura de tela 2016-03-02 as 10 40 24" src="https://cloud.githubusercontent.com/assets/3179444/13461897/3758366e-e063-11e5-8c05-9c53cc592475.png">

Thanks

**Comment by caseyjhol** [comment]
Try this:

```js
$.getJSON('/php/select.php', function(result) {
	var options = [];

	$.each(result, function() {
		options.append('<option value="' + this.value + '">' + this.name + '</option>');
	});

	$('#cmbStatus')
		.append(options.join(''))
		.selectpicker('refresh');
});
```

**Comment by ffkammer** [comment]
Hi @caseyjhol it works!

Than I decided to test with my code just adding the method `$('#cmbStatus).selectpicker('refresh')` after loading the results and it worked too, I think that is necessary refresh the select after reloading the data.

I think that is a bug because sometimes the data is loaded and sometimes not.

Thanks for your help
