### ISSUE TITLE
show-tick on wrong item when using Firefox 3.6.4

### ISSUE THREAD

**Issue by grahama** [silviomoreto/bootstrap-select#132]
When using firefox 3.6.4 on Linux x64 (as per Fedora 14) and on 3.6.28 on Windows (XP)

Goto http://silviomoreto.github.io/bootstrap-select/ and search for "selectpicker show-tick" on the page, in that example, shown below, if you select Mustard, then pull-down the selector, Ketchup is ticked.

  <select class="selectpicker show-tick">
     <option>Mustard</option> <--- select this
      <option>Ketchup</option> <-- but this is ticked
      <option>Relish</option>
  </select>

This does not happen on Chome, IE or Firefox 20 in on Windows (XP).

You can download FF 3.6.x from:
http://support.mozilla.org/en-US/kb/install-older-version-of-firefox

**Comment by caseyjhol** [comment]
Bootstrap doesn't support Firefox 3.6 as of August 2013. Closing.
