### ISSUE TITLE
When Bootstrap 4 support?

### ISSUE THREAD

**Issue by andreyugit** [silviomoreto/bootstrap-select#1320]
When Bootstrap 4 support?

**Comment by saucysalamandar** [comment]
Bootstrap 4 is in Alpha stage, meaning it has to reach the stage of stable release so that the author can script the library for Bootstrap 4.

**Comment by caseyjhol** [comment]
Duplicate of #1135. Thanks @saucysalamandar.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
