### ISSUE TITLE
Data Icon Missing on Mobile Browser

### ISSUE THREAD

**Issue by ogrampowell** [silviomoreto/bootstrap-select#1336]
I am using the bootstrap-select component on my website. I have added the data-icon attribute which i set dynamically via jstl. This works like a champ when I am on a desktop browser. 

I have added the mobile select appropriately and native display is working when I test on my iphone or ipad except for the fact that the data-icon does not appear when viewing the displayed options. 
Once I select an option, the icon appears in the selected choice.

In addition, I have tried changing the color of the text and the text background dynamically via the style attribute as well. Again, the changes work when on a desktop browser but not in the mobile browser. 

If there anything I am missing or can someone help me figure out how to make the data-icon image appear when viewing on a mobile browser? 

BTW- I am not a css guru and tried dabbling with webkit css settings to no avail thinking the mobile safari browser settings needed to be modified.

**Comment by caseyjhol** [comment]
It's not currently possible to style the native select menu on mobile devices.
