### ISSUE TITLE
Title should not change

### ISSUE THREAD

**Issue by techhysahil** [silviomoreto/bootstrap-select#1340]
Is it possible to use multiselect/select but on selection of items it should show tick mark in options but should not change the title.

Actually i want selct/multiselect title to be static.

I really appreciate if anyone can help me with this one.

**Comment by caseyjhol** [comment]
Set `selectedTextFormat` to `static` (`data-selected-text-format="static"`)

**Comment by techhysahil** [comment]
thanks
