### ISSUE TITLE
Error if typing into live search dropdown and no options are available

### ISSUE THREAD

**Issue by tbrunner** [silviomoreto/bootstrap-select#1350]
If you try to dynamically create the options for the dropdown as they search (necessary when there are thousands of possible options), if what they typed results in displaying 0 options then every key press after gives the error Uncaught TypeError: Cannot read property 'not' of null. Should be an easy fix, just check that the $lis exists before removing the class.

boostrap-select.js line 1285         
var $searchBase = that.$lis.not('.is-hidden').removeClass('hidden').children('a');

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.
