### ISSUE TITLE
Callback to confirm before onchange

### ISSUE THREAD

**Issue by claudchan** [silviomoreto/bootstrap-select#1351]
Hi,
Is there any option / callback function that can perform a confirmation dialog before make selected?
I would like to do something like once the option select will prompt a confirmation dialog box to choose 'Yes" or "No". Anyone can share and guide me how to make this? Many thanks.

**Comment by caseyjhol** [comment]
Do something like:

```js
var $select = $('#select');
var selectVal = $select.val();

$select.on('change', function() {
    if (!window.confirm("Are you sure?")) { 
        $select.val(selectVal);
    }
});
