### ISSUE TITLE
Exception when is handling events in android mobile WebViewFragments

### ISSUE THREAD

**Issue by joserg** [silviomoreto/bootstrap-select#1354]
In line https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L136
the Event constructor is throwing exceptions because the protection in line
https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L134
is not enough when the constructor Event(name, options) is not defined and only is defined the  constructor Event().

This is happening to us when we change from version 1.4.3 to 1.10.0.

You are including the Event(...)  from 1.7.3

And we are happy only until 1.7.2  :-)

Maybe some like this could be a solution to the issue:

```
      if (typeof Event === 'function') {
        // For modern browsers
        try {
          event = new Event(eventName, {
            bubbles: true
          });
        } catch (error) {
          event = document.createEvent('Event');
          event.initEvent(eventName, true, false);
        }
```

**Comment by caseyjhol** [comment]
What version of Android mobile are you using? When using that same version, does it say your browser supports DOM event constructors here: http://rauschma.github.io/event_constructors_check/?

**Comment by joserg** [comment]
We are using it inside WebView, by example, the issue happens using it with these two user agent:

User-Agent=Mozilla/5.0 (Linux; U; Android 4.1.2; es-es; GT-N8000 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30

User-Agent=Mozilla/5.0 (Linux; Android 4.4.2; GT-I9515L Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36

**Comment by caseyjhol** [comment]
> Does it say your browser supports DOM event constructors here: http://rauschma.github.io/event_constructors_check/?

**Comment by joserg** [comment]
Ok,
we use the   http://rauschma.github.io/event_constructors_check/  in a webview and obtain this:

![device-2016-04-12-120125](https://cloud.githubusercontent.com/assets/748048/14456939/d5a758d6-00a7-11e6-9b84-c6e14680f75c.png)

and we have now submitted to you the results by pushing in the  "Submit to Browserscope" button.

We hope you have found this information useful.

**Comment by caseyjhol** [comment]
Hrmmm...seems like the JS didn't run - it should either say "YES" or "NO" after `Your browser supports DOM event constructors (background):`. Is JavaScript enabled on the browser?

**Comment by caseyjhol** [comment]
Closing until you can provide more info.
