### ISSUE TITLE
Render Issues in Bootstrap Modal

### ISSUE THREAD

**Issue by yugenekr** [silviomoreto/bootstrap-select#1358]
Hello,

I need to render two bootstrap-selects in bootstrap modal, but can't get it working properly.
Here's [jsFiddle](https://jsfiddle.net/yugene/tcpkg0om/6) with the code that in my environment actually works on the first load/button Add click (cannot reproduce correct load in fiddle), but fails on the second Add button click. Fiddle shows the issue right away, on the first click.

The second [fiddle](http://jsfiddle.net/yugene/zh0v1k04/5/) shows one of tested approaches that fails at the first attempt in my environment.

There're two reproducible issues in total with modal render I've encountered:
1. Dropdown-toggle part is always rendered. This is the best scenario, as still possible to select options and submit data.
2. Or options are not selectable, as if refresh wasn't called. 

Would appreciate any help from your side.

**Comment by caseyjhol** [comment]
Use a class other than `selectpicker` so it's not initiated via the data-api.
```html
<button data-action="open-modal-link-items" class="btn btn-success" type="button">
        Add
    </button>
<div class="hidden" id="link-items-select">
        
<div data-selector="link-items-inputs">
    <div class="form-group field-linkeditems-mbo_id required">
      <label for="linkeditems-mbo_id" class="control-label">
        Sale Item
      </label>

      <select data-live-search="true" name="LinkedItems[mbo_id]" class="select form-control show-menu-arrow show-tick" id="linkeditems-mbo_id" tabindex="-98">
          <option value="">Nothing Selected</option>
          <option value="1064">3 Pack Boxing Hand Wraps</option>
          <option value="509056">500ml Pop</option>
          <option value="509057">500ml water</option>
      </select>
  </div>

    <div class="form-group field-linkeditems-inf_id required">
      <label for="linkeditems-inf_id" class="control-label">Infusionsoft Product</label>
      <select name="LinkedItems[inf_id]" class="select form-control show-menu-arrow show-tick" id="linkeditems-inf_id" tabindex="-98">
        <option value="">Nothing Selected</option>
        <option value="18">$1 Trial</option>
        <option value="53">1C-TEST</option>
        <option value="107">5ML21</option>
        <option value="123">ACME Bird Seed</option>
        <option value="25">ACME Rocket Fuel</option>
    </select>
    </div>
</div>

```
```js
    function refreshBootstrapSelect() {
        $('div.bootbox-body .select').selectpicker();
    }
    $('body').on('click', '[data-action="open-modal-link-items"]', function (e) {
        e.preventDefault();
        var bootboxModal = bootbox.dialog({
            message: $("#link-items-select").html(),
            title: 'Link Items',
            buttons: {
                "Submit": {
                    className: "btn-default",
                    callback: function () {
                        var $modalElem = $('div.modal-dialog'), $dataElem, sendData, url;
                        return false;
                    }
                }
            },
            show: false
        });
        bootboxModal.on('shown.bs.modal', function () {
            refreshBootstrapSelect();
        });
        bootboxModal.modal("show");
    });
```

Or put the html directly into `message` instead of using `.html()`.

**Comment by yugenekr** [comment]
Thank you for the response.

I had to make both updates to make it work on the second modal open (the second Add button click).
Working example: https://jsfiddle.net/yugene/zh0v1k04/

**Comment by Supposer** [comment]
thank you very much

**Comment by 0xwang-coder** [comment]
this issue does'n work for me，and then I choose [Select2](https://github.com/select2/select2)，there is a good solution. [solution](https://stackoverflow.com/questions/18487056/select2-doesnt-work-when-embedded-in-a-bootstrap-modal/18487440#18487440)
