### ISSUE TITLE
Optgroup label shown when optgroup is empty

### ISSUE THREAD

**Issue by clausbruun** [silviomoreto/bootstrap-select#1363]
When using the option _hideDisabled_, then the __optgroup label__ is shown, even when all child  __options__ is hidden.

Reduced test case: http://jsfiddle.net/clausbruun/os813725/5/

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

This is already fixed in master. 33e3a4bb177f469a3aef266f448fe0b92ec7d90a
