### ISSUE TITLE
How to detect when bootstrap select is loaded, so I can load other script after

### ISSUE THREAD

**Issue by kevinmamaqi** [silviomoreto/bootstrap-select#1365]
I'm trying to run the following code, and it works fine from the console but not when I include it in the footer, after the document is loaded: 

`jQuery(document).ready(function($) { 
    var espSeleccionada = $('button[data-id="select-especialidad"]');
    espSeleccionada.on("click", function() {
        var x = $(this).text();
        $('#boton-prueba').text(x);
    });
});`

It seems that bootstrap-select requires more time to finish loading

**Comment by caseyjhol** [comment]
`loaded.bs.select`
http://silviomoreto.github.io/bootstrap-select/options/#events
