### ISSUE TITLE
Deselect All removes the selection only in searched fields not from all option

### ISSUE THREAD

**Issue by whitef89** [silviomoreto/bootstrap-select#1369]
In the new version 1.10.0 I face again with the problem described in the [issue 1154](https://github.com/silviomoreto/bootstrap-select/issues/1154) and [issue 976](https://github.com/silviomoreto/bootstrap-select/issues/976) issues which are marked as resolved.
Can you please check if this problem are still exists?

Thank you

**Comment by caseyjhol** [comment]
The current behavior is the desired behavior, and the problems described in those issues are different than what you're describing. Filtering the options and then clicking "Select All" only selects the options that are visible. Likewise, clicking "Deselect All" only deselects the options that are visible.

If you have more to report, please:

See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.
