### ISSUE TITLE
Checked items length are the same after 'changed.bs.select' when i click DeselectAll button

### ISSUE THREAD

**Issue by gtzinos** [silviomoreto/bootstrap-select#1376]

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by gtzinos** [comment]
Its a closed issue ? if yes why you didn't release it ?

**Comment by caseyjhol** [comment]
This isn't a closed issue, I just don't understand what your issue is, and you didn't provide your environment details, create an isolated and reproducible test case, or live example so I can actually see what the issue is.
