### ISSUE TITLE
changed.bs.select	Not Passing The Right Params To Event Handler Function

### ISSUE THREAD

**Issue by ksidibe** [silviomoreto/bootstrap-select#1378]
```
$('#my_select').on('changed.bs.select', function (e, clickedIndex, newValue, oldValue) {
		console.log('clickedIndex');
		console.log(clickedIndex);
		console.log('newValue');
		console.log(newValue);
		console.log('oldValue');
		console.log(oldValue);
		  // do something...
		});
```
prints the following:

> clickedIndex
>  1
> newValue
>  true
> oldValue
>  false

When I look through the source code where the changed event is triggered, I see this:
```
// Trigger select 'change'
          if ((prevValue != that.$element.val() && that.multiple) || (prevIndex != that.$element.prop('selectedIndex') && !that.multiple)) {
            // $option.prop('selected') is current option state (selected/unselected). state is previous option state.
            that.$element
              .trigger('changed.bs.select', [clickedIndex, $option.prop('selected'), state])
              .triggerNative('change');
          }
```
One would expect _prevValue_ and _that.$element.val()_ to be passed to the event instead of _$option.prop('selected')_ and _state_

**Comment by caseyjhol** [comment]
newValue and oldValue refer to the value of the changed option - either true or false - to see whether the option was changed to be selected or unselected, not the value of the select itself. However, oldValue is a bit redundant, as it's obviously always the opposite of newValue. It would also make more sense to refer to newValue as `selected` and oldValue as `unselected` to improve clarity. It would make more sense to also pass in the select's previous value. Passing in the select's current value is unnecessary, as it can easily be retrieved with `$(this).val()`.

**Comment by ksidibe** [comment]
@caseyjhol, thanks a lot for your prompt response.
You are right, selected and unselected would be more descriptive, and it's also true that since one is the opposite of the other, passing only one of them would streamline the code/api.

**Comment by GreggOD** [comment]
Thanks for this clearing up. I also thought oldValue would give the actual val. One can see how that would be handy.
