### ISSUE TITLE
disable preselection

### ISSUE THREAD

**Issue by geronimoooooooo** [silviomoreto/bootstrap-select#1390]
I have 1 entry in a data-live-search="true" dropdown menu. When I open the dropdown menu, the first item is already preselected. How to disable that behaviour? I would like to have no preselection. I need this because I have a "onChange"-method that will execute some code. If the only option is preselected, there is no way to reselect it and trigger the "onChange"-method.

```
<select class="selectpicker" data-live-search="true">
 <option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>
</select>
```

**Comment by caseyjhol** [comment]
This should work by setting the title attribute in v1.10.0, but looks like that functionality was broken in 5a7d0f32220a4d09f0cadc0f569d27b970bb1065. For now, your best option would be to either add the multiple attribute, or add `<option data-hidden="true"></option>` as the first option.

**Comment by caseyjhol** [comment]
This is now fixed in the master branch.
