### ISSUE TITLE
Selected List index? issue when populating from knockout.

### ISSUE THREAD

**Issue by Jab0rnal** [silviomoreto/bootstrap-select#1395]
It seems that there is an issue when creating the options of the select picker with a knockout observable array.

Repro steps using this [codepen](http://codepen.io/anon/pen/EKqJVb?editors=1010)
1. Open the select, select somebody,
2. Re-open the select, the correct person is selected <- working.
3. Click the load more people button
4. Open the select, select a person
5. Re-open the select, the incorrect person is selected in the list. (It is always the one before, if you select the first the last one is selected) <- break.

**Comment by caseyjhol** [comment]
Hrmmm...this has something to do with the placeholder. If you remove the title attribute, it works as expected.

**Comment by Jab0rnal** [comment]
Thanks for taking a look at this Casey, appreciate it. That was probably the only thing I didn't try to get the expected behaviour. Have you got any time frame for a release that will include the fix?
Its a great control that i would really like to keep using. Thanks for your hard work.

**Comment by caseyjhol** [comment]
Hopefully I'll be able to have a fix out by next week, as part of v1.11.0.

**Comment by Jab0rnal** [comment]
Thanks Casey, I look forward to the new release. Thanks for the suggested work around also, I will give that a go tommorrow.

**Comment by Jab0rnal** [comment]
Any update on v1.11.0 release date?

**Comment by stodge** [comment]
This may relate to an issue I'm having - any updates on a fix? Thanks.

**Comment by caseyjhol** [comment]
The title option should always be the first option, but depending on the way the options are updated, that isn't always the case (you'll see that it is moved to the end after loading more people in your example). This will be fixed in v1.13.0.

**Comment by caseyjhol** [comment]
Available in v1.13.0-alpha.
