### ISSUE TITLE
Populate dropdown onclick

### ISSUE THREAD

**Issue by guruwanabe** [silviomoreto/bootstrap-select#1396]
The fact that the `<select>` remains in DOM and the plugin is adding the same content is a SEO issue, I would love an option to generate `<li>'s`   onclick event. 

Any opinions about this?

**Comment by caseyjhol** [comment]
You might try using the container option - e.g. `data-container="body"`. When the container option is used, the menu and its inner li elements are generated dynamically each time the menu is opened (rather than being inserted into the DOM by default.

**Comment by guruwanabe** [comment]
I've tried that, the inner `li` are first generated @ doc ready then moved in that container. I've modified the script to suit my needs, but i think it's a very usefull option to have.
