### ISSUE TITLE
controling button size

### ISSUE THREAD

**Issue by drormik** [silviomoreto/bootstrap-select#1405]
i'm not sure if this is a bug or a request, but wondering if "bootstrap-select" was supposed to support Bootstrap's button size class such as **btn-lg** ,  because right now i only see  "narrow" type of buttons produces by bootstrap-select
in the attached example you'll see bootstrap-select to the right (smaller button), and bootstrap's btn-lg (large button)to the left
![29f30ab](https://cloud.githubusercontent.com/assets/5310157/15801555/a264dc5e-2aa1-11e6-8df6-57d91bfbcbed.jpg)

**Comment by caseyjhol** [comment]
Set `data-style="btn-default btn-lg"`.

**Comment by drormik** [comment]
Thanks!
