### ISSUE TITLE
Remove blue border styling

### ISSUE THREAD

**Issue by papakonstantinouko** [silviomoreto/bootstrap-select#1406]
![capture](https://cloud.githubusercontent.com/assets/4752620/15883933/f969b170-2d4c-11e6-9968-b33a90e925c9.PNG)

Hello, as you in the pic, there is a light blue border around the select element when I click it and expands. Can you tell me how to remove it? I have tried various css selection but did not do the trick.

**Comment by sofiyastrochyk** [comment]
Hi, how about this:
```
.bootstrap-select .dropdown-toggle:focus {
    outline: 0 !important;
}
```
