### ISSUE TITLE
Changed event fired by selectAll method

### ISSUE THREAD

**Issue by sofiyastrochyk** [silviomoreto/bootstrap-select#1408]
I have a select picker with "Select all" option. When clicked, it should select all other options.
What is expected: 
- Change event is triggered once when any option is clicked.

What actually happens:
- Event is triggered twice, when "Select all" is clicked AND when value is changed programmatically, i.e. when 'selectAll' method is called.

Here is an example:
https://jsfiddle.net/rua40ayh/1/

I see that changed.bs.select and change events are triggered by the following code

```
      this.$element
        .trigger('changed.bs.select')
        .triggerNative('change');
```

in lines 1485-1487.
I would like to either have this disabled or to have an option "Trigger events" like this:
`$(this).selectpicker('selectAll', false);`

**Comment by caseyjhol** [comment]
This should be fixed, but let me know if it's not.

**Comment by joseluiz98** [comment]
I'm still having this problem!
