### ISSUE TITLE
Dynamically setting values

### ISSUE THREAD

**Issue by virik** [silviomoreto/bootstrap-select#1423]
Hi, 

I'm not sure if this is already mentioned, but I couldn't find anything about it.

How come this works:
`$("#product form select").selectpicker("val", ["1","2","3"]);`

But not this:
```
var str = '["'+row.categories.replace(/,/g, '","')+'"]';  // Equals: ["1","2","3"]
$("#product form select").selectpicker("val", str);
```
row.categories is just a comma separated list, like 1,2,3,4,5

Is this a bug?

**Comment by caseyjhol** [comment]
No, this isn't a bug. You need to pass through an array, not a string.

Technically you're doing `$("#product form select").selectpicker("val", '["1","2","3"]');` instead of `$("#product form select").selectpicker("val", ["1","2","3"]);`.
