### ISSUE TITLE
HTML text in "title" will only render in "multiple" -mode

### ISSUE THREAD

**Issue by jefvhal** [silviomoreto/bootstrap-select#1440]
I would like to embed an image (glyphicon) for the "Custom button text". When I choose for "multiple" this works perfect, however, I want to select a single option and that will render the HTML as text...

See fiddle: https://jsfiddle.net/jefvhal/n1mv5jcy/

**Comment by perrybush** [comment]
Here's my fix for title/placeholder issue ... did not test with a glyph.

Do a search for ...

```javascript
if ($opt.attr('selected') === undefined && $opt.prop('selected') === false) {
  titleOption.selected = true;
}
```

change to ...

```javascript
if ($opt.attr('selected') === undefined) {
  titleOption.selected = true;
}
```

**Comment by srklonaris** [comment]
+1

**Comment by srklonaris** [comment]
I've tested out this fix, and title will still only render in multiple mode

**Comment by caseyjhol** [comment]
Can you link me to an example? It's working for me: https://plnkr.co/edit/TNBGUVxbimIwQUXXZ4fU?p=preview. Are you sure you're trying the latest version in master? This isn't part of an official release yet.
