### ISSUE TITLE
Translating strings found in plugin

### ISSUE THREAD

**Issue by Wh1rlw1nd** [silviomoreto/bootstrap-select#1443]
Is it possible to translate english strings found in plugin into other languages ? I am referring to these strings:
"Nothing selected", "Select all", "Deselect all" etc...

It would be really useful if there is an option for that, or if there is a way to access and change those strings in the code...

**Comment by caseyjhol** [comment]
Use `selectAllText`, `deselectAllText`, and `noneSelectedText`.
