### ISSUE TITLE
Styling the select box

### ISSUE THREAD

**Issue by phamvuchuong** [silviomoreto/bootstrap-select#1444]
I have tried bootstrap-select, and everything was find but the style is different with other select boxes on the page. The bootstrap-select box had a gradient background like a button. How can we style the bootstrap-select box to look exactly the same as the original select element of bootstrap?

**Comment by caseyjhol** [comment]
bootstrap-select automatically applies classes to make it look like a Bootstrap button dropdown. I would start with this:

```js
$.fn.selectpicker.Constructor.DEFAULTS.styleBase = 'form-control';
$.fn.selectpicker.Constructor.DEFAULTS.style = '';
```

Then from there you can customize with CSS to change the appearance as desired.
