### ISSUE TITLE
input-group-addon on both sides does not work

### ISSUE THREAD

**Issue by vsc55** [silviomoreto/bootstrap-select#1451]
If we "input-group-addon" before and after select select stops working. They go round the edges.

![bootstrap-select_test_page_-_2016-07-25_11 59 15](https://cloud.githubusercontent.com/assets/13438676/17097726/4b8f7e3a-525f-11e6-9e2a-fc9c9f38ceec.png)

Code Example:
`<div class="input-group">`
`<span class="input-group-addon">@</span>`
`<select class="form-control selectpicker">`
`<option>One</option>`
`<option>Two</option>`
`<option>Three</option>`
`</select>`
`<span class="input-group-addon">@</span>`
`</div>`

**Comment by giro83** [comment]
I can confirm the above.

**Comment by caseyjhol** [comment]
This is actually an issue with Bootstrap. There's a mistake in the CSS that incorrectly applies `border-radius: 0;` to the `.input-group-btn` parent, instead of the button itself. Add:

```css
.input-group-btn:not(:first-child):not(:last-child) > .btn {
  border-radius: 0;
}
```

**Comment by vsc55** [comment]
OK, Fixed.
Thank you very much.

**Comment by vsc55** [comment]
Besides adding "border-radius" also add height:

```
.input-group-btn:not(:first-child):not(:last-child) > .btn {
  border-radius: 0;
  height: 100%;
}
```

**Comment by caseyjhol** [comment]
In what scenario is `height: 100%` needed?

**Comment by vsc55** [comment]
Not mandatory, but highly recommended if.
I've had problems since the span of the sides were higher than normal and the select is not occupied the entire area.
Thus no matter the height of the side span is set as 100%.

**Comment by vsc55** [comment]
Not mandatory, but highly recommended if.
I've had problems since the span of the sides were higher than normal and the select is not occupied the entire area.
Thus no matter the height of the side span is set as 100%.

Without height not set to 100% can happen:
![4b8f7e3a-525f-11e6-9e2a-fc9c9f38ceec](https://cloud.githubusercontent.com/assets/13438676/17526336/1d8832ca-5e67-11e6-9047-2a6f91c34cdd.png)

**Comment by giro83** [comment]
If this is a bug in bootstrap, is someone proficient / familiar in reporting bugs to them raising this? Just saying, so we won't have to use a workaround forever.

**Comment by caseyjhol** [comment]
Well, _bug_ might not have been the best word to use. I considered reporting it, but as far as I can tell, Bootstrap doesn't support having button groups next to input-group-addons (at least not officially). `.input-group-btn:not(:first-child):not(:last-child)` having a border-radius of 0 is more a result of consolidating the CSS than anything on purpose, I think. In addition, `width: 100%` would need to be added to the `.btn`, I'm not sure they'd be cool with that. Maybe I'll submit it, but I will be adding this fix into bootstrap-select officially.

**Comment by algopill-nadav** [comment]
any solution ?
