### ISSUE TITLE
onclick on mobile mode

### ISSUE THREAD

**Issue by fullmoonfisher** [silviomoreto/bootstrap-select#1454]
Hi authors,

I use bootstrap-select on mobile, so I set the option data-mobile to true and it works fine when I press it on screen, it shows a popup item select like android does. However, I am trying to get an input field that when I enter key code 13 (which is Enter) and than that emulate press action.

I use jquery to select the <select> dom and use .click() :
$("button[data-id='theType']").click()

The dropdown still able to display, but it is on the normal style like I did not set the data-mobile to false.

Maybe I just missed out something or I should not use .click on the button rendered. please let me know if there are any hints, Thank you for the great plug-in =)

**Comment by caseyjhol** [comment]
You'll want to initiate the click on the select element itself, rather than the button. The button is simply for appearances, and is actually underneath the select when mobile is enabled.
