### ISSUE TITLE
DropDown does not work

### ISSUE THREAD

**Issue by lebel33** [silviomoreto/bootstrap-select#1457]
When I use method post or load from jquery, the select does not show the menu, not even open the dropdown.

**Comment by pichotweb** [comment]
+1, the select is rendered, but the click triggers nothing

**Comment by weisjohn** [comment]
The only way I can get this to work is to blur the window / tab and then come back.

**Comment by lebel33** [comment]
Finally, I made it work, I think that the jquery libraries caused the error because in the html something put me an attribute to disabled the selectpicker, but I need to implement a GET method in javascript. Thank you for your comments.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.
