### ISSUE TITLE
jquery v3 issues

### ISSUE THREAD

**Issue by priley86** [silviomoreto/bootstrap-select#1459]
It appears there is an issue with bootstrap-select and jquery v3. The following is output from [jquery-migrate](https://github.com/jquery/jquery-migrate):
```
jQuery.expr[":"] is now jQuery.expr.pseudos
```

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by mmenzo** [comment]
We're also looking into upgrading to jQuery 3.0.0 and found that the Bootstrap Select libary isn't fully compatible yet (we're getting the same warning from jQuery Migrate as in the first post).

JSFiddle: https://jsfiddle.net/tgzqnLgq/1/
(See console for the warning)

**Comment by priley86** [comment]
@caseyjhol thanks! any idea when this will be released?

**Comment by caseyjhol** [comment]
Hopefully this week.
