### ISSUE TITLE
Event changed.bs.select not firing for native mobile menu

### ISSUE THREAD

**Issue by adrianhuna** [silviomoreto/bootstrap-select#1465]
Event `changed.bs.select` is not firing on mobile when native mobile menu is used. Tested on Android 6 with Chrome and Opera browsers.

http://jsfiddle.net/3fa34oez/4/

(Remove `data-mobile="true"` to see the event working correctly on desktop.)

**Comment by nicomollet** [comment]
I was about to post an issue about this too.

Changing `changed.bs.select` with `change` looks to work on both mobile and desktop. Not sure if it does on all browsers.
