### ISSUE TITLE
Live Search Style does not work with value as "startsWith"

### ISSUE THREAD

**Issue by amitra1997** [silviomoreto/bootstrap-select#1469]
Live search style does not work when using the setting startsWith. Only the value of 'contains' works.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by caseyjhol** [comment]
This appears to work properly in my testing (Chrome 52 on Windows 10). If using a data-attribute, be sure to use `data-live-search-style="startsWith"`. Closing this until you can provide an example.

**Comment by adjj1990** [comment]
[https://jsfiddle.net/KyleMit/9abm0hhy/](url)

totally not working

**Comment by adjj1990** [comment]
https://jsfiddle.net/KyleMit/9abm0hhy/
Check it.. definitely not working

**Comment by caseyjhol** [comment]
That's because you're using version 1.6.3 (released nearly 3 years ago) in that example. Try using 1.12.2 and it works.

**Comment by adjj1990** [comment]
Sorry sir.. still not working
http://jsfiddle.net/9xr5af00/44/

**Comment by adjj1990** [comment]
OK.. I sorted the issue . For anyone who faces the same problem please note that the plugin searches inside the <li> tags. So, if you are using the " data-content " attribute, live search is likely to malfunction. There are 2 ways out  :

1. Keep the text you want the live search to act on in the first position, before any kind of html tags you use inside data-content.

2. Just edit the plugin at line 1450. The variable $searchBase. Currently it only discards <li> tags with is-hidden, .divider & .dropdown-header classes. Make it discard any html tags inside your data content and only search for free texts. What I did was created another variable $filteredSearchBase and refiltered the original $searchbase variable discarding my custom html tags inside the data-content. 👍

**Comment by tomczek** [comment]
I had a similar problem. My search-result for liveSearchStyle "startsWith" was always empty for each search-value. After a while I've figured out, that this was an mapping issue. This is how it worked for me:

```
<abp-select
	picker-options.bind="{ liveSearch: true, dropupAuto: false, noneSelectedText: '', liveSearchStyle: 'startsWith' }"
	collection.bind="items"
	selected-item.bind="selectedItem"
	data-mapping-structure.bind="{ option: 'standardDisplayText', content: 'standardDisplayText' }"
	object-key="key">
</abp-select>

export interface IItem {
    key: string;
    value: string;
    displayText: string;
}

public items: IItem[];
public selectedItem: IItem;

items = [
	{ key: '121', value: 'hello', displayText: '121 - hello' },
	{ key: '112', value: 'world', displayText: '112 - world' },
];

search for: "12"
result: "121 - hello"
```
