### ISSUE TITLE
Overlapping with jquery datepicker

### ISSUE THREAD

**Issue by devingoble** [silviomoreto/bootstrap-select#1473]
I'm having an issue in 1.11.0 where the collapsed select box appears above the jquery date picker. There are no custom z-index's set.

![image](https://cloud.githubusercontent.com/assets/2547980/17755697/4ed9aeba-6490-11e6-9f91-1b3c9c633438.png)

**Comment by caseyjhol** [comment]
bootstrap-select has a z-index of 1 by default, to ensure it stays above the original select. Assigning a z-index to the datepicker should solve your problem.
