### ISSUE TITLE
Cannot read property 'apply' of null

### ISSUE THREAD

**Issue by daN4cat** [silviomoreto/bootstrap-select#1475]
After upgrading from 1.10.0 to 1.11.0 the following code causes an error:

```
  // set data-selected on options that are programmatically selected
  // prior to initialization of bootstrap-select
  var _val = $.fn.val;
  $.fn.val = function(value){
    if (this.is('select') && value) {
      this.find('option[value="' + value + '"]').data('selected', true);
    }
    
    return _val.apply(this, arguments);
  };
```
the exception is thrown on the return line. It looks like _val is null.

What changed from 1.10.0 to 1.11.0 that could cause this error?

**Comment by daN4cat** [comment]
That piece of code went in here: https://github.com/silviomoreto/bootstrap-select/commit/5da66949c2e7607a078a3aa3dd5c024c60ed4b50

**Comment by caseyjhol** [comment]
Can you provide an example? I can't recreate this.

**Comment by daN4cat** [comment]
We had that problem in this open source: https://github.com/jekkos/opensourcepos/commit/9a6bd6e000cf731767344a19d25154f5dfc0ff18 and I reverted the version to 1.10 to avoid that issue.
As soon as I updated your plugin to 1.11 I got issue reports: https://github.com/jekkos/opensourcepos/issues/813 and https://github.com/jekkos/opensourcepos/issues/812

Unfortunately I don't have the time to create a specific example, but that source is quite mature and ready to be delivered and worked well for many months of development with version 1.10.

**Comment by kenbwhite** [comment]
@caseyjhol I was having the same problem and we rolled back to v1.10.0 and everything worked fine.  Here is a link to a codeply that causes the problem.

http://codeply.com/go/y8gEFpNvbz

To see the problem please do the following:

1. Click on Magnifying class
2. Type in J in the text box that just displayed (In the console, you will see the error)

If you roll back to an older version of bootstrap-select you will the autocomplete run correctly.

I hope this helps, if not let me know and I'll try and update with some more.

Ken

**Comment by caseyjhol** [comment]
Great - thanks, Ken. Will look into this.

**Comment by daN4cat** [comment]
Yes, we get the same issue with an autocomplete box.
