### ISSUE TITLE
How can I sort DropDown by the text?

### ISSUE THREAD

**Issue by CKKwan** [silviomoreto/bootstrap-select#1476]
Or turn off sorting. DO NOT sort at all.

Currently it will automatically sort by the Value, which is causing a lot of troubles.

Thanks in advance.

**Comment by caseyjhol** [comment]
I'm not sure what you want. Can you elaborate on your question?

**Comment by PieChuckerr** [comment]
He wants sort based on text, not on the basis of key. for example <option value="key">text</option>

**Comment by CKKwan** [comment]
Yes, what ever mentioned by PieChuckerr is correct.

It is more useful to sort by the text, or do not sort at all. Sort by something which cannot be seen is really weird, and I cannot turn it off.

**Comment by PieChuckerr** [comment]
@caseyjhol   added question for more details [http://stackoverflow.com/questions/39085783/bootstrap-select-picker-automatically-sorting-based-on-key](url)  Issue is with  **li element data-original-index**

**Comment by caseyjhol** [comment]
As described in the StackOverflow answer, bootstrap-select doesn't do any sorting at all. There is no sorting to turn off.
