### ISSUE TITLE
No item could be found when liveSearchNormalize="true" AND liveSearchStyle="startsWith"

### ISSUE THREAD

**Issue by crevete** [silviomoreto/bootstrap-select#1477]
When combining liveSearchNormalize="true" AND liveSearchStyle="startsWith", whatever the searched text, no item can be found. But when using them individually, it works fine.

FYI, I have some accented characters in my options

**Comment by crevete** [comment]
@caseyjhol could you please take a look at this? Thanks

**Comment by caseyjhol** [comment]
For future reference, I would've looked into this as soon as you posted it if you would've followed the [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Time not spent recreating can be spent fixing.

**Comment by crevete** [comment]
@caseyjhol I think the liveSearchNormalize is buggy, please check this:

http://jsfiddle.net/9xr5af00/11/
