### ISSUE TITLE
select picker automatically sorting based on key

### ISSUE THREAD

**Issue by PieChuckerr** [silviomoreto/bootstrap-select#1479]
I have the data in the DB table like this,

*cId*       *CountryName*
1              Australia
2              Belgium
3              Canada
4              India
5              Zimbabwe
6              Brazil

What I am doing is ordering the data based on countryName and populating cId as option element's key and countryName as option element's value

`function loadJSONtoSelectBox(selector, options)
{
   $(selector).selectpicker();
   $.each(options, function(key, value) {
       $('<option data-tokens="'+value+'" value="' + key + '">' + value + '</option>').appendTo(selector);
       $(selector).focus();
  });

  $(selector).selectpicker('refresh');
}
`
But internally it is sorting based on option's key i.e it is showing Brazil at the end instead of after Belgium, what is the hack to solve this issue?

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by amit-tgr** [comment]
Any solution for this bug ? Please suggest.

**Comment by caseyjhol** [comment]
See #1476. Bootstrap-select doesn't do any sorting. You need to sort the options yourself.

**Comment by vladimirjohn** [comment]
Sort it via Country name in SQL much better.
