### ISSUE TITLE
focus on selectpicker when I hit enter in a form

### ISSUE THREAD

**Issue by FIA2008** [silviomoreto/bootstrap-select#148]
I have a form with input fields and select boxes (which are using the selectpicker plugin). When I want to enter something in a text input field and hit the enter key, a selectpicker select box comes to focus somehow.
How can I fix this?

**Comment by yogiben** [comment]
+1

**Comment by BenevidesLecontes** [comment]
+1

**Comment by caseyjhol** [comment]
Instead of saying "+1", can you provide me with an example?
