### ISSUE TITLE
Change events fire twice on IE8

### ISSUE THREAD

**Issue by Supersausagedog** [silviomoreto/bootstrap-select#1484]
Whenever I use bootstrap selects on IE8 the select event is fired twice, causing the listener to run twice. This caused considerable slowdown.

I wrote a quick fix to the problem, but since I know nothing about the codebase I'm not sure if its a paticularly robust solution.

Original code:
```
        if (el.fireEvent) {  
            event = document.createEventObject();  
            event.eventType = eventName;  
            el.fireEvent('on' + eventName, event);  
        }  
        this.trigger(eventName);  
```
IE 8 compatible code:
```
        if (el.fireEvent) {
            event = document.createEventObject();
            event.eventType = eventName;
            el.fireEvent('on' + eventName, event);
        } else {
            this.trigger(eventName);
        }
```

**Comment by caseyjhol** [comment]
Good catch - thanks. Will get this added.
