### ISSUE TITLE
Title color is not set to grey when no options are selected

### ISSUE THREAD

**Issue by alexcasella** [silviomoreto/bootstrap-select#1488]
I have a dropdown box like this 

    <select id="box" title="Select" class="selectpicker form-control">
	  <option value="">Option 1</option>
	  <option value="user">Option 2/option>
	</select>

My issue is that the title is not greyed out when no option is chosen, like this example shows. What am I doing wrong?

<img width="859" alt="screen shot 2016-08-26 at 9 53 39 am" src="https://cloud.githubusercontent.com/assets/10790628/18007685/179f50e6-6b73-11e6-8972-ad78b074dc74.png">

What mine looks like:

<img width="962" alt="screen shot 2016-08-26 at 9 55 24 am" src="https://cloud.githubusercontent.com/assets/10790628/18007730/3e32a00a-6b73-11e6-8afb-312ef2b76b08.png">

**Comment by alexcasella** [comment]
This has been resolved, thanks to an answer from SO I needed to hard code like this in my stylesheet

    .bootstrap-select > .dropdown-toggle[title='Select'],
	.bootstrap-select > .dropdown-toggle[title='Select']:hover,
	.bootstrap-select > .dropdown-toggle[title='Select']:focus,
	.bootstrap-select > .dropdown-toggle[title='Select']:active { color: grey; }

**Comment by caseyjhol** [comment]
You are most likely not using the most recent version of bootstrap-select, which includes placeholder styling.

**Comment by alexcasella** [comment]
@caseyjhol I am using v1.10.0. Which version supports custom styling?

**Comment by caseyjhol** [comment]
@alexcasella Placeholder styling was added in v1.11.0.
