### ISSUE TITLE
Event hide.bs.select not fired when Esc pressed with live search configuration

### ISSUE THREAD

**Issue by meesha81** [silviomoreto/bootstrap-select#1489]
Hi,

event hide.bs.select not fired when Esc pressed with live search configuration.

This differs to select WITHOUT live search which fires the event as expected.

Best regards,
Michal

**Comment by meesha81** [comment]
Hi,
thank you for fast bug fix. 

I have tested your solution and here is the feedback:

Event is now fired, but there is still difference between live search configuration and without it.

Without live search:
- key 27 (Esc) IS NOT propagated

With live search:
- key 27 Esc  IS still propagated


We have fixed this issue in the js file and here is the patch:

bootstrap-select.js
@@ -1637,6 +1637,7 @@
if (that.options.liveSearch) {
if (/(^9$|27)/.test(e.keyCode.toString(10)) && isActive && that.$menu.find('.active').length === 0) {
e.preventDefault();
+          e.stopPropagation();
that.$button.click().focus();
}

It should work properly.

Best regards,
Michal Vrabel

**Comment by anatoly-mytrucking** [comment]
The change in ead67e5 breaks behaviour of selectOnTab = true.
It makes .active the original option so later wrong option is picked at [line 1750](https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L1750)

**Comment by meesha81** [comment]
Hi, currently tab select option and close livesearch. But original behavior is:
select option, close live search and DO TAB to next form item.
