### ISSUE TITLE
Outline: none; not working

### ISSUE THREAD

**Issue by zolero** [silviomoreto/bootstrap-select#1490]
I'm not sure where to ask this question, but it's driving me crazy.
I'm trying to remove the outline when the div/button is focused.

[http://puu.sh/qSMIW/ad48b733ed.png](http://puu.sh/qSMIW/ad48b733ed.png)

Could someone please tell me what I'm missing?

```
.bootstrap-select .btn
{
    border-radius: 4px;
    border: 1px solid #f0f0f0;
    background: #fff;
    -webkit-box-shadow: none;
    text-transform: none;
    box-shadow: none !important;
    outline: none !important;
    -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

.btn-default.active.focus, .btn-default.active:focus, .btn-default.active:hover, .btn-default:active.focus, .btn-default:active:focus, .btn-default:active:hover, .open>.dropdown-toggle.btn-default.focus, .open>.dropdown-toggle.btn-default:focus, .open>.dropdown-toggle.btn-default:hover {
    border-color: #f15a29;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
    background: #fff;
    outline: none !important;
}
.bootstrap-select,.bootstrap-select:focus,.btn-group ,.bootstrap-select .btn:focus,.bootstrap-select .dropdown-toggle:focus  {
    box-shadow: none !important;
    outline: none !important;
    outline: 0 !important;
}
.btn, .btn:focus, .btn:active:focus, .btn.active:focus, .btn.focus, .btn:focus, .btn.focus:active, .btn.active.focus {
    outline: none !important;
    outline: 0 !important;
}

input::-moz-focus-inner {
    outline: none !important;
    outline: 0 !important;
}
.btn-group .dropdown-toggle:active, .btn-group.open .dropdown-toggle
{
    outline: none !important;
    outline: 0 !important;
}

```

**Comment by zolero** [comment]
Fixed it, it was being overruled by bootstrap-select.css 
`.bootstrap-select .dropdown-toggle:focus {
  outline: none !important;
}`

**Comment by suppi00** [comment]
> I'm not sure where to ask this question, but it's driving me crazy.
> I'm trying to remove the outline when the div/button is focused.
> 
> http://puu.sh/qSMIW/ad48b733ed.png
> 
> Could someone please tell me what I'm missing?
> 
> ```
> .bootstrap-select .btn
> {
>     border-radius: 4px;
>     border: 1px solid #f0f0f0;
>     background: #fff;
>     -webkit-box-shadow: none;
>     text-transform: none;
>     box-shadow: none !important;
>     outline: none !important;
>     -webkit-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
>     transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
> }
> 
> .btn-default.active.focus, .btn-default.active:focus, .btn-default.active:hover, .btn-default:active.focus, .btn-default:active:focus, .btn-default:active:hover, .open>.dropdown-toggle.btn-default.focus, .open>.dropdown-toggle.btn-default:focus, .open>.dropdown-toggle.btn-default:hover {
>     border-color: #f15a29;
>     -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
>     box-shadow: inset 0 1px 1px rgba(0,0,0,.075),0 0 8px rgba(102,175,233,.6);
>     background: #fff;
>     outline: none !important;
> }
> .bootstrap-select,.bootstrap-select:focus,.btn-group ,.bootstrap-select .btn:focus,.bootstrap-select .dropdown-toggle:focus  {
>     box-shadow: none !important;
>     outline: none !important;
>     outline: 0 !important;
> }
> .btn, .btn:focus, .btn:active:focus, .btn.active:focus, .btn.focus, .btn:focus, .btn.focus:active, .btn.active.focus {
>     outline: none !important;
>     outline: 0 !important;
> }
> 
> input::-moz-focus-inner {
>     outline: none !important;
>     outline: 0 !important;
> }
> .btn-group .dropdown-toggle:active, .btn-group.open .dropdown-toggle
> {
>     outline: none !important;
>     outline: 0 !important;
> }
> ```
USE THIS :----------------
textarea:focus, 
textarea.form-control:focus, 
input.form-control:focus, 
input[type=text]:focus, 
input[type=password]:focus, 
input[type=email]:focus, 
input[type=number]:focus, 
[type=text].form-control:focus, 
[type=password].form-control:focus, 
[type=email].form-control:focus, 
[type=tel].form-control:focus, :focus {
  box-shadow: inset 0 -1px 0 #ddd;
 
}
