### ISSUE TITLE
Can't work with bootstrap.js 

### ISSUE THREAD

**Issue by linzy410** [silviomoreto/bootstrap-select#1496]
When I import bootstrap.min.js 3.3.5, bootstrap-select is invalid, without error messages 
click on the select without any response

**Comment by caseyjhol** [comment]
Are you loading Bootstrap JS before bootstrap-select? See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.
