### ISSUE TITLE
Jquery UI autocomplete and Bootstrap select Bug

### ISSUE THREAD

**Issue by jensJJ** [silviomoreto/bootstrap-select#1500]
Hello,

when using jquery ui and bootstrap-select together, I get following error on my page:

```
Uncaught TypeError: Cannot read property 'apply' of null$.fn.val @ bootstrap-select.self-16a81c2….js?body=1:137_value @ autocomplete.self-3befc48….js?body=1:577(anonymous function) @ widget.self-c160224….js?body=1:116(anonymous function) @ autocomplete.self-3befc48….js?body=1:407handlerProxy @ widget.self-c160224….js?body=1:461
bootstrap-select.self-16a81c2….js?body=1:137 Uncaught TypeError: Cannot read property 'apply' of null$.fn.val @ bootstrap-select.self-16a81c2….js?body=1:137_value @ autocomplete.self-3befc48….js?body=1:577(anonymous function) @ widget.self-c160224….js?body=1:116_change @ autocomplete.self-3befc48….js?body=1:487(anonymous function) @ widget.self-c160224….js?body=1:116blur @ autocomplete.self-3befc48….js?body=1:205handlerProxy @ widget.self-c160224….js?body=1:427dispatch @ jquery.self-bd7ddd3….js?body=1:5227elemData.handle @ jquery.self-bd7ddd3….js?body=1:4879
```

  ```
// set data-selected on options that are programmatically selected
  // prior to initialization of bootstrap-select
  var _val = $.fn.val;
  $.fn.val = function(value){
    if (this.is('select') && value) {
      this.find('option[value="' + value + '"]').data('selected', true);
    }
    
    return _val.apply(this, arguments);
  };

```

Does anyone know the reason?

**Comment by caseyjhol** [comment]
This has been fixed in the latest master. In the future, see [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.
