### ISSUE TITLE
_val gets set to null while executing the code to re-define $.fn.val

### ISSUE THREAD

**Issue by caseykim** [silviomoreto/bootstrap-select#1501]
I'm using Chrome Version 52.0.2743.116 (64-bit), Rails 4.2.7.1, jQuery 1.12.0, and jquery-ui-rails 5.0.5.

I hit a bug on line 161 bootstrap-select.js with autocomplete input.
```
<input autofocus="autofocus" data-autocomplete-source="/customizeproducts/autocomplete" class="form-control ui-autocomplete-input" type="text" name="customizeproduct[product_name]" id="customizeproduct_product_name" autocomplete="off">
```
```
Uncaught TypeError: Cannot read property 'apply' of null
```

while the code was executing,
`_val` got reset to `null` before hitting line 161  because of race condition.

The fix that solved the issue for us was
```
  // set data-selected on options that are programmatically selected
  // prior to initialization of bootstrap-select
  var _val = $.fn.val;
  $.fn.val = function(value){
    if (this.is('select') && value) {
      this.find('option[value="' + value + '"]').data('selected', true);
    }

    if (_val) {
      return _val.apply(this, arguments);
    }
    else {
      return $.fn.val.apply(this, arguments);
    }
  };
```

**Comment by caseyjhol** [comment]
This has already been resolved in the latest master. And posted about twice.

See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md).

>## Bug reports
>
>A bug is a _demonstrable problem_ that is caused by the code in the repository.
>Good bug reports are extremely helpful - thank you!
>
>Guidelines for bug reports:
>
>1. **Use the GitHub issue search.** Check if the issue has already been reported.
>
>2. **Check if the issue has been fixed.** Try to reproduce it using the latest `master` or development branch in the repository.
>
>3. **Provide environment details.** Provide your operating system, browser(s), jQuery version, Bootstrap version, and bootstrap-select version.
>
>4. **Create an isolated and reproducible test case.** Create a [reduced test case](http://css-tricks.com/6263-reduced-test-cases/).
>
>5. **Include a live example.** Make use of jsFiddle or jsBin to share your isolated test cases.

**Comment by caseykim** [comment]
@caseyjhol do you guys have plans to release a new version or can I copy the file from the master branch into `vendor`?

I used `gem 'rails-assets-bootstrap-select'`
and I have the latest version 1.11.0 from bower.

**Comment by caseyjhol** [comment]
v1.11.1 will be released this week.
