### ISSUE TITLE
dash

### ISSUE THREAD

**Issue by xiquinho** [silviomoreto/bootstrap-select#1508]
using a dash such as 'data-width' is problematic in some situations, can you pl change it to 'datawidth' ?

See detailed explanation here:

http://stackoverflow.com/questions/2389041/dash-in-anonymous-class-member

**Comment by caseyjhol** [comment]
See https://api.jquery.com/data/#data-html5. This seems like a fringe case, so I don't think it makes sense to change this (not 100% sure how I'd even do that). If you need custom settings, do so with JS.
