### ISSUE TITLE
CSP error with bootstrap-select

### ISSUE THREAD

**Issue by mbielecki** [silviomoreto/bootstrap-select#1509]
Hello, I have a problem with bootstrap-select 1.11.0. After enable Content Security Policy (CSP), js displays error related with InnerHTML. 

The CSP have set all rules .

Error:
> bootstrap-select.js:512 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
createView: function ()
{ var $drop = this.createDropdown(), li = this.createLi(); $drop.find('ul')[0].innerHTML = li; return $drop; }

> 

Thanks for your help.

**Comment by caseyjhol** [comment]
Good catch. You might try using 'unsafe-inline' in the meantime.

Note to self: see https://github.com/ceolter/ag-grid/issues/1093

**Comment by caseyjhol** [comment]
I think this can be closed for now. The main problem was the inline style attribute was being added for *every* option, even if the option itself didn't have a style attribute. This will be available in the next release.
