### ISSUE TITLE
Change dog,cat,bird,bat...  to All when you choose select all ?

### ISSUE THREAD

**Issue by zeing** [silviomoreto/bootstrap-select#1518]
Can i change word from  dog,cat,bird,bat...  to All when you choose all  or click select all  

Ex   .
- [o]  dog
- [o]  cat 
- [o] bat 
default it show in block  "dog,cat,bat"  i want to show "All"
and when you unselect dog
- []  dog
- [o]  cat 
- [o] bat 
it back to show "cat,bat"

thank you

**Comment by caseyjhol** [comment]
See #1188.
