### ISSUE TITLE
Plugin does not follow jquery .prop('disabled', true)

### ISSUE THREAD

**Issue by divinoro** [silviomoreto/bootstrap-select#1521]
If I apply bootstrap-select to some select element, then I change property of the select to disabled, change does not apply to it's boostrap-select replacement.

I mean on-the-fly change by jQurey .prop('disabled', true)

Do I have manually disable also bootstrap-select replacement or will you add some kind of event listener to the plugin ?

Thank you.
Ivan

**Comment by caseyjhol** [comment]
For now, you'll have to call `.selectpicker('refresh')` manually after making changes to the select. http://silviomoreto.github.io/bootstrap-select/methods/#selectpickerrefresh
