### ISSUE TITLE
Dropup expands below navbar

### ISSUE THREAD

**Issue by imbrish** [silviomoreto/bootstrap-select#1525]
First, thanks for this great plugin! I really appreciate the work you guys put in it, and I guess you want to make it even better and so gonna be interested in this issue I had. 

Namely when select with enough options opens as dropup it tends to go beneath the fixed bootstrap navbar. As you can see in this plunker https://plnkr.co/edit/zSgS2m1KikVqbYP9QksQ?p=preview .

I managed to fix this behavior by simple hack, I changed this line:
```
selectOffsetTop = pos.top - containerPos.top - $window.scrollTop()
```
to
```
selectOffsetTop = pos.top - containerPos.top - $window.scrollTop() - $('nav.navbar').height();
```
which somehow makes selects behave nicely and stop right before navbar.

I'm not sure how this could be implemented, but have a few ideas:
- automatically checking margins set on body and adjusting available height accordingly
- adding an option where top/bottom offset from the edge can be specified, or maybe even a callback for more flexibility

**Comment by caseyjhol** [comment]
You can fix this a couple different ways:

- Set the z-index on the dropdown menu to be higher than the navbar.
```css
.dropdown-menu {
  z-index: 1040;
}
```
- Use a brand new feature (not yet documented or in an official release) - `windowPadding`. This will be in the next release. Use a number or an array of numbers `[top. right, bottom, left]` to set the padding around the window. You can also set a data attribute. See #1503 for more info.
```js
{
...
windowPadding: [50, 0, 0, 0]
...
}
```
```html
<select data-window-padding="[50, 0, 0, 0]">
</select>
```
