### ISSUE TITLE
selectpicker doesn't work in a HTML Tcript Tag of type="text/ng-template".

### ISSUE THREAD

**Issue by FaKiieZ** [silviomoreto/bootstrap-select#1526]
When i use the selectpicker Class in a HTML Script Tag of type="text/ng-template", the whole select doesn't appear. When i use it outside of the Script Tag, it works perfectly.

**Comment by caseyjhol** [comment]
You need to call `.selectpicker('refresh')` after the template has been loaded, since it is added dynamically via AngularJS. I recommend using a plugin such as https://github.com/caseyjhol/ng-bootstrap-select.
