### ISSUE TITLE
selectAllText & deselectAllText missing from most i18n files

### ISSUE THREAD

**Issue by vlsg** [silviomoreto/bootstrap-select#1529]
I am successfully including i18n files when the user's language is not set to English, however there are some text options which are not specified in about half of these files, primarily the selectAllText, deselectAllText and doneButtonText.  For example, both the spanish and italian js files do not specify the translations for these texts.  Unfortunately I do not speak those languages so I do not know the translations in order to contribute.  Could these files be updated to include translations for all text properties?  Our end users would be very grateful!  

Thank you.

**Comment by caseyjhol** [comment]
Looks like the following files don't have the translation:

* defaults-cs_CZ.js
* defaults-es_CL.js
* defaults-eu.js
* defaults-it_IT.js
* defaults-nl_NL.js
* defaults-pl_PL.js
* defaults-pt_BR.js
* defaults-pt_PT.js
* defaults-ro_RO.js
* defaults-ru_RU.js
* defaults-ua_UA.js
* defaults-zh_CN.js

**Comment by vsc55** [comment]
The "defaults-es_CL.js" file can also be used to es_ES "defaults-es_ES.js" as the translation is the same.

**Comment by vsc55** [comment]
Attachment translation with the new translated var.
Language: "es_ES

"
