### ISSUE TITLE
HOW TO: bind option value to component

### ISSUE THREAD

**Issue by LucaMarzialetti** [silviomoreto/bootstrap-select#1532]
Dear support,
I'm using this component, and it looks absolute crazy.
There's actually only one thing I haven't understand by your examples guide, how to bind some "hidden data" like in the field _value_ of _option_ tag?

My example is very simple:

```
<select class="selectpicker" title="title" data-live-search="true" data-size="7">
    <option value="value_to_be_binded" >some text to display</option>
    ...more other values
</select>
```
My interess is on the **field _value_ of the _option_**, not really on the text content shown in the selectpicker.
I would like to **catch the event on select (mouse click) and get the _option value_ field**.

I've just noticed that your component JS and CSS get the info inside the _select/option_ elements and translate them into _li_ elements...and those **values fields disappear**.

I've searched with the issue tracker, but, sound strange, no one seemes have already asked this question o,o.

Thanks for your work and support,
hope that this isn't a repost :)
best regards
Luca

**Comment by harlentan** [comment]
I am afraid it does not support this feature. I have the same feature like you.
And I just resolved it by use the index in the event callback, then compare with the index of the selectpicker element.

**Comment by harlentan** [comment]
Hello I have found a pretty easy way to get your own attributes:
```javascript
$(e.target.selectedOptions[0]).attr('data-xxx')
```

**Comment by LucaMarzialetti** [comment]
@harlentan 
thanks for your answer! :)
recently i solved like this! 

In case of a bootstrap dropdown made of `<ul>` and `<li>`
```
//click event for generic dropdown
$('li.your_dropdown_element_class').click(function(event){
    var val = $(this).attr('value');
});
```

In case of bootstrap-select
```
//click event for select items
$('select.your_dropdown_element_class').change(function(){
    var val = $(this).find('option:selected').val();
});
```
