### ISSUE TITLE
Double click required to select option on iOS when using FastClick

### ISSUE THREAD

**Issue by birjolaxew** [silviomoreto/bootstrap-select#1533]
When using FastClick, iOS browsers require a double tap to select an option from a bootstrap-select. Seems related to [this issue](https://github.com/ftlabs/fastclick/issues/48), which was fixed when [bootstrap removed their `touchstart.dropdown.data-api` listeners](https://github.com/twbs/bootstrap/commit/566380b257e5322a014fe52f935381ff86637f43). bootstrap-select [still has one of those](https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L1415).

To verify that the problem is with the `$button`, we can add the `needsclick` class to it, so it gets ignored by FastClick ([JSFiddle](https://jsfiddle.net/sbhbwwo8/)). This is a rather ugly solution though, so it should be much preferred to simply remove the `touchstart` listener from the library, as was done with bootstrap.

**Comment by virik** [comment]
I added your fix while waiting for an update.

Are you also having problem with the native drop down sometimes showing for a couple of seconds before bootstrap-select shows?
