### ISSUE TITLE
use 'bower install --save bootstrap-select' can't find gruntfile.js

### ISSUE THREAD

**Issue by yy7054wyq5** [silviomoreto/bootstrap-select#1537]
first:bower install success!
second: i can't find gruntfile.js in 'bootstrap-select'
third: tell me how to change the code by myself.
i want use gruntfile.js to custom the css~
i need u help.

**Comment by caseyjhol** [comment]
I recommend asking on StackOverflow, as this doesn't sound like a bootstrap-select specific issue.

**Comment by yy7054wyq5** [comment]
oh well.thank you

**Comment by yy7054wyq5** [comment]
This is bower's problem.So i use npm install it.
