### ISSUE TITLE
404 on optional translation js files

### ISSUE THREAD

**Issue by LucaMarzialetti** [silviomoreto/bootstrap-select#1543]
Hello there :),
actually i have a 404 error on this include
`<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.2/js/i18n/defaults-*.min.js"></script>`

is it normal?

**Comment by caseyjhol** [comment]
You're supposed to replace the asterisk (*) with the specific language translation file. e.g. defaults-fr_FR.min.js

**Comment by LucaMarzialetti** [comment]
Oh I see, 
Haven't read about it. 
Later I'll try then ☺️
Thanks
