### ISSUE TITLE
DOM reflow separates select box and dropdown

### ISSUE THREAD

**Issue by stodge** [silviomoreto/bootstrap-select#1552]
We are prototyping adding Bootstrap-select into our custom data grid. It works beautifully except for one issue. We use the "container" option set to "body" to avoid clipping when the grid is displayed in a (custom) gadget.

The user opens the dropdown and deselects an option. This modifies the data grid's filter, which reduces the number of displayed rows in the grid. The grid's height is therefore reduced, which causes the select box (part you click to open/close) to be re-positioned on the page. The dropdown is still open, but it isn't moved. So the select box and the dropdown are now in completely different parts of the page and are no longer aligned.

We will try to re-render the dropdown to fix this, but any suggestions would be appreciated.

Thanks

**Comment by caseyjhol** [comment]
The menu needs to be told when to update its position. The plugin automatically detects when the body is scrolled/resized. So, I recommend something like:

```js
$('#grid').on('scroll', function() {
    $(window).scroll();
});
```

**Comment by stodge** [comment]
Thanks! I'll try that.

**Comment by holtkamp** [comment]
@stodge did the suggested approach work?

**Comment by stodge** [comment]
I think it did - or something like this. Thanks!
