### ISSUE TITLE
If you try to clear the Livesearch when empty, it throws error in console

### ISSUE THREAD

**Issue by kpagnat** [silviomoreto/bootstrap-select#1553]
Hi everyone,

I have created a Fiddle that can reproduce the problem.
https://jsfiddle.net/dpzopfmw/

When input is already clear and you push back again, it throws an error :+1: 
> bootstrap-select.js:246 Uncaught TypeError: Cannot read property 'replace' of undefined(…)

It seems the function normalizeToBase is not taking into consideration that "text" can be undefined.

Thanks

**Comment by markdon** [comment]
Also occurs and repeats when pressing many (any?) non-printable keys.
