### ISSUE TITLE
liveSearchStyle with liveSearchNormalize  ?

### ISSUE THREAD

**Issue by kpagnat** [silviomoreto/bootstrap-select#1554]
Hi,

I'm trying to use the liveSearchStyle option with the liveSearchNormalize option together but it doesn't seems to work.
I have created a fiddle here : https://jsfiddle.net/ptxaah1u/
Anything I type returns no results.

Can you help ?

Thanks

**Comment by caseyjhol** [comment]
Duplicate of #1477. Fixed in master.
