### ISSUE TITLE
Bootstrap v4 Issues

### ISSUE THREAD

**Issue by ricky2k7** [silviomoreto/bootstrap-select#1559]
Working on a Bootstrap v4 application and realised that bootstrap-select isn't working as expected:

![select-bootstrap-v4](https://cloud.githubusercontent.com/assets/9956401/20462363/cbf7d886-af13-11e6-9645-b71b3a79ec32.png)

![select-bootstrap-v4-2](https://cloud.githubusercontent.com/assets/9956401/20462364/d533f6aa-af13-11e6-86c0-cbbb41f0eda0.png)

Any solution for this issue?

**Comment by LaVieh** [comment]
Experiencing the same issue +1

**Comment by caseyjhol** [comment]
Please use the search feature. https://github.com/silviomoreto/bootstrap-select/issues/1135#issuecomment-258538094
