### ISSUE TITLE
How to add new options with jquery?

### ISSUE THREAD

**Issue by Rafsonic** [silviomoreto/bootstrap-select#1560]
Hello guys..

- I am trying to add new <option> in my select using jquery but not working.
- I have tried with a normal/default <select> and my code is working fine!
- But when i try <select cass="form-control selectpicker> its not working..

![01](https://cloud.githubusercontent.com/assets/15655808/20510471/342c711c-b079-11e6-9e05-17cf923a43b6.PNG)
![02](https://cloud.githubusercontent.com/assets/15655808/20510472/342e7502-b079-11e6-868a-a5fe2dd608f1.PNG)

**Comment by Rafsonic** [comment]
![01](https://cloud.githubusercontent.com/assets/15655808/20510486/44082c7a-b079-11e6-9563-e759bd3afb2f.PNG)
![02](https://cloud.githubusercontent.com/assets/15655808/20510487/44280860-b079-11e6-9fcb-945bf7189372.PNG)

**Comment by ubfacility** [comment]
i am having the same issue

**Comment by ubfacility** [comment]
$(document).on('change', '.selectpicker', function () {
    $('.selectpicker').selectpicker('refresh');
});
doing the above or 
    $('.selectpicker').selectpicker('refresh');
will help update the list just discovered that.

**Comment by caseyjhol** [comment]
Please read the documentation.

**Comment by Rafsonic** [comment]
Good! Thanks a lot @ubfacility !!!
