### ISSUE TITLE
Stop focus from searchbox when open select box.

### ISSUE THREAD

**Issue by dipeshcct** [silviomoreto/bootstrap-select#1561]
Make disable focus in search box when I open select picker using live-search true?

Because of focus when I open in mobile it open keyboard also.

**Comment by caseyjhol** [comment]
Duplicate of #1511.

**Comment by dipeshcct** [comment]
I reviewed https://github.com/silviomoreto/bootstrap-select/issues/1511 this

But I could not found any solution there. Could you please help me on it?

**Comment by dipeshcct** [comment]
@caseyjhol l can you please tell me where is solution for this?

**Comment by amitsquare** [comment]
Hi Guys ,
After looking at the source code .
These lines gives focus to searchBox in the case of Live Search..
[Source Lines for Focus .](https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L1408-L1410)

Either you can comment it out for permanent effect .you can pass additional option to recognize & then disable it .
Hope this will help you out .

Let me know
