### ISSUE TITLE
Live Search using Key Words not working

### ISSUE THREAD

**Issue by fredmaccaferri** [silviomoreto/bootstrap-select#1563]
Live Search using Key Words it's not working

I've make a test with mac osx 10.11.6 with my macbook pro.
tested with safari 10.00.1 and chrome 54.0.2840.98 (64-bit).

TEST ON ONLINE EXAMPLE
1) Go to https://silviomoreto.github.io/bootstrap-select/examples/#key-words
2) Test the key words ketchup (as wrote in test)
3) Nothings seems to work

<img width="876" alt="screenshot 2016-11-25 17 16 15" src="https://cloud.githubusercontent.com/assets/23741371/20630722/f910dc28-b332-11e6-89f9-20d891b27d90.png">

TEST ON LOCAL EXAMPLE
1) download the example code
2) search an example with data-live-search="true"
3) insert some key words (es. data-tokens="ketchup mustard")
4) Nothings seems to work

**Comment by caseyjhol** [comment]
Looks like this was broken in #1516.

**Comment by JohnnyDeeee** [comment]
Has this been pushed through, because i still cant get it to work on the [Online Examples](https://silviomoreto.github.io/bootstrap-select/examples/#key-words) page and also not on [JSfiddle](http://jsfiddle.net/jc4gfjtb/) using the latest version (1.12.1) ...

**Comment by caseyjhol** [comment]
v1.12.2 has officially been released.

**Comment by tomczek** [comment]
I had a similar problem. My search-result for liveSearchStyle "startsWith" was always empty for each search-value. After a while I've figured out, that this was an mapping issue. This is how it worked for me:

```
<abp-select
	picker-options.bind="{ liveSearch: true, dropupAuto: false, noneSelectedText: '', liveSearchStyle: 'startsWith' }"
	collection.bind="items"
	selected-item.bind="selectedItem"
	data-mapping-structure.bind="{ option: 'standardDisplayText', content: 'standardDisplayText' }"
	object-key="key">
</abp-select>

export interface IItem {
    key: string;
    value: string;
    displayText: string;
}

public items: IItem[];
public selectedItem: IItem;

items = [
	{ key: '121', value: 'hello', displayText: '121 - hello' },
	{ key: '112', value: 'world', displayText: '112 - world' },
];

search for: "12"
result: "121 - hello"
```
