### ISSUE TITLE
Option for "All Items selected" in selectedTextFormat

### ISSUE THREAD

**Issue by raulbolsantos** [silviomoreto/bootstrap-select#1566]
Hi there!

I've think the option of show 3 kinds of situations in the same select will be interesting.
Example:
Considering: (multiple == true), (count == 2) and (4 options loaded)

select class="selectpicker" multiple>
  option>Asia/option>
  option>America/option>
  option>Europe/option>
  option>Oceania/option>

1. When 2 or less items has been selected, show all items like "Asia, America"
2. When 3 items has been selected, show like it already does, "3 of 4 continents"
3. When all 4 items has been selected, show like ''All World!" instead of "4 of 4 continents"

Thanks for the nice tool.

**Comment by caseyjhol** [comment]
See #1188.

```js
    countSelectedText: function (numSelected, numTotal) {
      if (numSelected == 1) {
        return "{0} item selected";
      } else if (numSelected === numTotal) {
        return "All items selected";
      } else {
        return "{0} items selected";
      }
    }
```
