### ISSUE TITLE
form-group-sm not applied

### ISSUE THREAD

**Issue by PhilPJL** [silviomoreto/bootstrap-select#1570]
The control doesn't change size to respect form-group-sm (and I guess form-group-lg)

See https://jsbin.com/muvuguy/441/edit?html,js,output

![snip](https://cloud.githubusercontent.com/assets/271656/20687222/86e361f6-b5b3-11e6-8748-2e6dea623902.PNG)

**Comment by PhilPJL** [comment]
@caseyjhol When do think this fix will be released?

**Comment by caseyjhol** [comment]
v1.12.2 has officially been released.
