### ISSUE TITLE
Live server it's not working properly.

### ISSUE THREAD

**Issue by raselcse10** [silviomoreto/bootstrap-select#1576]
Looking for help. After integrate this library in my project it's working on local server but in my **live server this library is not working.** Live server this library also loaded properly but not showing drop down.

**Comment by raselcse10** [comment]
Is it your script problem? I can't see any error in my console. So let me know.

**Comment by caseyjhol** [comment]
If it's working locally and not live, it sounds like a problem with your configuration. Are you loading jQuery and Bootstrap before bootstrap-select?

**Comment by raselcse10** [comment]
Yes i am loading jQuery and Bootstrap before bootstrap-select and sometimes it's working and sometimes it's hide.
