### ISSUE TITLE
prevent click event from bubbling up the dom does not work

### ISSUE THREAD

**Issue by jonnsn** [silviomoreto/bootstrap-select#1577]
Hi,

I am using bootstrap-select inside a construct of two divs as it can bee seen in this codepen:
http://codepen.io/anon/pen/MbGwQb

As I have a click listener on div#first I would like to prevent that listener to be called if one clicks in the select field or in div#second. So I added a listener on div#second and called stopPropagation().
But doing so prevents the select from toggling (without any error messages).
Am I doing something wrong?

Thanks for your help!

**Comment by caseyjhol** [comment]
This appears to be a problem with Bootstrap (rather than with bootstrap-select specifically). See http://codepen.io/anon/pen/mOKbja. You may want to check with the Bootstrap team or on on StackOverflow.

**Comment by amitsquare** [comment]
@jonnsn , you can recognize the "event.target" before doing any action on CLICK for $("#first") .
I have updated the pen which you have created .

http://codepen.io/amitsqure/pen/ObEEeY

hope that will give some solution to your problem .

-Amit

**Comment by amitsquare** [comment]
@caseyjhol  , there is no problem with BOOTSTRAP .

**Comment by caseyjhol** [comment]
Yea, I worded that poorly. I didn't really mean there's a "problem" with Bootstrap, just that the problem is not with bootstrap-select.

**Comment by jonnsn** [comment]
Thank you two for your replies.
You're right, the issue comes from Bootstrap-Dropdown, because it listens on document-click, so I'm canceling it before. Common workaround seems to be to stop propagation and then trigger toggle on the dropdown. If I am trying this with bootstrap-select it completetly disappears.
Sadly I cannot check wich was the event target. I am using the bootstrap select inside a jquery Datatable-header. A click inside the header triggers a sort of the column. Datatable offers no way (or I could not find it) to hook into that click event and check the target. I ended up disabling the click listener coming from datatable using off() and adding my own listener on a child element. Downside is, that you can not click anywhere you want in the header anymore.

Thanks again for your help on this!
