### ISSUE TITLE
I am going crazy with Chrome - It work at one page and not on other

### ISSUE THREAD

**Issue by rajjanorkar** [silviomoreto/bootstrap-select#1579]
Hi Team,

This issue i am facing is with Chrome.

I spend hell lot of time to understand why it is not working on this page. 
Drop Down In Problem : **Vehicle**

[Not Working](http://privatedrivinginstructors.com.au/instructors/find?state=QLD&vehiclesType=Motorcycle&city=Brisbane&transmission=Automatic&gender=Male)

[Working](http://privatedrivinginstructors.com.au)

Can anybody please help me out.

Thank you, Raj

**Comment by amitsquare** [comment]
"vehiclesType" is creating i suppose .As you don't have mention which one .
you have used "data-dropupAuto=true" , which is "beDefault" setting of the plugin .

As you container is not able to contain the container box of options list .
Do change it false while creating select tag .

Will solve your problem .

Cheers

**Comment by caseyjhol** [comment]
What specifically isn't working? It appears to be working fine to me (can open the menu and select options).

**Comment by rajjanorkar** [comment]
Sorry Amit/Caseyjhol,

Forgot to mention it's **Vehicle** option not working.

I will try your suggested solution Amit and let you know, thank you for that.

**Comment by caseyjhol** [comment]
Hrmmm...the Vehicle option is working for me.

**Comment by rajjanorkar** [comment]
It's working on home page and not working on other page in chrome and Mozilla.

**Comment by caseyjhol** [comment]
Well, I'm confused. It seems to be working to me. What specifically about that field isn't working?

**Comment by rajjanorkar** [comment]
Ohh really? Problem is : when I try to select option from dropdown it does not show anything like others.

**Comment by rajjanorkar** [comment]
Hi @amitsquare ,

Perfect, i added that property and it worked fine. 
Thank you so much for your help.

Raj
