### ISSUE TITLE
Accent insensitive not working with liveSearchNormalize property

### ISSUE THREAD

**Issue by naisonsouza** [silviomoreto/bootstrap-select#1587]
**See this fiddle example**: [https://jsfiddle.net/53wy5czj/2/](https://jsfiddle.net/53wy5czj/2/)
Search "vito" or "vitó" no results!

**Comment by caseyjhol** [comment]
This is fixed in master via commit ba65054cc966da18634f14a7215840e3e24edc31.

See https://jsfiddle.net/53wy5czj/3/.
