### ISSUE TITLE
Key words search/data-tokens aren't working on example page (nor in code)

### ISSUE THREAD

**Issue by kburnettECS** [silviomoreto/bootstrap-select#1592]
The example on https://silviomoreto.github.io/bootstrap-select/examples/  under Key Words doesn't correctly filter when typing in a data-tokens  keyword.

**Comment by AlwaysTinkering** [comment]
Yes, search for data-tokens appears to still be broken

**Comment by caseyjhol** [comment]
Fixed in v1.12.2.
