### ISSUE TITLE
multiple select set value

### ISSUE THREAD

**Issue by dimitrissch** [silviomoreto/bootstrap-select#1595]
This is potentially my mistake or stupidness and not a bug but i am not able to select multiple values in the dropdown programmaticaly using variables.
I tried passing an array:
`var x = [ 'x','y','z'];`
`$().selectpicker('val',x);`
or even that:
`$().selectpicker('val',[x]);` 
and i tried passing a string:
`var y = 'x,y,z';`
`$().selectpicker('val',[y]);`
with no effect..

**Comment by birjolaxew** [comment]
[Seems to work for me.](https://jsfiddle.net/bfw0efv5/) Could you provide a JSFiddle of your code?

**Comment by dimitrissch** [comment]
Thanks for your time man.I am sorry i didnt noticed your reply before.What i want to do is something like that
[](https://jsfiddle.net/msllol/q3s8zoac/2/)
The array in my code is an ajax response.I want to store options in an array and append them

**Comment by kannanthescube** [comment]
https://jsfiddle.net/q3s8zoac/24/ - seems not working
I'm having same issue passing variable(y) in $().selectpicker('val',[y]);

**Comment by birjj** [comment]
@kannanthescube [It works fine if you change the Bootstrap CDN to one that still works](https://jsfiddle.net/kaxcj1cd/)

**Comment by gonzalezroda** [comment]
Hello everyone,
Remember that .val needs an JSON encoded text, for example ["1","2","3"]. Encode your ajax response to JSON. 

Good luck
