### ISSUE TITLE
Cannot read property 'valHooks' of undefined

### ISSUE THREAD

**Issue by kiluax** [silviomoreto/bootstrap-select#1596]
Hello,

I installed the plugin throw npm and added the html tags to the header:

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>

```
However I get the error:

```
Uncaught TypeError: Cannot read property 'valHooks' of undefined
    at bootstrap-select.min.js:7
    at bootstrap-select.min.js:8
    at bootstrap-select.min.js:7
    at bootstrap-select.min.js:7
```

does anybody know about this?

Regards.

**Comment by the-codetrane** [comment]
I'm having the same issue.

**Comment by caseyjhol** [comment]
What version of jQuery are you using? You need to load jQuery _before_ bootstrap-select.min.js.

**Comment by the-codetrane** [comment]
I was able to resolve this be removing `turbolinks`. Thanks for your help!

**Comment by stajason** [comment]
I have the same question,I can't think how you solved the problem.

**Comment by hotsen** [comment]
@caseyjhol is right, even if rails-assets.org [says something different](https://rails-assets.org/#/components/bootstrap-select). 

This order works for a Rails 4.2.5 app (w/ Turbolinks)

```
# app/assets/javascripts/application.js

//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//= require bootstrap-select
//= require turbolinks
//= require bootstrap

```

**Comment by denishrana09** [comment]
I am using this library in React, and I have the same problem of valHooks and options are not styled as shown in docs, How to solve for React now?
as mentioned in [https://github.com/snapappointments/bootstrap-select/issues/1875](issue), how to add bootstrap-select.js, it's already added in node_modules when installed!

**Comment by thorst** [comment]
I am having the same issue in prod, but my test is fine. They are both hosted on the same server. The only difference I can think of is that Prod has cloudflare enabled.

Im using php, with no real framework. I tried switching from the min version to an uncompressed version. I will update here if I find a solution.

Update:
I had two references to the js. Once I removed one I was fine.

**Comment by geralddevelop** [comment]
I have solve the issue on my side by adding **defer** into the script.
``` 
<link defer rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
<script defer src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
```

I hope this helps you all to solve the issue!

**Comment by sevket-karayilan** [comment]
I I am using laravel 9 and after I mix the file with npm, selectpicker works, but even though it works, I still get the same error. do you have a solution?
jquery sees var $. because I added a jquery line in front of where it gave the error and it prints it to the console with success. I have no idea what jquery turbo is. Do I need to install this extra in Laravel?

note: my jquery version is 3.6.0

**Comment by tik9** [comment]
More info when to use `defer` as in @GeraldHeng answer on [stack](https://stackoverflow.com/a/39711009/1705829). Use in `js` is `<cool_script>.setAttribute("defer", "defer")`. Loading jquery before `select` made it for me, both scripts at the end of `body` before `</body>`.
