### ISSUE TITLE
Does not work with some combos of Bootstrap 3.3.6 and jQuery 3.x

### ISSUE THREAD

**Issue by explody** [silviomoreto/bootstrap-select#1600]
While troubleshooting why this was not working in an app we are building, we discovered that a a few combos of Bootstrap and jQuery do not work as expected.  Specifically, the top level select appears but the dropdown does not appear. 

To reproduce:
Using the recommended Plunk,  change bootstrap to 3.3.6 and jquery to 3.1.1  https://plnkr.co/edit/4NXrHv1qcOF78fm3IFsm?p=preview

Or, this jsfiddle (jquery 3.1.1 + bootstrap 3.3.6):  https://jsfiddle.net/b8eojs37/1/

For the dropdown to work, lower bootstrap to  < 3.3.6.  Here is the same fiddle w/ Bootstrap 3.3.4:  https://jsfiddle.net/b8eojs37/2/

Or, curiously, leave bootstrap at 3.3.6 and drop jQuery to < 3.x:  https://jsfiddle.net/3n888tuj/1/

**Comment by caseyjhol** [comment]
Bootstrap 3.3.6 doesn't support jQuery 3.0.0 or higher. Please upgrade to Bootstrap 3.3.7. See https://github.com/twbs/bootstrap/issues/16834.
