### ISSUE TITLE
Cannot selected and clicked on my website

### ISSUE THREAD

**Issue by rebelholic** [silviomoreto/bootstrap-select#1601]
Still unlucky after searched to solve my issue in this repository on [my website ](http://www.rayasem.com/property/sale-or-rent?sortby=any&ispic=false&keyword=*&issale=false&isrent=false&minprice=any&maxprice=any&bedroom=any&type=any&area=any&country=id) such as cannot selected and clicked if using two select box like screenshot below:
![errorselect](https://cloud.githubusercontent.com/assets/6254876/21631780/0f76c3de-d272-11e6-8c1f-7782c024724a.jpg)

You should check out on [my website](http://www.rayasem.com/property/sale-or-rent?sortby=any&ispic=false&keyword=*&issale=false&isrent=false&minprice=any&maxprice=any&bedroom=any&type=any&area=any&country=id) to reproduce two select boxes like screenshot above.

**My HTML Code:**

```
  <div class="col-xs-2 checkboxtop">
               <div class="btn-group rayasem-filter-dropdown-result">
                            <select class="selectpicker form-control" title="<%=xl8('TITLE-Min-Price')%>" data-size="7" name="minPrice">
                                <optgroup label="<%=xl8('TITLE-Min-Price')%>">
                                    <% _.each(minMaxPrice.min, function (v,i) { %>
                                    <option value="<%= v.key %>"><%= v.val %></option>
                                    <% }); %>
                                </optgroup>
                            </select>
                        </div>
            </div>
            <div class="col-xs-2 checkboxtop">
                <div class="btn-group rayasem-filter-dropdown-result">
                    <select class="selectpicker form-control" title="<%=xl8('TITLE-Max-Price')%>" data-size="7" name="maxPrice">
                        <optgroup label="<%=xl8('TITLE-Max-Price')%>">
                            <% _.each(minMaxPrice.max, function (v,i) { %>
                            <option value="<%= v.key %>"><%= v.val %></option>
                            <% }); %>
                        </optgroup>
                    </select>
                </div>
            </div>
```

My website using:

- bootstrap: "3.3.7"
- bootstrap-select: "1.11.2"
- jquery: "1.12.4"

**Comment by mickster04** [comment]
1. please provide the working select box.
2. please provide a https://jsfiddle.net/ example. no one has time to debug your app for you. get to the pure functionality (just the drop down buttons) so that they don't work. then we can see clearly why the problem lies with selectpicker.
3. if you cannot replicate the problem with just selectpicker, keep adding bits of code in until it breaks. OR the problem isn't with selectpicker but something else in your app.


I would have thought you want a form for a form control?

**Comment by mickster04** [comment]
Also, have you considered updating jquery?

**Comment by mickster04** [comment]
https://jsfiddle.net/w18rr7ep/1/ working select boxes...

**Comment by rebelholic** [comment]
@mickster04 
I already tried to updating jquery to latest version but got conflict with other plugins. I will fix it with ASAP.
Actually I already provided working select box on [my website ](http://www.rayasem.com/property/sale-or-rent?sortby=any&ispic=false&keyword=*&issale=false&isrent=false&minprice=any&maxprice=any&bedroom=any&type=any&area=any&country=ph) like select "min price", "max price" or "property type to find out about what's cause this bug and cannot replicate to jsfiddle.net because too complicated.
You can check out the code on "My HTML Code" above

**Comment by mickster04** [comment]
Seems you have this working?

**Comment by rebelholic** [comment]
@mickster04 yeah its already fixed yesterday. That's bug just from my server side.

Thanks for your help.
