### ISSUE TITLE
Issues with up/down keys

### ISSUE THREAD

**Issue by andrews05** [silviomoreto/bootstrap-select#1603]
In some circumstances, using up/down keys to move through the list doesn't quite work as expected.

See this plunker: https://plnkr.co/edit/QnzGd6LPrdAnco71W9Ma?p=preview
1. Type ASD into the livesearch and then use the arrow keys to move through the items. Some items will be skipped for some reason.
2. In the second menu, open the menu then press the up arrow. It should highlight the first item. Press the up arrow a second time and nothing happens. A third press will then wrap to the end of the list.

**Comment by caseyjhol** [comment]
I can't recreate issue 1. What browser are you using?

**Comment by andrews05** [comment]
Sorry, didn't get that quite right: First use the arrow keys to change the highlighted item (e.g. just push down once), then type ASD and try using the arrow keys again.

**Comment by caseyjhol** [comment]
Ah, now I see it. I'll take a closer look at your PR and can hopefully get it merged soon.

**Comment by andrews05** [comment]
Thanks! Happy to make any changes to it if you need.
