### ISSUE TITLE
LiveSearch performance

### ISSUE THREAD

**Issue by andrews05** [silviomoreto/bootstrap-select#1606]
The fix implemented for the key word searching (ba65054cc966da18634f14a7215840e3e24edc31) unfortunately made the performance much worse again. The culprit is the .parent() function - somehow over half the performance improvement from #1516  was gained by the removal of .parent().
The best solution I can find is to move the `.find('a')` into the pseudo expressions, which allows to remove .parent() while still keeping the key words working. I was thinking there could be remove for some extra improvement as well though. Here's what I have in mind:

1. Move .find('a') into the pseudo expressions as mentioned above.
2. Use the token to store normalized text, eliminating the need for the extra pseudo expressions.
3. Use normal functions instead of pseudo expressions and optionally accept a function for the liveSearchStyle. This is marginally faster and would allow users to implement their own search function which could be used to do something like 'word starts with', or to provide optimal performance by ignoring tokens.

Any thoughts on this? I'm happy to make a PR for this if you think it would be a good idea.

(P.S. Much apologies for breaking the key word searching)

**Comment by caseyjhol** [comment]
I'm working on an updated version of bootstrap-select that uses virtualization (rendering only the options that are actually visible). This makes live search *instant* (using a select with 4000 options in my testing) and works pretty awesome. The slowest part about the search currently is showing/hiding thousands of elements at once. I'm working on making this new version available in a separate branch so others can test it as well.

**Comment by andrews05** [comment]
Awesome, I look forward to testing that out :)

**Comment by caseyjhol** [comment]
I just added a virtual scrolling feature (which results in instant searching) in the [virtual-scrolling](https://github.com/silviomoreto/bootstrap-select/tree/virtual-scrolling) branch. It's still a WIP, and there are a few features missing, some I'm aware of (the startsWith feature for example), and some I'm sure I'm not. Try it out - I'm looking for feedback. Please post all findings in #1229.
