### ISSUE TITLE
I want to use data-live-search automatic clear 'blank' frunt and end.

### ISSUE THREAD

**Issue by yy7054wyq5** [silviomoreto/bootstrap-select#1607]
`<select class="selectpicker" data-live-search="true" tabindex="-98">
    <option>Hot Dog, Fries and a Soda</option>
    <option>Burger, Shake and a Smile</option>
    <option>Sugar, Spice and all things nice</option>
  </select>`

if I input ' Hot',
Notice,In front of the 'Hot' have a 'blank'
And then, this will show "no  result matched ' hot'".
So,if i want to automatic clear 'blank' before search,how to do?
Thank you

**Comment by amitsquare** [comment]
Hi ,

Look at this Source code of Library for search input function . [search Input Function](https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L1417-L1464) 

`searchInputValue = that.$searchbox.val() `

for removing front & back spaces , use trim function of jquery .

`updatedSearchValue = $.trim(that.$searchbox.val())`

Use this updated search value to search from the list .
     `this.$searchbox.on('input propertychange', function () {
        that.$lis.not('.is-hidden').removeClass('hidden');
        that.$lis.filter('.active').removeClass('active');
        $no_results.remove();

        if (that.$searchbox.val()) {
         var updatedSearchValue = $.trim(that.$searchbox.val()) ;
          var $searchBase = that.$lis.not('.is-hidden, .divider, .dropdown-header'),
              $hideItems;
          if (that.options.liveSearchNormalize) {
            $hideItems = $searchBase.find('a').not(':a' + that._searchStyle() + '("' + normalizeToBase(updatedSearchValue) + '")');
          } else {
            $hideItems = $searchBase.find('a').not(':' + that._searchStyle() + '("' + updatedSearchValue + '")');
          }

          if ($hideItems.length === $searchBase.length) {
            $no_results.html(that.options.noneResultsText.replace('{0}', '"' + htmlEscape(that.$searchbox.val()) + '"'));
            that.$menuInner.append($no_results);
            that.$lis.addClass('hidden');
          } else {
            $hideItems.parent().addClass('hidden');

            var $lisVisible = that.$lis.not('.hidden'),
                $foundDiv;

            // hide divider if first or last visible, or if followed by another divider
            $lisVisible.each(function (index) {
              var $this = $(this);

              if ($this.hasClass('divider')) {
                if ($foundDiv === undefined) {
                  $this.addClass('hidden');
                } else {
                  if ($foundDiv) $foundDiv.addClass('hidden');
                  $foundDiv = $this;
                }
              } else if ($this.hasClass('dropdown-header') && $lisVisible.eq(index + 1).data('optgroup') !== $this.data('optgroup')) {
                $this.addClass('hidden');
              } else {
                $foundDiv = null;
              }
            });
            if ($foundDiv) $foundDiv.addClass('hidden');

            $searchBase.not('.hidden').first().addClass('active');
          }
        }
      });
    }`

**Comment by yy7054wyq5** [comment]
Thank you very much.
Because the Spring Festival.I forget the Issue.
Sorry.

**Comment by bulabula001** [comment]
@amitsquare  tks, i have occured the same problem.  it works well.

**Comment by bulabula001** [comment]
also the code 
`$hideItems = $searchBase.not(':' + that._searchStyle() + '("' + that.$searchbox.val() + '")');`
should replace  that.$searchbox.val()  to  updatedSearchValue
