### ISSUE TITLE
How to set default value?

### ISSUE THREAD

**Issue by harked** [silviomoreto/bootstrap-select#1608]
Hi All.

How can i set default value of bootstrap-select?
for example i have a list of selection : apple, mango, orange, pineaple.
And i want to set default value of the selection is apple.

is there a way to do that?

**Comment by yy7054wyq5** [comment]
$('.selectpicker').selectpicker('val', 'Mustard');
$('.selectpicker').selectpicker('val', ['Mustard','Relish']);

**Comment by mickster04** [comment]
<select ... value='Mustard'><option....

doesn't that work?

**Comment by fabriciosf1** [comment]
Mine also was not working, but I put $ ('selectpicker'). Selectpicker ('val', 'Mustard'); below the input select and worked

**Comment by loic-bellinger** [comment]
Is there a way to use $('.selectpicker').selectpicker('val', x) without triggering the changed.bs.select event?

**Comment by caseyjhol** [comment]
@LouisBellinger 
```js
$('.selectpicker').val('x').selectpicker('render');
```
