### ISSUE TITLE
load slow with large data

### ISSUE THREAD

**Issue by purvesh4575** [silviomoreto/bootstrap-select#1611]
I am using the latest version of selectpicker 1.12.1, which takes some time to load with large data about 1000 records.

**Comment by AronDavis** [comment]
This seems to be caused (at least partially) due to an <li> element being created for every option.  A solution for this could be to only generate <li>'s for options that are currently visible in the  dropdown.

**Comment by purvesh4575** [comment]
can you give me example here?

**Comment by AronDavis** [comment]
@purvesh4575 the solution is not built in, just offering my thoughts on a way to fix it.

You can inspect the html source to see all of the `<li>`'s created.

**Comment by purvesh4575** [comment]
@AronDavis yes because of `<li>` created for each record will slow down browser performance due to heavy load on html. And that's why i am looking for solution here.

**Comment by caseyjhol** [comment]
Please subscribe to #1229 for updates regarding performance.

**Comment by caseyjhol** [comment]
I just added a virtual scrolling feature (which results in instant searching) in the [virtual-scrolling](https://github.com/silviomoreto/bootstrap-select/tree/virtual-scrolling) branch. It's still a WIP, and there are a few features missing, some I'm aware of (the startsWith feature for example), and some I'm sure I'm not. Try it out - I'm looking for feedback. Please post all findings in #1229.
