### ISSUE TITLE
Does not seen in modal

### ISSUE THREAD

**Issue by t3mh4** [silviomoreto/bootstrap-select#1612]
i use mvc 6 and i popup an bootstrap modal but the select does not seen on modal.
It seem in html like that;

```
<select class="selectpicker show-tick" data-width="100%" id="Cities" name="Cities" required="required"><option selected="selected" value="20">XX</option>
<option value="64">YY</option>
</select>
```

**Comment by amitsquare** [comment]
force the render of select dropdown .
`$("#Cities").selectpicker('render')` 

For documentation [](http://silviomoreto.github.io/bootstrap-select/methods/#selectpickerrender)

**Comment by t3mh4** [comment]
ok it worked. thanks for your help

**Comment by amitsquare** [comment]
please close the issue .

**Comment by hrustbb2** [comment]
this is not work

**Comment by Supposer** [comment]
+1
this is not work
