### ISSUE TITLE
Remove focus from searchbox

### ISSUE THREAD

**Issue by dipeshcct** [silviomoreto/bootstrap-select#1613]
Hello,

I want to remove focus from search box when open select. I tried by using "shown.bs.select" event. But I cant remove focus from search box.

Here is my code:
`$('.selectpicker1').on('shown.bs.select', function (e) {		
		$(this).parent().children('.dropdown-menu').children('.bs-searchbox').children('.form-control').focusout();
	});`

**Comment by amitsquare** [comment]
[Source Lines for Focus](https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L1408-L1410)

Either comment it out for permanent effect Or pass additional option along with Select .

`<select class="selectpicker" data-live-search="true" data-focus-off="true">
 <option>test1</option>
<option>test2</option>
<option>test3</option>
</select>`


Then update above mentioned source lines like this ..

`if(!that.options.focusOff){
     setTimeout(function () {
          that.$searchbox.focus();
        }, 10); 
}`

hope this will help you out .

**Comment by dipeshcct** [comment]
Thanks @amitsquare, It's working properly. Thanks for your help.
