### ISSUE TITLE
Can't make option "data-content" to work

### ISSUE THREAD

**Issue by kiopsycho** [silviomoreto/bootstrap-select#1616]
Hi, I am a student at Technological institute of central Macedonia. I try to use this for a project, but I am unable to make it work. I try to have a selector where all options are hrefs too. So I tried the <option data-content=""></option> method but it didn't work. https://jsfiddle.net/os506oop/. Any help would be highly appreciated.

**Comment by caseyjhol** [comment]
You did a few things wrong. For external resources, you used the full link tag (rather than just the URL). Also, you had quotes within quotes, which doesn't work.

Try:

```html
<select class="selectpicker">
  <option data-content='<a href="http://www.google.gr"></a>'>All</option>
</select>
```
