### ISSUE TITLE
How can i use material icons in multiple select?

### ISSUE THREAD

**Issue by kayuda91** [silviomoreto/bootstrap-select#1619]
How can i use material icons in multiple selects?
`<i class="material-icons">check</i>` for example.

When i try to set in options
`iconBase: 'material-icons',
 tickIcon: 'check',`
it's render
`<span class="material-icons check check-mark"></span>`.

But material icon must be `<i class="material-icons">check</i>`

**Comment by caseyjhol** [comment]
Bootstrap-select doesn't support ligatures. You'll either need to create a custom stylesheet for the font, or or a different Material icon font.

e.g.

```css
.check:after {
    content: 'check';
}
