### ISSUE TITLE
How to dynamically add options on a select?

### ISSUE THREAD

**Issue by dontuta** [silviomoreto/bootstrap-select#1623]
I'm trying to dinamically populate a select element in my page, but yet without success. Is there an equivalent to the following code?
JS
$(document).ready(function () {
                var options = [];
                var src = [
                            { id : 1, txt : "test 1" },
                            { id : 2, txt : "test 2" },
                            { id : 3, txt : "test 3" }
                        ];
                        src.forEach(function (item){
                            var option = "<option value='" + item.id + "'>" + item.txt + "</option>"
                            options.push(option);
                        });
                        $('.picker').html(options);
                        $('.picker').selectpicker('refresh');
});

html
<select class="selectpicker picker" data-live-search="true">
</select>

**Comment by dontuta** [comment]
Just forget it, I found the error in my code =)

**Comment by zia1177** [comment]
In case anybody wondering what's the correct code...

`$(document).ready(function () {
    var options = [];
    var src = [
        {id: 1, txt: "test 1"},
        {id: 2, txt: "test 2"},
        {id: 3, txt: "test 3"}
    ];
    src.forEach(function (item) {
        var option = "<option>" + item.txt + "</option>"
        options.push(option);
    });
    $('.selectpicker').html(options);
    $('.selectpicker').selectpicker('refresh');
});`

**Comment by cetintas41** [comment]
`var data = [{"ID":"1", "NAME": "Leo"}];
$.each(data, function () {
     var options = "<option " + "value='" + this.ID + "'>" + this.NAME + "</option";
     $(".selectpicker").append(options);
 });
$('.selectpicker').selectpicker('refresh');`

**Comment by ghost** [comment]
function GetData() {
	$.ajax({
		type: "GET",
		url: "Home/List",
		contentType: "application/json; charset=utf-8",
		dataType: "json",
		success: function (data) {
			$.each(data, function () {
				var options = "<option " + "value='" + this.ID + "'>" + this.NAME + "</option>";
				$(".selectpicker").append(options);
			});
			$('.selectpicker').selectpicker('refresh');
		},
		failure: function () {alert("Failed!");}
	});
}
