### ISSUE TITLE
Does not work with bootstrap 4 

### ISSUE THREAD

**Issue by kamranbashir** [silviomoreto/bootstrap-select#1629]
Does any one has bootstrap 4 running version?

**Comment by huphtur** [comment]
Looks like there's a PR ready for this? #1522

**Comment by caseyjhol** [comment]
Duplicate of #1135. In the future, please use the search feature.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
