### ISSUE TITLE
Rewrite example

### ISSUE THREAD

**Issue by higimo** [silviomoreto/bootstrap-select#1632]
http://tjwebb.github.io/react-bootstrap-select/

This documentation is copy http://silviomoreto.github.io/bootstrap-select/examples/

This documentation must include **react** code.

**Comment by caseyjhol** [comment]
Huh?

**Comment by martin0852** [comment]
I'm with @higimo here, the page says react-bootstrap-select but the examples are from the regular example on this repo. The examples should show how to use the module in React.

**Comment by higimo** [comment]
example:
```
import Select from 'bootstrap-select'

return <Select class="selectpicker">
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Relish</option>
</Select>
```

**Comment by caseyjhol** [comment]
This project is separate from react-bootstrap-select. You'll want to speak to the developer of that project about this.
