### ISSUE TITLE
How to get select Option

### ISSUE THREAD

**Issue by Clcll** [silviomoreto/bootstrap-select#1642]
How can I get selected option. 
I am using ReactJs.

**Comment by ghiscoding** [comment]
You should look on the entire example page and also [Bootstrap-Select - Methods](http://silviomoreto.github.io/bootstrap-select/methods/#selectpickerval) 

Calling 
```javascript
$('.selectpicker').selectpicker('val');
```
will give you the selected values

**Comment by Frossard** [comment]
Thanks! This did help a lot.
