### ISSUE TITLE
Select options with jquery

### ISSUE THREAD

**Issue by Six-wars** [silviomoreto/bootstrap-select#1643]
Hi,
I'm trying to select the already selected options via jquery, however the black `tick` isn't visible.

Here's what I'm trying

```
$('.skills :last').find('option:contains("Calculating data")').prop('selected', true);
[option]

$('.skills :last').val();
["Calculating data↵"]

$('.skills');
[div.btn-group.bootstrap-select.show-tick.skills.job-seeker-content-spacing, select.selectpicker.skills.job-seeker-content-spacing]

$('.skills :first').find('option:contains("Calculating data")').prop('selected', true);
[option]

$('.skills :first').val();
""
```

I've also tried `click` instead of propping the select neither works. [full details](http://stackoverflow.com/questions/42327541/bootstrap-select-selecting-options-using-jquery)

**Comment by Kevenvz** [comment]
Hey,

If you set the current selected options you need to rerender te select. You can do this programmatically using the `.selectpicker('render')` function. This should fix your issue.

Docs: https://silviomoreto.github.io/bootstrap-select/methods/#selectpickerrender

**Comment by Six-wars** [comment]
Resolved it
