### ISSUE TITLE
selected="selected" not being removed.

### ISSUE THREAD

**Issue by asacarter** [silviomoreto/bootstrap-select#165]
Hi

I've justed tested the latest version committed on 6th June.

I've tested with two items in the select

`<select id="gender" name="gender" class="selectpicker">
    <option value="M">Male</option>
    <option value="F">Female</option>
</select>`

When an option is selected `selected="selected"` is added the select option but not removed from other options. Therefore only the fist option can be selected.

Hope you can fix it soon. The version on the demo page is working fine for me.

Thanks

Asa

**Comment by gravelld** [comment]
Hmmm, for me, JQuery 1.8.3 and Chrome 38.0.2125.104 (also FF) only attr works... In the click handler:

          if (!that.multiple) { // Deselect all others if not multi select box
            $options.prop('selected', false);
            $option.prop('selected', true);
            that.$menu.find('.selected').removeClass('selected');
            that.setSelected(clickedIndex, true);

The lines 2-3 don't change the selected status of the original `<select>`. Note the dropdown is successfully changed.
