### ISSUE TITLE
  Slowness when searching by use livesearch with more than 3 thousand records

### ISSUE THREAD

**Issue by xssunircomercial** [silviomoreto/bootstrap-select#1650]
## Bug reports

Slowness when searching for livesearch with more than 3 thousand records

I am using the component and is slow when using the livesearch option with more than 3000 records in Explorer, firefox and Chrome, if they can help me please

Thanks!

**Comment by caseyjhol** [comment]
I just added a virtual scrolling feature (which results in instant searching) in the [virtual-scrolling](https://github.com/silviomoreto/bootstrap-select/tree/virtual-scrolling) branch. It's still a WIP, and there are a few features missing, some I'm aware of (the startsWith feature for example), and some I'm sure I'm not. Try it out - I'm looking for feedback. Please post all findings in #1229.

**Comment by Gatunox** [comment]
I've tried this branch and for some reason it's not working. i will post my findings here
