### ISSUE TITLE
Dropdown only

### ISSUE THREAD

**Issue by Six-wars** [silviomoreto/bootstrap-select#1656]
How can you make bootstrap-select dropdown only?

**Comment by caseyjhol** [comment]
?

**Comment by holtkamp** [comment]
@Six-wars have a look at: http://silviomoreto.github.io/bootstrap-select/examples/#dropup-menu

You can prevent the menu from dropping up / only allow drop down, by setting `dropupAuto` to `false`... Does this work for you?
