### ISSUE TITLE
Make the default title blank so it behaves like a regular select

### ISSUE THREAD

**Issue by grosser** [silviomoreto/bootstrap-select#1671]
just added this to a bunch of our selects and the only recurring annoyance was having to add `title: ""` ... would be great if it behaved like a regular select and showed nothing when nothing is selected to keep the visual clutter on the page low.

https://github.com/zendesk/samson/pull/1819

**Comment by caseyjhol** [comment]
http://silviomoreto.github.io/bootstrap-select/options/

See `noneSelectedText`

**Comment by grosser** [comment]
I understand that it's an option, my issue was that it would be nice if the
default looked like a regular submit.

**Comment by caseyjhol** [comment]
We may consider changing that later. In the meantime,

```js
$.fn.selectpicker.Constructor.DEFAULTS.noneSelectedText = '';
```

So you only have to set it once.

**Comment by grosser** [comment]
nice!
