### ISSUE TITLE
Android 4.4.4 Illegal constructor

### ISSUE THREAD

**Issue by alanaasmaa** [silviomoreto/bootstrap-select#1678]
Android 4.4.4 Illegal constructor

Agent: Mozilla/5.0 (Linux; U; Android 4.4.4; fi-fi; SM-G357FZ Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

Using jQuery 1.11.2
Using plugin v1.10.0

This line causes a crash `event = new Event(eventName, {`

```javascript
    if (el.dispatchEvent) {
      if (typeof Event === 'function') {
        // For modern browsers
        event = new Event(eventName, {
          bubbles: true
        });
      } else {
```

**Comment by caseyjhol** [comment]
Duplicate of #1286.
