### ISSUE TITLE
How to preselected a multiple choice ?

### ISSUE THREAD

**Issue by ochiers** [silviomoreto/bootstrap-select#1684]
Hello,

I want to create a multiple select boxes where some option are preselected.

The option are dynamic so they are different at each generation.

How can i do it ?

I already try to simulate click, manipulate class manually but I don't find the solution.
I already try the method .val(); .render() and selectpicker('val', ["aud1 aud1", "aud2 aud2"]) but it doesn't work...
I need help.

Thanks

**Comment by caseyjhol** [comment]
Set the value like you would normally, and then call render, or use the val method. If that's not working, post an example.
