### ISSUE TITLE
Refresh not showing all changes.

### ISSUE THREAD

**Issue by concept-core** [silviomoreto/bootstrap-select#1690]
Hello I am having a issue with this plugin when I load in data from localStorage.

We allow the user to go ahead and typ in the form and the moment they leave it is saved in localStorage.

When they come back the whole form is being republished if they wish so.
Same goes for a candidate select `selectbox`.

I tried to solve this with the following js code : 
```js
if ($formData[$i].split("=")[0] === "contacts_id") {
    $("[name='" + $formData[$i].split("=")[0] + "'] option").each(function() {
        if ($formData[$i].split("=")[1] === $(this).val()) {

            console.log($(this).val(), $('[name=contacts_id]').selectpicker());

            $(this).attr('selected', true);
            $('[name="contacts_id"]').selectpicker('refresh');

            getContactInformation($formData[$i].split("=")[1]);
        }
    });
}
```

I gives me back the following : https://puu.sh/v19Jo/fa52ebc37f.png.
And this is the html : https://puu.sh/v1a03/73182f430c.png.

Is there any reason why I don't see 3 selected items.

**Comment by caseyjhol** [comment]
You probably need to use `$(this).prop('selected', true)` instead of `attr`.
