### ISSUE TITLE
Single Select and Blank Options

### ISSUE THREAD

**Issue by MrCaspan** [silviomoreto/bootstrap-select#1696]
I cannot seem to find a way to add an option to remove the existing solution? I want to remove the selection sometimes. Is this possible on a single select?

**Comment by MrCaspan** [comment]
Nobody? there must be a way to select nothing with this

**Comment by caseyjhol** [comment]
It's not possible to deselect an option with a single select. You have a few choices: You can include a blank option at the start of your select, or you can use a multiple select with `maxOptions: 1` set.

**Comment by Adityashaw** [comment]
> It's not possible to deselect an option with a single select. 

Any particular reason for not providing it?
