### ISSUE TITLE
"changed.bs.select" event not working as expected

### ISSUE THREAD

**Issue by angelpcadena** [silviomoreto/bootstrap-select#1697]
Currently the documentation states that "changed.bs.select" does the following:

> This event fires after the select's value has been changed. It passes through event, clickedIndex, newValue, oldValue.

But that's not the case, right now it just outputs the event, selected index and two boolean values that are always, true and false, in that order.

I made a jsfiddle: https://jsfiddle.net/SrGoodbar/9xotvca2/

**Comment by farhansyed9** [comment]
Getting the same issue, you figure it out yet?

**Comment by angelpcadena** [comment]
Yeah, just listen to the 'change' event on the <select> instead of using Bootstrap's events, worked on my case, using KnockoutJS.

**Comment by caseyjhol** [comment]
Yea, the current implementation doesn't make a lot of sense. See https://github.com/silviomoreto/bootstrap-select/issues/1378#issuecomment-216393099

> newValue and oldValue refer to the value of the changed option - either true or false - to see whether the option was changed to be selected or unselected, not the value of the select itself. However, oldValue is a bit redundant, as it's obviously always the opposite of newValue. It would also make more sense to refer to newValue as selected and oldValue as unselected to improve clarity. It would make more sense to also pass in the select's previous value. Passing in the select's current value is unnecessary, as it can easily be retrieved with $(this).val().

I'd like to replace oldValue with the actual previous value of the select.

**Comment by angelpcadena** [comment]
Ok, thanks for the clarification!

**Comment by caseyjhol** [comment]
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)! @angelpcadena Please feel free to close this issue.
