### ISSUE TITLE
Remove Drop Down arrow?

### ISSUE THREAD

**Issue by MrCaspan** [silviomoreto/bootstrap-select#1706]
Is there a way to remove the drop down arrow to the right of the text. I want it to look like just a button that you press and you get a list if at all possible

**Comment by tpetrychyn** [comment]
You can remove it using css by adding the following rule:
```
.caret {
    display: none;
}
```

Or you should be able to remove it in your selectpicker using the `template.caret` option. You can see that option and more: https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L348
