### ISSUE TITLE
Reset Dropdown

### ISSUE THREAD

**Issue by chandru1822** [silviomoreto/bootstrap-select#1712]
I am using two dropdown using Bootstrap-select.I want to reset one dropdown if i selected other dropdown and vice-versa. So,Please help me to fix this problem.

**Comment by caseyjhol** [comment]
Not 100% sure what you're asking, but it sounds like the `refresh()` method might be what you're looking for? http://silviomoreto.github.io/bootstrap-select/methods/#selectpickerrefresh

You can update the value of one select to "reset" it and then call refresh.
