### ISSUE TITLE
Issues re-rendering multiple select fields, empty options (although count is correct)

### ISSUE THREAD

**Issue by E-VANCE** [silviomoreto/bootstrap-select#1713]
Hi there,

I am using the latest version of bootstrap-select (1.1.12) together with the latest Bootstrap 4 Alpha 6 and jQuery 1.12.4. I have created a custom logic combining three select fields to be dependant of each other, meaning:

If A shows value "X" then B only displays values "X.1,X.2,X.3,X.4" and C (being dependant of B and A) only shows values "X.1.1,X.1.2,X.2.1,etc.".

Actually I almost made it but there is some really strange behaviour when it comes to rendering the last select box since the options are there but the select itself stays empty...?

Tested with the latest versions of Firefox, Chrome and Safari, all the same.

Find a **live example** here on [Plunkr](https://plnkr.co/edit/h3N7e5e2WXWJJY4qC5l5?p=preview).

Looking forward to getting some insights into why this might happen and how to fix it.

Thanks for a great plugin & Regards,
Henning

**Comment by E-VANCE** [comment]
Stupid me... I found the error, the options on the second select had values but no actual text in between `<option value="xyz"></option>` thus bootstrap-select couldn't pick up on those.

Sorry for the fuss, leaving the code example out there for reference's sake.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
