### ISSUE TITLE
Programatically select a value from dropdown options

### ISSUE THREAD

**Issue by imranitian** [silviomoreto/bootstrap-select#1720]
Programmatically select a value from drop down options

<select id="urole" name="urole" class="selectpicker" data-live-search="true" title="User Role" onchange="document.getElementById('urole').value = this.options[this.selectedIndex].text" >
		<option data-icon="glyphicon-user" value="Manager">Manager</option>
		<option data-icon="glyphicon-user" value="Staff">Staff</option>
</select>

For example, an option 'Staff' is fetched from database and is desired to automatically selected.
Please help.

**Comment by tox2ik** [comment]
try: $('#picker').selectpicker('val', 'Staff');

**Comment by badeamihai** [comment]
And with that, you can make your own optional data attribute, so it's easier to change it from a server side language:

`<select name="name" class="selectpicker" data-val="some-variable"> ... </select>`

And then:
`$(".selectpicker").selectpicker("val", function(){
return $(this).data("val");
})`

**Comment by mtonc** [comment]
> try: $('#picker').selectpicker('val', 'Staff');

This works, but the issue I had was this method does not trigger the 'changed.bs.select' event. It should do that imo.

**Comment by caseyjhol** [comment]
Please follow #1303.
