### ISSUE TITLE
Multiple Select - show dropdown as "<Blank> Selected..."

### ISSUE THREAD

**Issue by onesneakymofo** [silviomoreto/bootstrap-select#1721]
Hello,

There's a UI problem introduced in my web app when I select a lot of multiple values.  

Is there any way to convert the select box to "<Blank> Selected..." after a certain value is hit?

In my screenshot below, instead of all of the positions, it would say
[New York City, Los Angeles] [9 positions selected]

Initial form:
![initial_form](https://cloud.githubusercontent.com/assets/3330804/26317867/8f48833a-3ede-11e7-996c-b7b4b9eb3726.png)

After selecting a lot of positions:
![multiple_select](https://cloud.githubusercontent.com/assets/3330804/26317850/7ad963e2-3ede-11e7-9512-8b13be8ce2ed.png)

Thanks.

**Comment by onesneakymofo** [comment]
Plunker example: https://plnkr.co/edit/SQt0hSykjjWEym0Rj8X4

**Comment by caseyjhol** [comment]
http://silviomoreto.github.io/bootstrap-select/examples/#selected-text-format

**Comment by onesneakymofo** [comment]
Wowwwww, how did I miss that? Thanks @caseyjhol - sorry for wasting your time, my friend.
