### ISSUE TITLE
Firefox : Impossible to select via javascript the first item of the select when there is a title.

### ISSUE THREAD

**Issue by mlerouxonf** [silviomoreto/bootstrap-select#1730]
Hi, i have a weird bug in Firefox 53 Mac / Firefox 45 PC.

When i have a titlle in the select, i can't select the first element of the dropdown via javascript and then refresh the selectpicker. In Safari, it's not only the first one but all of them. The selectpicker stays to the value of the title.
It's working fine if : 
-I try in another browser
-I remove the title
-I select via javascript the second element in firefox

Here is a fiddle : 
https://jsfiddle.net/mlerouxonf/2vL8qrg4/2/

Thank you very much for your help!

**Comment by caseyjhol** [comment]
You should be using `prop` instead of `attr` when setting `selected`.

`$('.selectpicker').find('option[value="alphabetical"]').prop('selected', true);`
