### ISSUE TITLE
How to create select without "Nothing selected" option?

### ISSUE THREAD

**Issue by AlexByte** [silviomoreto/bootstrap-select#1732]

**Comment by caseyjhol** [comment]
?

`noneSelectedText`

http://silviomoreto.github.io/bootstrap-select/options/

**Comment by yuviprathap** [comment]
How to solve the issue pls any help me

**Comment by caseyjhol** [comment]
`noneSelectedText: ''`

**Comment by mertskaplan** [comment]
OK then without multiple select?

**Comment by abad93** [comment]
You can just add `<option value=""> </option>`
like
` <select class='selectpicker form-control'>`
             ` <option value=""> </option>`
              `<option value="1"> Number 1</option>`
             ` <option value="2"> Number 2</option>`
           ` </select>`
