### ISSUE TITLE
Make width to have auto

### ISSUE THREAD

**Issue by jt4000** [silviomoreto/bootstrap-select#1740]
Hello,

I would like to make the width of the select to have auto width but it doesn't work.

What part am I missing?

I'm using bootstrap v3 with bootstrap-select

Demo: http://jsbin.com/fedusazilo/edit?html,output

Thank you!

**Comment by caseyjhol** [comment]
You need to set `data-width="auto"`. See http://silviomoreto.github.io/bootstrap-select/options/.
