### ISSUE TITLE
Missing option "selectedAllText"

### ISSUE THREAD

**Issue by Tim77277** [silviomoreto/bootstrap-select#1743]
I love bootstrap-select. It is easy to use and pretty. But I think there is a missing option for developers, which is how to change the text when a user click on 'Selected All' action button. The default value just show all the option text. But how if I want to show "All" instead of everything? (Not the text on select all button but the text that actually show after click on the select all button.)

**Comment by caseyjhol** [comment]
#1566

```js
    countSelectedText: function (numSelected, numTotal) {
      if (numSelected == 1) {
        return "{0} item selected";
      } else if (numSelected === numTotal) {
        return "All items selected";
      } else {
        return "{0} items selected";
      }
    }
```
