### ISSUE TITLE
bootstrap-select width changes on resize

### ISSUE THREAD

**Issue by jonasgroendahl** [silviomoreto/bootstrap-select#1744]
Hello,

I'm trying out bootstrap-select instead of the regular bootstrap select (<select> with form-control class) and it's great until i attempt to resize the page. The selectpicker doesn't fit into my panel anymore if i make the window smaller which is a shame. This is my html:

[snippet.txt](https://github.com/silviomoreto/bootstrap-select/files/1088490/snippet.txt)

Any smart way to make the select align inside the column/panel even though the text in the options of the select are too big(crop it instead) upon resizing the window? It needs to be dynamic so you can resize the screen to whatever size you want.

Image to showcase the problem:

![resize_example](https://user-images.githubusercontent.com/23399953/27337478-d497549c-55d2-11e7-8e64-08a84aa7cf74.png)

**Comment by dancadana** [comment]
What have happened to this questions? I need an answer too
