### ISSUE TITLE
Feature Select / Deselect all in one option

### ISSUE THREAD

**Issue by catacs** [silviomoreto/bootstrap-select#1753]
I want to add the option of select / deselect all, but from the design point of view a better user experience is to have the option at the same level as the list elements. Is there any option to add that feature?

Example:

![image](https://user-images.githubusercontent.com/3251397/27635085-092fa586-5c06-11e7-83b7-1f3cc1b6e2ae.png)

![image](https://user-images.githubusercontent.com/3251397/27635306-bc627c82-5c06-11e7-8f50-4e4b38d9402a.png)

**Comment by caseyjhol** [comment]
This isn't available as an option. It seems like poor UX, as the user would have to always scroll back up to the top to select/deselect all. In any case, this should be easy enough to implement by making the first option "Select / Deselect all" and then checking the value of the select on change, and then call either `$('.selectpicker').selectpicker('selectAll')` or `$('.selectpicker').selectpicker('deselectAll')`.

**Comment by catacs** [comment]
Thank you for feedback. We finally implemented as the provided method with the visible select/deselect out of scroll.
