### ISSUE TITLE
Show option value or optgroup as placeholder when selected

### ISSUE THREAD

**Issue by interrogator** [silviomoreto/bootstrap-select#1759]
I have a number of optgroups with identical options. When selected, the placeholder text shows only the option, so it is not possible to easily see which optgroup it was chosen from.

It'd be good if there was a placeholder display option that combined the optgroup value and the option text, perhaps separated by `": "`.  Something like this is in stale PR  https://github.com/silviomoreto/bootstrap-select/pull/306.

The other option would be to have a data attribute inside the `<option>` that could be used as placeholder when the text is selected.

```html
<select class="selectpicker" data-selected-text-format="custom">
  <optgroup value="main">
    <option data-placeholder="main: sub">sub</option>
  </optgroup>
</select>
```

My current workaround is not really elegant:

```javascript
$('.selectpicker').on('changed.bs.select', function (event, clickedIndex, newValue, oldValue) {
    var text = $(this).find("option").eq(clickedIndex).val();
    $(this).prev().text(text);
});
```

The final option is to allow the user to pass in a function that formats the text, as in PR https://github.com/silviomoreto/bootstrap-select/pull/1660. That's a bit over the top for my use case.

**Comment by caseyjhol** [comment]
See http://silviomoreto.github.io/bootstrap-select/examples/#selected-text

**Comment by interrogator** [comment]
Oh great, my bad, don't know how I missed it! Happy to close
