### ISSUE TITLE
dropdownAlignRight doesn't work with div pull-right

### ISSUE THREAD

**Issue by kimbim** [silviomoreto/bootstrap-select#1765]
Am I doing something wrong? See jsfiddle: http://jsfiddle.net/mfrup5bL/103/

**Comment by caseyjhol** [comment]
You need to use `data-dropdown-align-right="true"`, as well as a newer version of bootstrap-select (you're using v1.5.4 in your linked example).

**Comment by kimbim** [comment]
Ah, silly of me. Thanks!

Den tor. 20. jul. 2017, 20:32 skrev Casey Holzer <notifications@github.com>:
