### ISSUE TITLE
How to add or remove new items from the selectpicker from jquery?

### ISSUE THREAD

**Issue by MercedeX** [silviomoreto/bootstrap-select#1767]
I have to create cascading drop-downs in a certain app. Both the drop-downs are select pickers. When the value of one drop-down is changed, I have to repopulate the items in select picker, which I retrieve through AJAX/Jquery. 

However, when I looked into the rendered code It seemed to be using a mix of ul,li, ,divs etc.  How can I update the select picker from the client side? Kindly guide me or if it's mentioned in the documentation somewhere I missed?

**Comment by caseyjhol** [comment]
Update the options in the select itself, and then simply call `$('#selectID').selectpicker('refresh')`.
