### ISSUE TITLE
Question - How can I get the selected values of a multiple selectpicker?

### ISSUE THREAD

**Issue by Wuaner** [silviomoreto/bootstrap-select#1769]
I done my work with this js framework, it is a awesome framework btw.

But I found I dont know how to retrieve the selected values of a multiple-selected selectpicker, LOL.

This is just a question, not a bug. sorry ask question here.

Thanks.

**Comment by caseyjhol** [comment]
Underneath bootstrap-select is still a regular HTML select, so you would still use normal methods to retrieve the value.

```js
$('select').val();
```
