### ISSUE TITLE
Sample to work with ReactJS

### ISSUE THREAD

**Issue by iphonic** [silviomoreto/bootstrap-select#1774]
Hello, the component looks promising, thanks for it. I want to use it with **reactjs** it looks like the component can be used with reactjs, but I am not able to make it work, a simple sample how to use it with reactjs will greatly help.

I am adding my code which I am trying to use to make it work below

```
import React,{Component} from 'react';
import ReactDOM from 'react-dom';
import Select from 'bootstrap-select';

class SelectSample extends Component{

render(){
    return (
        <div>
          <Select className="selectpicker">
            <option>Hello</option>
          </Select>
        </div>
    );
  }
}

ReactDOM.render(
    <SelectSample/>
  , document.getElementById('container')
);
```

When I run this, I get following error

![screen shot 2017-08-03 at 11 53 00 pm](https://user-images.githubusercontent.com/5745637/28936993-023f69ba-78a7-11e7-9f5f-f8c12226d919.png)

**Please Help!! Thanks.**

**Comment by caseyjhol** [comment]
I don't have a lot of experience with ReactJS - this is a question you'd be better off asking on StackOverflow.
