### ISSUE TITLE
bootstrap-select and bootstrap v4.0.0-beta

### ISSUE THREAD

**Issue by aeont** [silviomoreto/bootstrap-select#1785]
bootstrap 4 now beta https://github.com/twbs/bootstrap/releases.

**Comment by caseyjhol** [comment]
Thanks - please subscribe to #1135.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
