### ISSUE TITLE
Select's overflow issue on Modal Dialog

### ISSUE THREAD

**Issue by ypk** [silviomoreto/bootstrap-select#179]
for the sake of an argument lets assume that I have an object which holds the ID, and option's values and texts

```
myHTML += '<div class="form-horizontal">';
myHTML += '<div class="control-group">';
myHTML += '<label class="control-label" for="'+inputID+'">'+labelText+'</label>';
myHTML += '<div class="controls">';
myHTML += '<select id="'+inputID+'">';
for(x in inputOptions){
    selectHTML += '<option value="'+x+'">'+inputOptions[x]+'</option>';
}
myHTML += selectHTML;
myHTML += '</select>';
myHTML += '</div>';
myHTML += '</div>';
myHTML += '<script type="text/javascript">$("#'+inputID+'").selectpicker({style: "btn-danger"});</script>';
myHTML += '</div>';
```

I appended myHTML to Modal body to display the dropdown in modal dialog.

But The drop down doesn't appear properly in Modal as it overflows and creates a scroll bar to scroll down to see rest of options.

I've added both style="overflow:hidden;" and data-container="body" to div and select respectively, But when I do that, the select vanishes completely.

How do I make sure that the drop down pops out of the modal and not inside the modal?

---

I believe that this issue is causing by modal's "overflow-y: auto;" property. I've overridden this by hard coding "overflow: hidden" into the div. It still doesn't solve anything..

**Comment by pramod-vishwakarma** [comment]
simple if you using bootstrap modal than you need to remove tabindex="-1" 
in place of this
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
paste
<div class="modal fade" id="exampleModal"  role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
