### ISSUE TITLE
Bootstrap 4 beta issue when data-container set to body

### ISSUE THREAD

**Issue by Juanllb76** [silviomoreto/bootstrap-select#1792]
Hello, 

I'm getting an error when setting data_container = "body".
"Uncaught TypeError: Cannot read property 'jquery' of undefined"

I'm using bootstrap 4 beta and jquery v1.2.3.
Before, with bootstrap alpha this error didn't show.

@Html.DropDownListFor(model => model.Data, Model.DataSel, new { @class = "form-control selectpicker", data_container = "body" })

Any ideas?

**Comment by caseyjhol** [comment]
Not sure. I'm still working on implementing Bootstrap 4 beta support. It will be available in v1.13.0 (currently in alpha). Keep your eyes peeled for updates, and follow #1135.

**Comment by jmchauv** [comment]
Has this been resolved? I am running into the same problem. Thanks!

**Comment by ko06** [comment]
hi, I am also waiting for the solution

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
