### ISSUE TITLE
Select element not displaying in Angular app

### ISSUE THREAD

**Issue by tylerlaberge** [silviomoreto/bootstrap-select#1796]
I am trying to use bootstrap-select with an Angular application and I cannot get it to work. The select element is not visible on the page after giving it the "selectpicker" class. I can see from inspection that "display: none" is being set.

Plunker: https://embed.plnkr.co/rmzCBq2d6gJaYOHfDQYo/

![select-hidden](https://user-images.githubusercontent.com/16872788/30000303-02d5f952-9035-11e7-96e3-04ee68c78de9.jpg)

I have tried calling $("select").selectpicker() in the ngAfterViewInit method but it doesn't seem to solve the issue. 

bootstrap: v3.3.7
bootstrap-select: v1.12.4
jquery: v3.1.1
angular: v4.1

**Comment by jadestrong** [comment]
Did you find the reason? I sometimes have this error when ajax not return a correct select options, but i have a default option inside select element, so why it doesn't display it??

**Comment by ninethug** [comment]
How did you do it using angular4 ?

**Comment by pawelchmara** [comment]
1. In index.html you can add all needed scripts:  jQuery, Bootstrap, Bootstrap-select.
2. Add select in html, for example:

```
<select #paymentMethodRef id="paymentMethod" name="paymentMethod" [(ngModel)]="orderForm.paymentMethod" class="selectpicker form-control" title="Payment method"  i18n-title="@@orderFormPaymentMethod" data-style="btn-light">
<option *ngFor="let item of paymentMethodEnum | enumKeys" value="{{item.key}}">{{item.value}}</option>
</select>
```

3. Init selectpicker in component:

```
declare var $: any;
...
@ViewChild('paymentMethodRef') private paymentMethodRef: ElementRef;
...
public ngAfterViewInit(): void {
    $('select.selectpicker').selectpicker({
      style: 'btn form-control btn-sm',
    });
  }
```

4. Set value:

`$(this.paymentMethodRef.nativeElement).selectpicker('val', PaymentMethod.PaymentMethod_Cash);`

5. Get value:

`$(this.paymentMethodRef.nativeElement).val()`

6. Set change event callback:

`$(this.paymentMethodRef.nativeElement).on('changed.bs.select', this.onPaymentMethodChange)`

**Comment by tylerlaberge** [comment]
@pawelchmara, thanks for the detailed response, this helps.
