### ISSUE TITLE
Boostrap select is not working with Bootstrap 4.0 Beta version

### ISSUE THREAD

**Issue by tejashapani** [silviomoreto/bootstrap-select#1797]
Hi All,

The Bootstrap select is not showing options when clicked. Showing a blank container without any option.
See this: 
![bs](https://user-images.githubusercontent.com/13566246/30027670-9092ebc2-919f-11e7-9eb4-b68d21dd576c.png)

I am getting issue with Bootstrap select (v1.12.4) and Bootstrap latest version 4.0 (Beta release).
but after all research & debug i could not get any solution.

Is there any solution to this issue?

I appreciate any help on this.

Thanks
Tejas

**Comment by faesin** [comment]
See #1135

**Comment by tejashapani** [comment]
Hello @faesin ,

Thanks for your reply.

I checked that PR but i could not understand what is the issue with boostrap select.
Can you please explain?

I also noticed that i am getting JS error on console:
index.js:38 Uncaught TypeError: Cannot read property 'jquery' of undefined

Where index.js belongs to popper.js i think.

Thanks

**Comment by tejashapani** [comment]
Hi @faesin ,

After reviewing the comments, i am able to manage the boostrap select now.

but i found there are some options which are not working with BS4.
For example, 
```
jQuery('.selectpicker').selectpicker({
        container: 'panel-body',
        size: 5
});
```
This options are not working. Also FYI i am using <optgroup> for select box.
```
<select class="selectpicker2">
   <optgroup label="PHONES">
      <option value="Mobile" data-icon="fa-mobile">Mobile</option>
      <option value="Main" data-icon="fa-phone">Main</option>
      <option value="PPersonal" data-icon="fa-phone">Personal</option>
      <option value="Business" data-icon="fa-phone">Business</option>
      <option value="iPhone" data-icon="fa-mobile-phone">iPhone</option>
      <option value="Fax" data-icon="fa-fax">Fax</option>
   </optgroup>
</select>
```

Hope to find some solution soon for this option.

**Comment by botularius** [comment]
+1

**Comment by caseyjhol** [comment]
Bootstrap 4 support is a work in progress. Please search next time.

**Comment by arpitux** [comment]
Is it fixed? I have the same issue.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by spyter** [comment]
I am having issues compiling the scss file for bootstrap-select 1.13.0-beta.

Line 78 needs to be border-color: **$**color-green-success; instead of border-color: **@**color-green-success;

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Comment by TamizhJayapal** [comment]
I have a problem like that.
The field did not shown when i am click the option in multiselect. 

Any one can suggest to me?

**Comment by McFcologne** [comment]
I just get: "Uncaught TypeError: Cannot read property 'Constructor' of undefined"
