### ISSUE TITLE
Virus / Spam included in minified js file.

### ISSUE THREAD

**Issue by ericwra** [silviomoreto/bootstrap-select#1810]
There is a script element that attempts to get created that points to https://horux.online/x.php within the minified js file.

**Comment by danielekbom** [comment]
I noticed the same problem.

**Comment by ericwra** [comment]
I've forked and created a pull request that removes the malicious code. 

https://github.com/silviomoreto/bootstrap-select/pull/1813

**Comment by oliviernt** [comment]
The github page (http://silviomoreto.github.io/bootstrap-select/) also includes the version containing the horux.online URL.

**Comment by raderio** [comment]
How this code was accepted?

**Comment by oliviernt** [comment]
The commits including it are from @silviomoreto ... maybe his account got compromised?

**Comment by silviomoreto** [comment]
Actually I have accepted the pull request from eric to remove the script.

I will look to see who added this code in our library and change my password as well.

Oliver, dis you found the commit adding this malware?

Best

**Comment by kozec** [comment]
> dis you found the commit adding this malware?

Here you are: https://github.com/silviomoreto/bootstrap-select/commit/6a4d98ca2e507ce8d8a871656931d7d31326082c

**Comment by kozec** [comment]
> dis you found the commit adding this malware?

Here you are: https://github.com/silviomoreto/bootstrap-select/commit/3211b3b90da119fe47a5f1192ae356c6cdd33fdc

**Comment by oliviernt** [comment]
There actually were multiple commits adding/removing the malicious code
 
![clipboard - september 29 2017 8_40 am](https://user-images.githubusercontent.com/162120/31018261-a84387d2-a52b-11e7-83fb-bac5082e31e5.png)

**Comment by silviomoreto** [comment]
Wow!! I think my github account is compromised.
Sorry guys, I will change my password again! (just in case...)

I think just the min file was compromised.
If you see anything else that must be changed, please address me on the issue or by email.

I think by now it is solved, so I will close the issue by now.

**Comment by oliviernt** [comment]
I'd also recommend using MFA (may be activated here -> https://github.com/settings/security)

**Comment by silviomoreto** [comment]
Sure! Doing that right now

**Comment by SGOrava** [comment]
i suggest to sign commits with GPG https://help.github.com/articles/signing-commits-with-gpg/

**Comment by caseyjhol** [comment]
@silviomoreto When you get a chance, it'd be great if you could respond to my email regarding transferring ownership of bootstrap-select over to me.
