### ISSUE TITLE
What about support Bootstrap 4?

### ISSUE THREAD

**Issue by thiensubs** [silviomoreto/bootstrap-select#1822]
How about your future of this library with Bootstrap 4?

**Comment by krystyna93** [comment]
Yes, I would like to know also.

**Comment by ionesculiviucristian** [comment]
It has the same pace as the bootstrap team... maybe next year will have them both working

**Comment by caseyjhol** [comment]
Working on getting this implemented. It's somewhat tricky to ensure it will work with both Bootstrap 3 and 4 with minimal changes to the code. Follow #1135 for updates.

**Comment by krystyna93** [comment]
Well, until the compatible version is released by the Silvio gang, I am
using the heimrichannot/bootstrap-select alternate version for now, which
seems to be working satisfactory.
Thanks for the update, Casey.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
