### ISSUE TITLE
Malicious script still being loaded on Github page

### ISSUE THREAD

**Issue by oliviernt** [silviomoreto/bootstrap-select#1824]
The malicious script that was recently removed (Issue https://github.com/silviomoreto/bootstrap-select/issues/1810) from the minified version of the plugin is still being included on the Github page of the project.

See: http://silviomoreto.github.io/bootstrap-select/dist/js/bootstrap-select.min.js

Pull request removing the malicious part: https://github.com/silviomoreto/bootstrap-select/pull/1819

**Comment by caseyjhol** [comment]
I re-deployed the docs and they no longer include the malicious code.
