### ISSUE TITLE
Bootstrap 4 - Selectpicker Dropdown/Dropup tiny

### ISSUE THREAD

**Issue by Optimaximal** [silviomoreto/bootstrap-select#1843]
I've got the following code populating a select box from a mysql table...

```
<select class="form-control selectpicker" id="nominal" name="nominal" data-size="5" >
<?php
$nc_sql = "SELECT * from nom_code order by id";

$nc_result = $link->query($nc_sql) or die(mysqli_error($link));

while($row_nc = mysqli_fetch_array($nc_result))
 {
print '<option value='.$row_nc['id'].'>'.$row_nc['fulltext'].'</option>';
 }
?>
</select>
```

But this is the result...
![screenshot 2017-10-24 12 42 30](https://user-images.githubusercontent.com/4669242/31941243-0dc062ec-b8b9-11e7-8568-a8e757a3093b.png)

I know Bootstrap 4 is in Beta and they've changed a bunch of code, but it seems somewhere the height is being overridden to just 18px. Is this an easy fix?

**Comment by Optimaximal** [comment]
Nevermind, found the discussion about Bootstrap 4 not being supported yet.

**Comment by sdq99** [comment]
bootstrap 4 is not supporting selectpicker, right?

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
