### ISSUE TITLE
Does not work near bottom edge

### ISSUE THREAD

**Issue by sstyle** [silviomoreto/bootstrap-select#1846]
Bootstrap 3.3.7, jquery 1.11.3, bootstrap-select 1.13.0 alpha, google chrome (last one)

If select is near bottom edge it does not work with error:

> Uncaught TypeError: Cannot read property '0' of undefined
    at d (bootstrap-select.min.js:sourcemap:7)
    at bootstrap-select.min.js:sourcemap:7
    at dispatch (jquery.js:4670)
    at r.handle (jquery.js:4338)

Looks like it needs a free space below select, because height of select always equals distance to the bottom edge.

Video: https://youtu.be/pBSvKzmMx20

![bug](https://user-images.githubusercontent.com/6489964/32054728-1b48de02-ba68-11e7-9877-0afc79a40b1b.jpg)

**Comment by caseyjhol** [comment]
This should be resolved in [v1.13.0-beta](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta).
