### ISSUE TITLE
Able to hide selectpicker

### ISSUE THREAD

**Issue by bouzafr** [silviomoreto/bootstrap-select#185]
Sorry if this is already in place. But I can't seem to be able to hide the select no matter what I do. Is there a way to do this?

**Comment by hilyin** [comment]
Would it be possible to also detect when initing selectpicker, if the select element is ```display:none```? I am running into an issue where I want to use the selectpicker, but not on initial load. So I have the select with ```display:none```, but selectpicker still displays the element when initialized.
