### ISSUE TITLE
The 'destroy' method remove the whole 'select' tag

### ISSUE THREAD

**Issue by acharkizakaria** [silviomoreto/bootstrap-select#1863]
Why the `destroy` method remove the whole select tag : 

`$('.selectpicker').selectpicker('destroy');`

The expected behaviour is that the destroy just leave the simple select tag, when the detroy now remove the select at all and leave just the blank there.

**[Sample Fiddle](http://jsfiddle.net/z_acharki/nk2u3ckv/4/)**.

Thanks in advance.

**Comment by caseyjhol** [comment]
You're using an old version of bootstrap-select. This was fixed in v1.9.4.
