### ISSUE TITLE
I included every file, nothing is showing up

### ISSUE THREAD

**Issue by denigada** [silviomoreto/bootstrap-select#1864]
I just use the example code and nothing shows up on the website. I have the js file right before </body> and I have css files on top. It just hides the select object, I can see nothing. Can someone please help me

**Comment by grotup** [comment]
Which code example do you use ?

**Comment by maxivak** [comment]
I have the same problem.
I am using Bootstrap 4.0.0-beta.2 and I have this code.

and I see empty SELECT list.

```
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>

<!-- (Optional) Latest compiled and minified JavaScript translation files -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/i18n/defaults-*.min.js"></script>


<select class="selectpicker">
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Relish</option>
</select>
```

**Comment by maxivak** [comment]
I am using the following js libraries:

```
"font-awesome": "4.7.0",
    "bootstrap": "4.0.0-beta.2",
    "jquery": "3.2.1",
    "popper.js": "1.12.4",
    "bootstrap-select": "1.12.4"
```

maybe it doesn't work because of jQuery 3 which is mentioned in issues #1832, #1459 .

**Comment by blackthorne11** [comment]
Same issue here.  I'm also using Bootstrap 4. beta 2 and jquery 3.2.1  
I copied the basic example of:

<select class="selectpicker">
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Relish</option>
</select> 

but the select list shows as empty

**Comment by caseyjhol** [comment]
Bootstrap 4 is not yet supported, but will be in an upcoming update.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
