### ISSUE TITLE
data-size attribute not work on bootstrap 4 current version

### ISSUE THREAD

**Issue by andryshok** [silviomoreto/bootstrap-select#1865]
When use attribute data-size="5" - drop down list is empty on bootstrap 4

**Comment by caseyjhol** [comment]
Bootstrap 4 is not yet supported. See #1135.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Comment by andryshok** [comment]
Thanks !
