### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by HamedFathi** [silviomoreto/bootstrap-select#1870]
Please support the latest version of Bootstrap 4.
thanks

**Comment by krystyna93** [comment]
@HamedFathi and others, here is a compatible version that you can use in the meantime:
https://github.com/heimrichhannot/bootstrap-select

Its the same but has been modified for compatibility, and it functions perfectly in bootstrap 4 beta. I am using this in my current project, and it all works fine.

**Comment by caseyjhol** [comment]
Duplicate of #1135.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
