### ISSUE TITLE
bootstrap-select doesn't look bootstrap

### ISSUE THREAD

**Issue by abelardolg** [silviomoreto/bootstrap-select#1875]
Hi,

I run the npm installation process.

I copied the example showed below of these lines:
```
<select class="selectpicker">
  <option>Mustard</option>
  <option>Ketchup</option>
  <option>Relish</option>
</select>
```

but this component doesn't appear bootstrapped. In fact, this component is hidden. I have got to show it inspectioning this element and removing the "display:none!important!" style but it doesn't appear bootstrapped but as normal select. 

Why does it happen? What's wrong?

Please, provide a hello world doc containing precise instructions to show this select as is showed at your examples.

Tested on Windows 7@NPM 5.3.0

Best regards.

**Comment by caseyjhol** [comment]
It sounds like bootstrap-select.js is not being included (or is included in the wrong order). Can you post the order the javascript files are being loaded?
