### ISSUE TITLE
data-live-search="true" not working in Bootstrap 4

### ISSUE THREAD

**Issue by major697** [silviomoreto/bootstrap-select#1878]
Hello, anyone of you has solved the problem with the class data-live-search = "true"? The class does not work in bootstrap 4. It does not display the field for typing and the list of options

**Comment by caseyjhol** [comment]
Bootstrap 4 is not yet supported, but it will be available in an upcoming release. Please follow #1135 for updates

**Comment by vidalive** [comment]
same question here! :) Is it solved yet?

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!

**Comment by kinoli** [comment]
live search shows up but it doesn't do anything when you type in the input field.

**Comment by Izzzzy** [comment]
> live search shows up but it doesn't do anything when you type in the input field.

For anyone coming across this, a solution that worked for me is [here](https://github.com/creativetimofficial/ct-material-kit-pro/issues/86#issuecomment-381541004)

**Comment by Myname10** [comment]
Hey I installed boostrap-select@1.13.17 but still does not show the search box

**Comment by caseyjhol** [comment]
@Myname10 Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case (you can use our preconfigured [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/)), and report back with your link.
