### ISSUE TITLE
Dynamically added dropdown as selectpicker

### ISSUE THREAD

**Issue by matthbon** [silviomoreto/bootstrap-select#1880]
Hi there,

I have a page where i have some kind of query builder. That is using 2 selectpickers to choose where to filter on and the condition.

        <div class="col-md-2 no-margin no-padding-left">
            <select name="search_key[]" class="selectpicker search-key" data-width="100%" data-style="btn-success" data-max-options="1">
                <option value="product_name">Product Name</option>
                <option value="product_ean">EAN</option>
                <option value="product_sku">SKU</option>
            </select>
        </div>

        <div class="col-md-2 no-margin">
            <select name="search_condition[]" class="selectpicker search-condition" data-width="100%" data-style="btn-default" data-max-options="1">
                <option value="sw">Starts with</option>
                <option value="ew">Ends with</option>
                <option value="co">Contains</option>
                <option value="ex">Exact</option>
            </select>
        </div>`
This works perfect.
But when i press a button to add a filter (an ajax call which gets this template) the selectpickers are not showing.
I tried to do `$(".selectpicker").selectpicker('refresh');`
But no luck.

Any idea how i can enable dynamically created select boxes as an selectpicker?

Thanks in advance.

Matthijs

**Comment by Art4es** [comment]
Do you appending bootstrap.js with this template?

**Comment by matthbon** [comment]
No not in the template itself. I do an ajax call and append the template to a div. On the page itself the where it is appended the bootstrap.js is loaded.

**Comment by durr04** [comment]
After completing your ajax call, You might be appending the option to the select list conditionally. After that only you need ton use following code.
`$(".selectpicker").selectpicker('refresh')`

If you use it before the option of the select list getting updated its of no use. You need to do after rendering the options conditionally. That would work for you.

**Comment by matthbon** [comment]
Ok it is working now I already did `$(".selectpicker").selectpicker('refresh');` this after appending the html. But had to add another class like `filter-selector` and then `$(".filter-selector").selectpicker('refresh');` works. Thanks.

**Comment by abdullah195** [comment]
I have same problem but my problem is resolved with
$(".selectpicker").selectpicker('refresh')

**Comment by ravi-kant-alok** [comment]
> After completing your ajax call, You might be appending the option to the select list conditionally. After that only you need ton use following code. `$(".selectpicker").selectpicker('refresh')`
> 
> If you use it before the option of the select list getting updated its of no use. You need to do after rendering the options conditionally. That would work for you.

Thanks
