### ISSUE TITLE
Bootstrap 4 does not work list.

### ISSUE THREAD

**Issue by uaKalwin** [silviomoreto/bootstrap-select#1883]
Hello, there was a problem.
Bootstrap 4.0 does not work list.
When you click, only the search is opened. Who knows why? How to fix it?

**Comment by major697** [comment]
You must wait, Bootstrap Select for Bootstrap 4 is in preparation

**Comment by uaKalwin** [comment]
Okey.

**Comment by HiNeX** [comment]
As an alternative, we develop a plug-in for bootstrap 4
https://github.com/hardskilled/bootstrap-hardskilled-extend-select

**Comment by srikrishnacj** [comment]
@HiNeX Thank you. It works well

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
