### ISSUE TITLE
Using events

### ISSUE THREAD

**Issue by picks44** [silviomoreto/bootstrap-select#1887]
Hi,
I can't figure out how to fire the `changed.bs.select` event on my picker...
Here is my code 
```
<div class="form-group">
    <label class="control-label required" for="contact_country">Country</label>
    <span class="required" title="This field is required">*</span>
    <select id="contact_country" name="contact[country]" required="required" class="selectpicker form-control" data-live-search="true" data-container="body" data-size="10">
        <option value="" selected="selected">Choose from the list</option>
        ...
    </select>
<div>
```

And the JS, [following the doc](https://silviomoreto.github.io/bootstrap-select/options/#events)
```
$("select[id$='_country']").on('changed.bs.select', function (e, clickedIndex, newValue, oldValue) {
    alert(newValue);
});
```

Can anyone help?

**Comment by epoxa** [comment]
Are you sure bootstrap-select.js is loaded at the moment you attach event listener?

**Comment by fskale** [comment]
Why not refering the the id stated in the doc ?

$("#selectpicker").on('changed.bs.select', function (e, clickedIndex, newValue, oldValue) {
    alert(newValue);
});

**Comment by caseyjhol** [comment]
It looks like you're probably setting the variable incorrectly for the select ID.
