### ISSUE TITLE
Button text is centered in Bootstrap 4 beta 2

### ISSUE THREAD

**Issue by bascloud61** [silviomoreto/bootstrap-select#1895]
For bootstrap 4 beta 2 compatibility, please change

filter-option pull-left

on line 503 of bootstrap-select.js to

filter-option float-left"

since pull-left is no longer used in BS4

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
