### ISSUE TITLE
Select picker issue on Microsoft Edge

### ISSUE THREAD

**Issue by karthiksubramaniam** [silviomoreto/bootstrap-select#1907]
Picker not refreshing after adding a new value dynamically.

Works on Chrome & firefox (OS: Windows 10).

Steps:
1.Adding new option to select (selected:true)
2.Refresh the dropdown by .selectpicker('refresh');

Js Fiddle Link: https://jsfiddle.net/karthiksubramaniam/ddz7zggo/4/

**Comment by caseyjhol** [comment]
I could sometimes get this to work, other times it wouldn't. In any case, you're setting the selected property incorrectly (should be using `prop` instead of `attr`, which is probably the source of your problem. This should work better:

```js
$(function() {
  $('#city').selectpicker();
  $('#newCity').click(function() {
    var newText = $('#newText').val();

    $("#city")
      .append("<option value=\"" + newText + "\">" + newText + "</option>")
      .val(newText)
      .selectpicker('refresh');
  });
});
```
