### ISSUE TITLE
Upgrade jQuery to 3.0?

### ISSUE THREAD

**Issue by rajadain** [silviomoreto/bootstrap-select#1908]
Hello,

GitHub is reporting one of our projects as insecure because we were on an older version of jQuery, and so have been upgrading it to the latest 3.3.1. During the upgrade, I noticed that bootstrap-select is using [the insecure 1.12.4](https://david-dm.org/silviomoreto/bootstrap-select):

![image](https://user-images.githubusercontent.com/1430060/35758405-e0fbdce0-0841-11e8-9c73-6eaa38111cf4.png)

Is a jQuery upgrade planned? If so, what is the tentative timeline?

**Comment by ionesculiviucristian** [comment]
Too bad that this awesome project is not keeping the pace with the latest version of bootstrap.

**Comment by ataft** [comment]
@rajadain bootstrap-select has a minimum requirement of jQuery 1.8, but the latest version of jQuery 3.3.1 works fine with bootstrap-select. FYI - bootstrap-select is version 1.12.4, it's not using jQuery 1.12.4.
