### ISSUE TITLE
DropDown in NavBar not visible

### ISSUE THREAD

**Issue by clempe** [silviomoreto/bootstrap-select#1909]
I'm trying to use the selectpicker in the navbar. 
When i click on selectpicker, the dorpdown field opens, but is not visible. 

I'm using Bootstrap v4 and jQuery 3.3.1
Here is an [example](http://jsfiddle.net/clempe/brzu9hh4/32/)

**Comment by mdigi** [comment]
Bootstrap-select does not currently support Bootstrap v4.

**Comment by krahamath** [comment]
Yes - bootstrap-select will added support b4 very soon

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
