### ISSUE TITLE
Large number of option

### ISSUE THREAD

**Issue by hnahoulder** [silviomoreto/bootstrap-select#1911]
Hello,

I'm using bootstra-select with a large number of options (about 30 000 options), so when I initialize it's very slow and when I do livesearch, it's work very slow also. Do you have any idea to run it fast? My list of options is from AJAX call.

**Comment by caseyjhol** [comment]
The performance issues with large selects have been addressed in v1.13.0, currently in beta. I've moved development of this plugin to a new repo, and v1.13.0-beta can be downloaded here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta.
