### ISSUE TITLE
It doesn't work in bootstrap4.0, Is there any solution to it?

### ISSUE THREAD

**Issue by youngsherlee** [silviomoreto/bootstrap-select#1912]
It work in bootstrap4.0 is like this:
![2018-02-09 5 49 12](https://user-images.githubusercontent.com/14268156/36021705-96817f82-0dc1-11e8-9ef3-171f6a307ed0.png)

**Comment by cocowalla** [comment]
看看 #1135 
我们得等!

**Comment by HiNeX** [comment]
U can use https://github.com/hardskilled/bootstrap-hardskilled-extend-select

**Comment by caseyjhol** [comment]
Bootstrap 4 support has been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on.

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
