### ISSUE TITLE
Change Event

### ISSUE THREAD

**Issue by oblogic7** [silviomoreto/bootstrap-select#216]
I need to monitor for value changes on a multiple select field.  I can listen for the event on the actual select element, but that change event fires each time an item is selected.  However, this is not the behavior I need. 

Are any events fired when the bootstrap-select is closed?  This would allow several selections to be made with a single event that can be used to trigger an action with the final value.  Possible?

**Comment by benissimo** [comment]
Thanks @caseyjhol -- your suggestion works.
It'd be nice if bootstrap-select offered a cleaner way to get at the select element.
This feels like we're peeking behind the curtain:

```js
.data('selectpicker').$newElement;
```

**Comment by caseyjhol** [comment]
See commit 541d9a06af6fc69161156a78cdb081567f2a3b03

**Comment by xennygrimmato** [comment]
I'm a new Javascript/jQuery  user and I am facing this same issue at the moment.
@caseyjhol - https://github.com/silviomoreto/bootstrap-select/issues/216#issuecomment-33105746 does not work for me.
I want to trigger an event as soon as the the bootstrap-select is closed.
My Code snippet:
```
$('#multiselect').data('selectpicker').$newElement.on('hide.bs.dropdown', function() {
                alert('hide');
});
```
What is the current way to do this, after https://github.com/silviomoreto/bootstrap-select/commit/541d9a06af6fc69161156a78cdb081567f2a3b03 ?

**Comment by sebkoller** [comment]
```javascript

**Comment by sebkoller** [comment]
@xennygrimmato the current way of doing this is:
```javascript
$('#multiselect').on('hide.bs.select', () => alert('hide'));
```

**Comment by xennygrimmato** [comment]
Thanks @sebkoller !

**Comment by nguoirom** [comment]
My simple solution:

`	$('[name^=selectP_fabricColor], [name^=selectP_fabricPattern]').parent('div').on('hidden.bs.dropdown', function(){
		getOptions(currentA)
	});`

**Comment by tmartin2089** [comment]
`  $('#selectpicker').on('shown.bs.select', function(){
    console.log('its shown son!')
  })`

Works like a dream. Thanks @sebkoller, wish I had scrolled to the bottom instead of spending an hour googling :)

**Comment by turigeza** [comment]
I was looking for a way to only submit data to the server once the multiselect has been closed but only if it was changed. The solution is fairly trivial so I leave it here for others.

Sure a 'changedhide.bs.select' event would be handy but for now:

```

var filterChanged = false; 

$('.selectpickers').selectpicker({
    // selectpicker options
}).on('changed.bs.select', function (e) {
    filterChanged = true;
}).on('hide.bs.select', function (e) {
    if(filterChanged){
        filterChanged = false;
        // send data to server or what ever :)
    }
})
```

**Comment by satish1020** [comment]
I am having a select picker in my html page as below which will  select multiple values in drop down.I am having difficult time in capturing the selected values in the page.viewmodel.js of knock out.Can some one help me out on how to capture multiple values

     <td style="border-top: none">
                                <h4>Name:</h4>
                                <select id="selName" class="someNameselectpicker input-small pull-left" data-live-search="true" multiple data-actions-box="true" data-bind="options: vm.demo.searchservicerequest.names(),
                                                        value: selectedRequester,
                                                        selectpicker: {  width: '350px' },
                                                        optionsValue: function(item) {
                                                            return item;
                                                        },
                                                        optionsText: function(item) {
                                                            return item.FirstName+', '+item.LastName;
                                                        },
                                                        optionsCaption: ui.selectCaption"></select>
                            </td>
