### ISSUE TITLE
Respond to Keyboard

### ISSUE THREAD

**Issue by digerata** [silviomoreto/bootstrap-select#220]
This is a great little lib here.  It shows a lot of promise, nice work!

One thing I noticed.  Selectpicker should mimick the same keyboard functionality in real form elements.  That is:
- Allow for focus via Tab key
- Allow for option to be selected by typing in letters/numbers/etc.  Follow native feature of typing mi to move past Maine to Michigan.
- Allow for option to be selected by arrow keys

It looks like arrows and letters can be used to select, but only if you first select an option with the mouse and the selectpicker still has focus.  Further, it is outlining the selected option instead of actually selecting the option.

**Comment by cristiangiagante** [comment]
Someone know if the issue with only 1 letter was fixed in safari to live search with a multiple select list?
It's not working in Safari 11 to me.

**Comment by Jogai** [comment]
@tbbstny 's code didnt work for me with the latest version. Based on his solution I came up with:

	$(document).ready(function () {

		$("body").on("keypress", ".bootstrap-select.open", function (e) {
			e.preventDefault();
			//fix from https://github.com/silviomoreto/bootstrap-select/issues/220#issuecomment-35531742
			var $options, $select, ctrl = this;
			ctrl.buffer = (ctrl.buffer || "");
			$select = $(ctrl).find("select");
			$options = $select.find("option");

			// If capturing, keep capturing
			if (ctrl.capture) {
				clearTimeout(ctrl.capture);
			}

			// capture keystrokes; reset capture after 1sec.
			ctrl.capture = window.setTimeout(function () {
			ctrl.buffer = "";
			ctrl.capture = null;
			}, 1000);

			// Use captured buffer to filter <options> of native select
			// select first and trigger change & refresh
			ctrl.buffer += String.fromCharCode(e.which);

			var searchVal = ctrl.buffer.charAt(0).toUpperCase() + ctrl.buffer.slice(1);
			var opt = $select.find('option:contains('+searchVal+')');

			$select.selectpicker("val", opt.val());
			return false;
		});
	});
