### ISSUE TITLE
Data & Default

### ISSUE THREAD

**Issue by Cartman34** [silviomoreto/bootstrap-select#281]
Thank you for this great library.

I am currently using the version 1.2.0, the last one, and I got some trouble with data and defaults for options, the data I gave are not used... so i looked for the reason and I find it... data attribute's name is set to lower case (jQuery behavior ?!), so "data-noneSelectedText" sets the data "noneselectedtext" and not "noneSelectedText" (behavior on last Firefox with last version of jQuery lib).

The solution is to modify the lib to use only lower case options.

Example:
<select class="select" data-noneSelectedText="Aucun choix disponible"></select>

Data list of this <select> :
Object { noneselectedtext="Aucun choix disponible"}

Options finally used by bootstrap-select :
Object { size="auto", selectedTextFormat="values", noneSelectedText="Nothing selected", more...}

**Comment by srikanthpullela** [comment]
i have data like this in Html page 
<select id="done" class="selectpicker" multiple data-done-button="true">
    <option value="Apple">Apple</option>
    <option value="Banana">Banana</option>
    <option value="Orange">Orange</option>
    <option value="Pineapple">Pineapple</option>
  </select>
by calling API now i got data from preselected values from server , so i want to show to show preselected values.

**Comment by apmeena** [comment]
$("select option[value='Banana']").attr("selected","selected");

**Comment by MartinP7r** [comment]
> $("select option[value='Banana']").attr("selected","selected");

This selects the option, but is not reflected in the title of the select element.
