### ISSUE TITLE
Prohibitively slow render performance with large select elements

### ISSUE THREAD

**Issue by loganfuller** [silviomoreto/bootstrap-select#291]
I've found that the render performance of this library tends to be prohibitively slow for select elements with large numbers of options. From my tests, the "setSelected" and "setDisabled" functions contribute to over 90% of the render time. 

Current tests show that rendering takes 40ms per select tag on average, but often takes 250ms+ to render when using larger select elements (196 options for a country dialog).

**Comment by cifren** [comment]
Just a question about this issue, why this awesome from @pembo13 hasn't been integrated into the master, I tried it and it worked very well on my test, saved a lot of loading time !! Still not enough but good enough for the first 2 selects used on a single page.

I am loading more than 10 selects of 1600 items on one page, We should think about something lighter :)

**Comment by Khrysller** [comment]
+1

**Comment by caseyjhol** [comment]
@cifren It was implemented...back in January of 2014.

**Comment by cifren** [comment]
Sorry, maybe I am wrong but I tried to find this in the master branch source and nothing than I could see was there. I had to change the code with the one given above and it changed completely the behaviour, not enough but faster.
Anyway, I am sorry I went to the enemy... I used Select2... But thanks for your work and the sharing of this tool :)

**Comment by caseyjhol** [comment]
@cifren https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L746-L758

**Comment by caseyjhol** [comment]
Please try v1.7.0-rc2 and report back.

**Comment by rrajesh145** [comment]
@caseyjhol : I have tried with the recent version but still facing the same issue as  what @loganfuller said.

**Comment by caseyjhol** [comment]
Can you provide me with a JSFiddle or link to an example? What browser/OS are you using? I tested using nearly 1000 cities on Windows 8/Chrome/Firefox and it loads almost instantaneously.

**Comment by rrajesh145** [comment]
@caseyjhol : http://jsfiddle.net/nr54vx7b/88/ , I am using Windows 7 / Chrome Version 43.0.2357.134m

**Comment by caseyjhol** [comment]
That's because you're trying to call `refresh()` every time you add an option. You want to add all of the options first, and then call refresh once outside of the for loop.

http://jsfiddle.net/nr54vx7b/89/

**Comment by rrajesh145** [comment]
Oh Ok Thanks for the help @caseyjhol . Code which you suggested works good .

**Comment by om-sharmahbis** [comment]
https://github.com/silviomoreto/bootstrap-select/blob/master/js/bootstrap-select.js#L746-L758

this plugin is not working for updation or edit???

it doesnt select multiple options which we already selected while editing???

**Comment by szofar** [comment]
seems like this is an issue again in v1.14.0-beta3 for Bootstrap 5 if I follow the step to "Add the selectpicker class to your select elements to auto-initialize bootstrap-select."

If I have 10 options it's fine. If I have 10,000, the browser asks to kill the page.

### version info
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
