### ISSUE TITLE
Make dropdown scrollable with arrow keys after live search

### ISSUE THREAD

**Issue by srimola** [silviomoreto/bootstrap-select#303]
Normally, one is able to scroll through options in a dropdown using their arrow keys and then choose the option with enter. This works in all instances of the selectpicker except when data-live-search = "true", which is when I would definitely expect this feature to work. The user's hands are already on the keyboard, and it is a nuisance to have to transition back to the mouse, especially if one is using multiple screens.

I understand that this is very minor so I would classify it as a feature request. For some reason, I don't see the "Add label" section but I would label this as an enhancement. Thanks in advance!

**Comment by gmsa** [comment]
This is not working anymore

**Comment by tumispro** [comment]
Any updates on this? Is there a workaround perhaps?
