### ISSUE TITLE
Sample on how to get selected vlues

### ISSUE THREAD

**Issue by oscar-pereira** [silviomoreto/bootstrap-select#305]
Hey, how is it that we get the selected values before a submit, I see other multiselect that enabled the Change event to know when selection changed and get the selected options, but how to do it with this plugin.
I really like it but need to know how to get the selected values, also, is it possible that I get the Value of the selected Item and not the Text

**Comment by Taytus** [comment]
var targets = [];
 $.each($(".selectpicker option:selected"), function(){
          targets.push($(this).val());
});
 alert("You have selected the targets - " + targets.join(", "))
