### ISSUE TITLE
check mark on the wrong position

### ISSUE THREAD

**Issue by radova** [silviomoreto/bootstrap-select#309]
Great plugin, thank you!
I think that there is a small  bug (you can see it even in your test file).

In multiple selections, when user selects the first option under the optgroup the checkmark is displayed above the selection, over the optgroup line. Checkmark is displayed correctly for all other options. 
I am getting this on all browsers.

Alex

**Comment by piburglar** [comment]
What was the resolution here?  I am having the same issue.
