### ISSUE TITLE
How to change title?

### ISSUE THREAD

**Issue by frapontillo** [silviomoreto/bootstrap-select#328]
I am trying to change the title of the `select` but changing the HTML attribute `title` does not solve it, neither by consequently calling `refresh`.
Is there any way to achieve this that I'm not aware of?

**Comment by gronostajo** [comment]
Changing title still appears to be broken. Here's [a demo](http://plnkr.co/edit/E8VJulqg3sYMSRXkQqVJ?p=preview) that contains both the method that I expected to work (simply changing title and calling render/refresh) and a workaround.
