### ISSUE TITLE
How to get all selected values for multiple select?

### ISSUE THREAD

**Issue by shang-wang** [silviomoreto/bootstrap-select#333]
Dear all:

Can somebody tell me how can I get the selected values for multiple select? Thanks.

http://silviomoreto.github.io/bootstrap-select/#multiselect

**Comment by eagore** [comment]
can i set default select in multiple select?

**Comment by KingR1** [comment]
@eagore Yes. Check this http://silviomoreto.github.io/bootstrap-select/#methods You can pass array of values into method `val()`

**Comment by eagore** [comment]
Hello Roman;
         Thank you for your help. :D

Thanks,
Archie

**Comment by RAJESHW** [comment]
How do I populate the selected values in multi select?
