### ISSUE TITLE
Uncaught TypeError: Cannot read property 'options' of undefined bootstrap-select.js:582

### ISSUE THREAD

**Issue by raphaelcarlosr** [silviomoreto/bootstrap-select#372]
![image](https://f.cloud.github.com/assets/483708/1515143/a81bb798-4afd-11e3-9148-eb06c53befef.png)

**Comment by dougfarre** [comment]
+1 I have this issue after updating from rails 4.1.8 to 4.2.0.

**Comment by angelxmoreno** [comment]
same issue.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case?

**Comment by universome** [comment]
I had this problem and found the source of it in my case: all my third-party libs were loaded twice (yes, that's awkward). Such a way bootstrap-select was "inited" twice and this broke it up

**Comment by fracz** [comment]
1.12.1 and error is still present

**Comment by EvgenyVetrov** [comment]
+1 same problem

**Comment by ufocruz** [comment]
++1 same problem

**Comment by ufocruz** [comment]
Problem solved on last version

**Comment by KarolMilewski** [comment]
number of the version ? 
1.12.4 same problem

**Comment by maheshBajait2404** [comment]
1.12.2 and error are still present. I used it with nya-bs-select
