### ISSUE TITLE
How to pass options by javascript

### ISSUE THREAD

**Issue by chetanwagh** [silviomoreto/bootstrap-select#42]
Hello,

I faced on question about how to pass an options through javascript like code
  $('.selectpicker').selectpicker({
      btnStyle: 'btn-info'
    });

Please replay

Thank you,
Developer

**Comment by aimflaiims** [comment]
you can find all available options at https://developer.snapappointments.com/bootstrap-select/options/
$(function () {
    $('select').selectpicker({
        liveSearch: true
    });
});
