### ISSUE TITLE
default icon is of glyphicon type

### ISSUE THREAD

**Issue by siciarek** [silviomoreto/bootstrap-select#430]
Default option icon is of glyphicon type, when i use fontAwesome class .glyphiocon does not let my icon to display properly, and I have to remove '.glyphicon' programatically.

Could you, please, remove hardcoded glyphicon class (bootstrap-select.js line 136).

**Comment by ataft** [comment]
Is there a way to do this as a global default? I tried creating a custom default file based off "defaults-en_US.js" with iconBase and tickIcon as defaults, but it did not pick them up...

**Comment by caseyjhol** [comment]
@ataft 

```js
$.fn.selectpicker.Constructor.DEFAULTS.iconBase = 'fa';
$.fn.selectpicker.Constructor.DEFAULTS.tickIcon = 'fa-check';

**Comment by ataft** [comment]
works great, thanks!

**Comment by SavageByte** [comment]
// use bootstrap select picker
    $('.selectpicker').selectpicker({
        style: 'btn-default',
        size: 7,
        iconBase: 'fa',
        tickIcon: 'fa-check',
        showTick: false,
        showIcon: false
    });

I'm trying to no show any icon and this was my test but nothing changes. What have i done wrong?
