### ISSUE TITLE
How can I display a popover on an item when user hovers over it?

### ISSUE THREAD

**Issue by mkschreder** [silviomoreto/bootstrap-select#441]
I would like to display a popover beside an item when user hovers over it. 

How do I do it?

**Comment by 51001624** [comment]
Hello, caseyjhol
I am still having the trouble with showing the info of the hidden text in selectpicker, i want to see the hidden text in option ( becasause my text is very long) when i hover over it. Can you explain me how to do these? Thanks !

**Comment by TCOA** [comment]
What does "$lis" refer to???
