### ISSUE TITLE
Size option not working correctly

### ISSUE THREAD

**Issue by kaelar** [silviomoreto/bootstrap-select#446]
I Initialize my select using:
`$(".selectpicker").selectpicker({ size: 2 });`

This seems to have no effect, it still shows all the items. Once I select an item from the list it seems to update and display the correct number of items (2 in this case)

If i manually call the setSize function, this will work correctly and show 2 items in the list:
`$(".selectpicker").selectpicker({ size: 2 });`
`$(".selectpicker").selectpicker('setSize');`

Also, I noticed calling `$(".selectpicker").selectpicker('refresh')` does not update the size. Is this intended behavior? I'm not sure if I'm doing something wrong here.

**Comment by azhararmar** [comment]
Is there a fix for this? same here, I am using data-content to display in multiple lines, however size does not work, but when I use setSize, it does adjust the size although it is not correctly calculated.

This is tested on:
Operating system: macOS Sierra (10.12.6)
Web browser: Firefox 61.0.2
jQuery version: 3.1.1
Bootstrap version: 3.3.7
Bootstrap selection version: 1.12.4
