### ISSUE TITLE
li rel have the value of the equivalent option

### ISSUE THREAD

**Issue by xyfantis** [silviomoreto/bootstrap-select#451]
Currently the rel attribute of the generated li have no relevance with the value of the equivalent option, it would be nice if that rel had the value of the equivalent option so if you
$(this).selectpicker('val'); 
get the selected values which are the option values 
you can easily get those elements and do whatever you want like call a trigger click on their child anchors e.t.c. 

What do you think?

**Comment by caseyjhol** [comment]
`rel` attribute has been removed.
