### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by sirNemanjapro** [silviomoreto/bootstrap-select#456]
I would like to be able to translate some of the words and expressions in the bootstra-select, for example - "Nothing selected". Is there a chance this could be done?

**Comment by gfdesign** [comment]
Could you give an example how to set it up?
I don't realize how I must to apply it.
Thanks

**Comment by caseyjhol** [comment]
We offer tons of different language files (in the i8n folder). Just load the translation file after you load bootstrap-select.

**Comment by aarhusgregersen** [comment]
Sorry to reopen an old - and closed - issue, but I can't figure out how to customize the text either. I get that I can load the specified i8n file, but for a translated site that has multiple locales, that seems like a bad solution. 
Is it possible to move the control somewhere we can load it conditionally (ir our own JS files)?

**Comment by AmineBelaid** [comment]
you can simply set it up like this: 
```
$('select').selectpicker({
            noneSelectedText: 'put here any msg in preferred lang',
            selectAllText: 'put here any msg in preferred lang',
            deselectAllText: 'put here any msg in preferred lang'
        });
```

you can also add other msgs, search in the bootstrap-select .js file to find the other variables.
