### ISSUE TITLE
Internationalize strings

### ISSUE THREAD

**Issue by rdeavila** [silviomoreto/bootstrap-select#473]
Hi!
I've been using a modified version of Bootstrap Select, because I want the text of Selects in Brazilian Portuguese (things like "Nothing selected", or "No results match" when the select has a search field). 
Although I can make changes for myself, and post on my own server, it is not possible when a third party CDN serve JS files: I'm using jsdelivr.com now. 
If there is a way to add internationalization of strings, can help with the translation. 
Thank you.

**Comment by t0xicCode** [comment]
We seem to have i18n working now, so I'll be closing this.
