### ISSUE TITLE
Auto open

### ISSUE THREAD

**Issue by grecha10** [silviomoreto/bootstrap-select#484]
Hello! 
Is it possible to open a list like that $('.selectpicker').selectpicker('open')?
Required to select a beautiful ajax loading.
Thanks for the cool plugin!

**Comment by KrunchMuffin** [comment]
I know this is old, but was looking for something. came up with this

`$(".bootstrap-select .dropdown-toggle").click()`

**Comment by caseyjhol** [comment]
Alternatively, there's `$('.selectpicker').selectpicker('toggle')`.

**Comment by KrunchMuffin** [comment]
Ya, saw that after. :)

**Comment by rajkumarm-iprogrammer** [comment]
This is perfect solution 

$('.selectpicker').selectpicker('toggle')
