### ISSUE TITLE
Options not populating with the use of ngOptions or ngRepeat

### ISSUE THREAD

**Issue by oluigenuma** [silviomoreto/bootstrap-select#490]
The Template:

```
<select class="selectpicker form-control" data-style="btn btn-default btn-sm" data-live-search="true" ng-model="entity.location" ng-options="row.label for row in tree" title="entity.location"></select>
```

The Controller:

```
$('select').selectpicker();
```

The select-box isn't populating with the use of this setup. Same applys for the use of ng-repeat instead of ng-options. If I remove `$('select').selectpicker();` from the controller, it works fine.

Has someone encountered a similiar problem? Any Solutions?

**Comment by kunalnagar** [comment]
Hi,

I'm using Angular with Firebase and even 'refresh' or 'render' doesn't work. The options are populated in the "normal" select list that is hidden though. Here is my code:

```
<select id="fscode" name="fscode" ng-model="data.fscode" ng-options="station.code as station.name for station in data.stations" class="selectpicker" data-live-search="true"></select>
```

And for the Firebase code:

```
stationsRef.on('value', function(snapshot) {
  		$timeout(function() {
  			$scope.data.stations = snapshot.val();
  			$('.selectpicker').selectpicker('refresh');
  			$('.selectpicker').selectpicker('render');
  			console.log(snapshot.val());
  		});
  	})
```

If you need any more info, let me know!

**Comment by kunalnagar** [comment]
Hi,

I just fixed it. I need to put another timeout inside the main timeout and call the refresh inside of that. Here is an example:

```
stationsRef.on('value', function(snapshot) {
  		$timeout(function() {
  			$scope.data.stations = snapshot.val();
  			$timeout(function() {
  				$('.selectpicker').selectpicker('refresh');
  			});
  			console.log(snapshot.val());
  		});
  	})
```

**Comment by irfantahirkheli** [comment]
@kennynaoh 
You are my boy.. You owe me a lunch bro :). Thanks for posting the answer.

**Comment by vasupotnuru** [comment]
Hi EveryOne ,
i have used Angularjs $http Service call ,options populated but options populated on second click.
pls help me .

$http({
method : "GET",
url : "/SelectBox/service?"
}).then(function mySucces(response) {
$scope.SELECT=response.data;
$('#SELECT9').selectpicker('refresh');
}, function myError(response) {
$scope.SELECT=response.data;
});

**Comment by rosorio02** [comment]
Hi there!
I know the post was made long time ago but I hope my solution will be a help for others.

I got another solution to the issue related.

What I did was first load my data from back-end using angularjs and inside the `.success` after my validation I wrote the following code:
`angular.element(document).ready(function () {
                                   $('select').selectpicker("destroy");
                                   $('select').selectpicker("render");
                                });`
I tried to do it without `angular.element(document).ready(function (){})` but nothing happend. I suppose the plugin's methods only works inside that function.

# **Happy Coding!!**
