### ISSUE TITLE
LiveSearch does not remove hide class from items after closing the select

### ISSUE THREAD

**Issue by simonphilips** [silviomoreto/bootstrap-select#510]
Steps to reproduce:
1. Create a select box with livesearch enabled
2. Open select and perform a live search
3. Close select
4. Open select

Only the items that match the previous live search value are displayed while the live search field is empty.

Simply using .removeClass("hide") instead of .show() works for me:

``` javascript
        liveSearchListener: function() {
            ...
                    that.$searchbox.val('');
                    that.$menu.find('li').removeClass("hide");
                    if (!!no_results.parent().length) no_results.remove();
            ...
```

**Comment by turgs** [comment]
I have the same issue and is reproducible with the same steps as outlined about but in the latest version.

However the fix this time seems to be making sure that when the button's clicked, the `<div class="dropdown-menu">` element gets the `open` class applied which isn't happening by default for some reason.

**Comment by caseyjhol** [comment]
@turgs Please post a live example, and I'll take a look. In the video you posted, you don't appear to be using the live search feature.

**Comment by Rishabhqleverlabs** [comment]
when i use live search and select an option the menu doesn't get closed. iam facing this issue

**Comment by Rishabhqleverlabs** [comment]
![image](https://user-images.githubusercontent.com/32612872/39695895-b55eec6e-5209-11e8-9a7f-a7b065e36db2.png)
