### ISSUE TITLE
Select 'required' parameter not working

### ISSUE THREAD

**Issue by navilink** [silviomoreto/bootstrap-select#514]
Without the styling, it will prompt 'Please fill in this field'. But when style it, the 'required' parameter doesn't work.

<select class="selectpicker" required>

**Comment by rwyland** [comment]
+1

**Comment by MemoLabra** [comment]
+1

**Comment by navilink** [comment]
Sorry for super late reply. Here's the jsfiddle simple example: https://jsfiddle.net/adtu3zv8/

Chrome 43: Doesn't popup "Please select item.."
Firefox 38: Popup "Please select item.." but not positioned at the select but on top-left most of the window

**Comment by ashleydw** [comment]
I'm interest to hear what people make of the method I have used and have suggestions/ideas of alternatives. I have only managed to do this by making the multiselect div overlay the original element (which remains visible), thus allowing the HTML5 required brower tooltip to be displayed.

This works in chrome but is untested in other browsers. Commit of interest: https://github.com/ashleydw/bootstrap-select/commit/51a1b58d0bc0adf8559d0143d33d0f0ea8617e3b

(My fork contains other fixes which aren't related to this issue)

**Comment by injaon** [comment]
I've the same problem. Is there a solutions for this?

**Comment by cyberjar09** [comment]
I'm using @ashleydw's fork. Works fine for me. Why is this not integrated as a pull request?

**Comment by 5minpause** [comment]
@ashleydw's fork works for me as well. Splendid commit.

**Comment by dmolineus** [comment]
When is the next release planned which would integrate this bugfix?

**Comment by szegheo** [comment]
It seems buggy again in Chrome :(
http://codepen.io/anon/pen/NxMMPW?editors=1000

Works OK in latest Firefox, Edge..

**Comment by root91** [comment]
hey everyone! U can easily fix it with css: 

.btn-group.bootstrap-select select {
    width: 1px !important;
}

opacity is set 0 and position absolute will hide your original select but u will see the warning.

**Comment by EcoFreak** [comment]
This does not work for Internet Explorer right?

I'm getting problems with users using IE11.

Any thoughts?

**Comment by TCOA** [comment]
@root91 - you deserve more than a thumbs up! :)  easy patch (would prefer it in the main program) and works great - thanks!

**Comment by dinukasal** [comment]
> hey everyone! U can easily fix it with css:
> 
> .btn-group.bootstrap-select select {
> width: 1px !important;
> }
> 
> opacity is set 0 and position absolute will hide your original select but u will see the warning.

saved my time :D

**Comment by caseyjhol** [comment]
This seems to work fine for me using the latest version of bootstrap-select. If somebody can show me an example of it not working, I'll reopen the issue.

**Comment by ppazos** [comment]
@caseyjhol tried 1.13.12 on FF 66.0.3 Linux and "required" is not working.

I'm styling the select to match bootstrap's default theme:

```
.bootstrap-select {
      width: 100% !important;
    }
    .bootstrap-select .status { /* fix to the status vertical position */
      margin-bottom: -8px !important;
      margin-top: 3px !important;
    }
    .bootstrap-select > .btn.dropdown-toggle { /* make bootstrap select look like normal */
      background-color: white;
      border: 1px solid #ced4da;
    }
```

Also tried @root91 CSS but didn't work:

```
.btn-group.bootstrap-select select {
      width: 1px !important;
    }
```

**Comment by ppazos** [comment]
It seems the selectpicker ajax extension is breaking the required
