### ISSUE TITLE
on dropdown open or close function

### ISSUE THREAD

**Issue by kfir432** [silviomoreto/bootstrap-select#525]
it will be great if there will be a function like onclose dropdown and onopen dropdown.
its for ajax function that send all the options selected onclose dropdown....

thanks... :)

**Comment by sudsneha** [comment]
Not sure why but show.bs.dropdown and hide.bs.dropdown doesnt work for me, Can anyone help?

**Comment by C0ZEN** [comment]
@sudsneha Agreed. I just use the code from @t0xicCode but it doesn't works.

**Comment by caseyjhol** [comment]
You need to use `show.bs.select`. See https://github.com/silviomoreto/bootstrap-select/releases/tag/v1.7.0
