### ISSUE TITLE
data-live-search with option groups

### ISSUE THREAD

**Issue by fquintero** [silviomoreto/bootstrap-select#568]
Hi,

I've got a problem trying to filter options using data-live-search attribute. List items are hidden when "input propertychange" is triggered but because of the list structure (option groups hang from the same list item than the first option of this group), the option group is hidden even if it has options that should appear.

E.g.:

List:

Option Group A-2
	Option A-1
	Option A-2
Option Group B
	Option B-1
	Option B-2

If I enter "-2" in the input box, I get the following result:

Option Group A-2
	Option A-1
	Option A-2
	Option B-2

Hanging from the first option group (because the 2nd option group is hidden). The Option group should be persistent.

Thanks in advance,

Fernando

**Comment by ramkumar522** [comment]
For optiongroup wise live search, you put the same name of optiongroup label text into data-subtext of option value and wrap the text with hidden styles. It has works using optiongroup label wise 
For example
`<select class="form-control selectpicker show-tick" data-live-search="true" name="trekking[]">
	<optgroup label="Everest Region">
		<option data-subtext="<span class='hidden'>Everest Region</span>">Everest Base Camp trekking</option>
		<option data-subtext="<span class='hidden'>Everest Region</span>">Everest Base Camp tour 17 days</option>
	</optgroup>
	<optgroup label="Annapurna Region">
		<option data-subtext="<span class='hidden'>Annapurna Region</span>">Annapurna Base Camp trekking</option>
		<option data-subtext="<span class='hidden'>Annapurna Region</span>">Everest Annapurna Base Camp tour 17 days</option>
	</optgroup>
</select>`

i.e. "everest" query able to show the optgroup of everest region
Thank you...
Ram shrestha
[Software Developer Nepal](https://ramkstha.com.np)
