### ISSUE TITLE
Where should I set `maxOptionsGrp`?

### ISSUE THREAD

**Issue by flyingfoxlee** [silviomoreto/bootstrap-select#576]
I know I can set `maxOptions` in `selectpicker` function. But how should I set `maxOptionsGrp`?

**Comment by JeyKeu** [comment]
```js
       var bsSelect = $('#myBsSelect');
       var dynamicValue = 1;//This is a value set from the UI
       bsSelect.attr('data-max-options', dynamicValue);
       bsSelect.selectpicker('refresh');
```

I can see the `data-max-options` attribute value set in the markup but it does not work as it should.
What am I missing
