### ISSUE TITLE
performance degradation with over 20 selects on website

### ISSUE THREAD

**Issue by rangerek** [silviomoreto/bootstrap-select#582]
when inserting a lot of selects on one page webpage freezes with watchdog alerting about jQuery execution too long
I have already checked #291 and #447 but they are not relevant here 
Here is the sample of the code that is repeated >100 times on the webpage (with different parameters): 
```
<td><select class="selectpicker" name="ref[240][sub_class]">
<option value=0 selected="selected" >A</option>
<option value=1>B</option></select></td>
<td><select class="selectpicker" name="ref[265][sub_class]">
<option value=0>A</option>
<option value=1 selected="selected" >B</option></select></td>
```

**Comment by andyburton** [comment]
Likewise with 1.6.3 and 2.0.0-beta1 - had to revert to 1.6.2 to get it to work in IE8 without the dreaded "A script on this page is causing Internet Explorer to run slowly" alert.

**Comment by caseyjhol** [comment]
Please try v1.7.0-rc2 and report back.
