### ISSUE TITLE
[UI bug fix] prevent to scroll document when you at the end of select list

### ISSUE THREAD

**Issue by werddomain** [silviomoreto/bootstrap-select#584]
when you scroll in the select option list and you at the end of the list, it scroll the document. i give you the code i found to fix the problem.

just put the code after :

```
$(document)
    .data('keycount', 0)
    .on('keydown', '.bootstrap-select [data-toggle=dropdown], .bootstrap-select [role=menu], .bootstrap-select-searchbox input', Selectpicker.prototype.keydown)
    .on('focusin.modal', '.bootstrap-select [data-toggle=dropdown], .bootstrap-select [role=menu], .bootstrap-select-searchbox input', function (e) { e.stopPropagation(); });
```

ADD THIS CODE:

```
$(document).on('DOMMouseScroll mousewheel', '.bootstrap-select .dropdown-menu.selectpicker',  
 function (ev) {
    var $this = $(this),
        scrollTop = this.scrollTop,
        scrollHeight = this.scrollHeight,
        height = $this.height(),
        delta = (ev.type == 'DOMMouseScroll' ?
            ev.originalEvent.detail * -40 :
            ev.originalEvent.wheelDelta),
        up = delta > 0;
    var prevent = function () {
        ev.stopPropagation();
        ev.preventDefault();
        ev.returnValue = false;
        return false;
    }

    if (!up && -delta > scrollHeight - height - scrollTop) {
        // Scrolling down, but this will take us past the bottom.
        $this.scrollTop(scrollHeight);
        return prevent();
    } else if (up && delta > scrollTop) {
        // Scrolling up, but this will take us past the top.
        $this.scrollTop(0);
        return prevent();
    }
});
```

**Comment by Tomas-M** [comment]
I think there should be an option for the user to decide if he wants this or not.
This is perfectly enough to add there:

    $(document).on('DOMMouseScroll mousewheel', '.bootstrap-select .dropdown-menu',
    function (ev) {
        $(this).scrollTop($(this).scrollTop()-ev.originalEvent.wheelDelta);
        ev.stopPropagation();
        ev.preventDefault();
    });

**Comment by yuguilley** [comment]
//// Prevent Scroll
    var body = document.getElementsByTagName('body')[0];
    $(".dropdown-menu").mouseover(function disableBodyScroll() {
        body.style.overflow = 'hidden';
    });
    $(".dropdown-menu").mouseout(function enableBodyScroll() {
        body.style.overflow = 'auto';
    });
