### ISSUE TITLE
Issue on Loading Data From Database Using Ajax

### ISSUE THREAD

**Issue by Behseini** [silviomoreto/bootstrap-select#623]
I have an application which is getting some data from MySQL Database by using Bootstrap 3 Group Button and Bootstrap select library as:

div class="panel panel-default">
  div class="panel-heading">4 - Select Species <button type="button" class="btn btn-default btn-xs pull-right" id="specicPop">?</button></div>
 div class="panel-body">
div class="btn-group"  id="speciesSelect">
      button id="allspecies" type="button" class="btn btn-default btn-sm">All Species</button>
     button id="aquatic" type="button" class="btn btn-default btn-sm">Aquatic</button>
      button id="terrestria" type="button" class="btn btn-default btn-sm">Terrestrial</button>
  /div>
   select class="selectpicker" id="selectPicker" class="form-control" data-container="body" data-live-search="true">
   option value="0">Select From The List</option>
/div>
/div>

and the ajax is as:

"$('.btn-group .btn').click(function(){
     $( ".selectpicker" ).selectpicker("refresh");
    $.post(
        'con/animalList.php',
        { selType : this.id },
        function(data)
        {         $('#selectPicker').html(data);        }    );});"

the PHP part is like

"if ($result->num_rows > 0)     {
    $resultStr.=  '<option value="0">Select From The List</option><option';
        while($row = $result->fetch_assoc())        {
            $resultStr.=  '<option value="'.$row['id'].'">'.$row['fName'].'</option>';          }
    }
    else    {        $resultStr = 'Nothing found';    }"

Now the problem is , I have to Double click or Click Twice to load the select element with options from database. Please be informed that PHP part is working fine and I am getting correct data but I can not figure it out why the First click is not working!

Can you please let me know how to fix this? Thanks

**Comment by AmaliDeveloper** [comment]
Here is a tutorial complete like facebook live search Good Work [Link](https://youtu.be/sWx01r2nIS8)
