### ISSUE TITLE
Selectpicker in div with overflow: hidden

### ISSUE THREAD

**Issue by anton164** [silviomoreto/bootstrap-select#645]
Bootstrap-select doesn't seem to calculate the available space correctly in the case where overflow: hidden; is set in the container div.

http://jsfiddle.net/anton164/J9kfC/1/

There are workarounds of course, like setting data-size, but when the content height varies, it would be ideal if it could calculate available height under based on the container div which has overflow: hidden (if some option is set).

**Comment by D-Skywalker** [comment]
This solution is perfect, but the link seems to be wrong, following an alternative: http://silviomoreto.github.io/bootstrap-select/examples/#container

**Comment by ktravelet** [comment]
Spent wayyyy too much time figuring this out.  Thanks everyone.

**Comment by tristanblackburn-lewis** [comment]
the links are outdated

https://developer.snapappointments.com/bootstrap-select/options/#bootstrap-version
