### ISSUE TITLE
JSDoc 3 support

### ISSUE THREAD

**Issue by t0xicCode** [silviomoreto/bootstrap-select#661]
I would like to see all functions and parameters implemented in the library documented using JSDoc. It will make documentation much easier and will ensure that all options and methods are properly documented.

I expect that this work would be done on the grunt branch, but it can also happen on the master branch.

**Comment by caseyjhol** [comment]
For reference: https://github.com/jsdoc3/jsdoc

**Comment by caseyjhol** [comment]
close in favor of #782
