### ISSUE TITLE
Support bootstrap Height sizing

### ISSUE THREAD

**Issue by apiweb** [silviomoreto/bootstrap-select#694]
I think it would be interesting if the Bootstrap-Select, would support the ["Height sizing"](http://getbootstrap.com/css/#forms-control-sizes)
This height could be set only in select, need not be inherited by the itemlist. 
I make this suggestion because the times have created a form with all fields using input-inpurt-lg or sm, but the select is the one that it stays with the default size.

**Comment by thiagof** [comment]
It is gone from 1.6.4 or 2.0.0.

Why?!

**Comment by thiagof** [comment]
Confirmed to work in version `1.6.3` with the above commit.
