### ISSUE TITLE
Add events to listen for

### ISSUE THREAD

**Issue by jkrehm** [silviomoreto/bootstrap-select#699]
While working with bootstrap-select on one of my projects I lamented the fact that bootstrap-select doesn't trigger any events that I could listen for, e.g. "refresh". Our specific use case was applying a class to the button created by boostrap-select. We were easily able to get around it by adding the code right after the "refresh" call, but if some other code causes it to refresh the class won't get added. That's where events would be amazing.

What do you think of adding events that get triggered on rendering, refreshing, etc? I'm willing to take a crack at it, but you know your code far better than I and might have somewhere in mind already where those could get triggered.

**Comment by Jogai** [comment]
Search input events would be nice, that way its easy to extend the search to use ajax

**Comment by andrews05** [comment]
Just tried out the changed event. Works great, allowed me to greatly simplify my code. Thank you!

**Comment by markcarver** [comment]
@caseyjhol, thank you!!

I suppose https://github.com/truckingsim/Ajax-Bootstrap-Select could initialize on the "show.bs.select" event, but I would still feel more comfortable if there were a dedicated `init.bs.select` event. That way we don't risk re-initializing the ajax-bootstrap-select plugin and so we could also get rid of the hack-ish `setTimeout` work around.

**Comment by caseyjhol** [comment]
Makes sense. I should be able to add that later this week.

**Comment by ntucakovic** [comment]
Another event that might be beneficial and easy to implement is when class active is added (when going through options with keyboard). I need to fire an event each time someone goes through options, for each option.

In 1.6.5 that would be on line 1077.

**Comment by markcarver** [comment]
@caseyjhol, I think this issue can be closed now. I decided to just open a new issue for the `initialize` event (#1026) since it is getting kinda buried by this one (which has already been "fixed").
