### ISSUE TITLE
Duplicating accented characters

### ISSUE THREAD

**Issue by deivamagalhaes** [silviomoreto/bootstrap-select#702]
I am seeing a very weird behavior here... I have a select with live search enabled. When I type an accented character (like "é"), it is displayed twice in the search box. It seems to happen only in Firefox. Has anyone else ever seen it?
![image](https://cloud.githubusercontent.com/assets/4502503/4003221/72016b02-2974-11e4-9fd1-ebcca65a95f5.png)

**Comment by gzambotti** [comment]
I am developing a web map (http://gzambotti.github.io/rusiangenealogy/) and I would like to select from the pull down menu with insensitive accent, meaning if I enter e it should return words with e, é, ê, E. Any suggestions?

**Comment by caseyjhol** [comment]
@gzambotti Set `liveSearchNormalize` or `data-live-search-normalize` to true.
