### ISSUE TITLE
Search only functionality?

### ISSUE THREAD

**Issue by tvirelli** [silviomoreto/bootstrap-select#716]
I am looking for a way to only use the search function. So i want a select menu, but when the user clicks it, I don't want to show any of the options. Once they start to search, say after 3 characters are typed (nice if that number could be defined), then it starts returning results that match.

**Comment by saldanac** [comment]
how this works?

**Comment by EngHans** [comment]
Can this be added as a feature without coding?, this functionality would be really awesome, adding to that an option to limit results.

Thanks for the great work.
