### ISSUE TITLE
Avoid flickering

### ISSUE THREAD

**Issue by sergomet** [silviomoreto/bootstrap-select#736]
The problem is that in addition to whatever other bottlenecks you have, you have to download and parse a lot of javascript files first. Bootstrap-Select depends on Bootstrap which itself depends on jQuery. By the time all that javascript is loaded, the page is probably already rendered. So, the user first sees the HTML select element and then sees it switch to the pretty Bootstrap-select item, thus the "flickering".
(source: http://stackoverflow.com/questions/23251488/bootstrap-select-plugin-how-to-avoid-flickering )
Any other solutions?

**Comment by caseyjhol** [comment]
Anything with the `selectpicker` class is now automatically hidden by default.
