### ISSUE TITLE
title attribute is not working when you don't use multiple

### ISSUE THREAD

**Issue by bboerendans** [silviomoreto/bootstrap-select#738]
It would be very useful if we can use the title attribute also with a default select picker, like:

` <select class="selectpicker" title='Choose one of the following...'>`

For now its only working when you specify multiple.

**Comment by hellocosmin** [comment]
`<option data-hidden="true" value="">Choose one...</option>`

This I think is better, because otherwise your select will have by default the value of the hidden options' text.

Still a hackish way though, it makes no sense to have an empty option as a label, when one could ideally use a title="" attribute just as with the multiple selects...

**Comment by caseyjhol** [comment]
@hellocosmin I guess I'm not sure what the fix is here? A regular select has to have at least one option selected at all times. I suppose setting the title attribute could just automatically insert

```html
<option data-hidden="true" value="">Choose one...</option>
```

**Comment by nickbouton** [comment]
Tested against #0351bd8 and still having to use the hack... setting the `data-title=""` attribute or passing `title` as an argument to `.selectpicker()` still doesn't seem to be respected in 1.7.0 RC1. I notice that if you set either, a hidden option is added to the top of the `select`, but the option text is empty.

**Comment by caseyjhol** [comment]
Hrmm...it's working for me (Chrome 42, Windows 8.1). Can you provide me with a jsfiddle? The option's text node is empty on purpose. `render()` already checks to see if the selected option is empty, and if so, sets the title accordingly.

**Comment by caseyjhol** [comment]
@nickbouton Give it a shot now using the latest version from master. I was able to reproduce it if the select had a lot of options, but it was working fine on a select with ~20 options.

**Comment by nickbouton** [comment]
@caseyjhol Tried the latest build, no dice. I'm testing on Mac OS X 10.10.3, Chrome 42.0.2311.135 (64-bit). Still have to add that empty option manually for the title to be applied. I'll post a fiddle in a bit.

**Comment by nickbouton** [comment]
@caseyjhol Scratch my previous comment, I dumped a cut-down version of what I had into [JSfiddle](http://jsfiddle.net/c5evoo2s/1/) and it looks to be working fine. Might be another library version causing issues or conflicting with something, I'll try and track it down here. Thanks for your help.

**Comment by wreardan** [comment]
I experienced this problem as well.  I attempted to update the bootstrap-select code to apply this fix.  However, this significantly changed the styling inside our application.  I fixed the problem by applying the above fix 
`data-hidden="true"`
