### ISSUE TITLE
Fixed nav overlaps long select

### ISSUE THREAD

**Issue by trololosha4real** [silviomoreto/bootstrap-select#749]
So, when usind defaul fixed nav in bt with long select it overlaps the plugin. Tried to "play" with z-index, but no luck... Only thing that helped is the decreasing of the maximum height.

![untitled](https://cloud.githubusercontent.com/assets/7287184/4441782/f858a190-47d6-11e4-9811-b1ebd6d64349.png)

**Comment by kriskd** [comment]
I'm running into the same issue.  My long list is getting hidden under the element above it.  How are you adjusting maximum height since that is controlled by the plugin JS?

**Comment by caseyjhol** [comment]
You need to use `data-container="body"` as the container for your selects is preventing the menu from being completely visible.
