### ISSUE TITLE
Conflict with another plugin

### ISSUE THREAD

**Issue by pdcmoreira** [silviomoreto/bootstrap-select#755]
Hi,

I'm including "eternicode/bootstrap-datepicker" plugin in the same page as this one and the select doesn't work anymore. It shows the button with the first option as the text, but no options inside. Also, datepicker stops showing any hover or selected effects.

As soon as I remove one of the plugin's css file from the page, the other plugin becomes fully working again.

select:

```html
<select name="categoria" class="selectpicker" data-live-search="true" data-width="100%">
```
```javascript
$('.selectpicker').selectpicker();
```

datepicker:

```html
<div class="input-group date" id="test">
    <input type="text" class="form-control" id="test" />
```
```javascript
$('#test').datepicker();
```

**Comment by RemiBloch** [comment]
Hello, 

We checked your code and after quite some time we started reading issues till we found this one which is the exact same problem than we've.

Here is the fiddle that shows the problem. The problem is NOT the usage of datetimepicker and selectpicker as having both works. The problem comes from boostrap itself. I think that some bootstrap css updated is conflicting with your select css

http://jsfiddle.net/5g2vebhm/1/

EDIT : it's related to boostrap vs boostrap-select as removing the datetimepicker lib doesn't correct the problem

**Comment by RemiBloch** [comment]
any update on this issue? This is really a huge problem as it totally prevents a lot of dev to use your awesome lib.

**Comment by caseyjhol** [comment]
The problem is you were using the "Bootstrap 3.2.0" option built into JSFiddle. I unchecked that option and loaded bootstrap separately and it works. http://jsfiddle.net/5g2vebhm/2/

**Comment by hurbinal** [comment]
Your solution works fine but it has conflicts with modal windows, i upgraded the JSFiddle for pointing the problem :(

**Comment by caseyjhol** [comment]
@hurbinal Can you elaborate? What conflicts? Link to the JSFiddle?

**Comment by hurbinal** [comment]
sorry, i edited the comment, but the link of JSFiddle is http://jsfiddle.net/5g2vebhm/4/

**Comment by caseyjhol** [comment]
Removing bootstrap-select completely results in the same problem - so the problem isn't related to bootstrap-select. Upgrading the version of Bootstrap to 3.3.7 fixes the problem.

**Comment by hurbinal** [comment]
@caseyjhol I made a couple of changes to the JSFiddle, updating bootstrap make it work, but which version of bootstrap-select and bootstrap-datetimepicker have you used?

**Comment by caseyjhol** [comment]
I used the same versions that were in that demo. Bootstrap-select hasn't done anything to affect modal z-indexes, so newer versions should work as well.

**Comment by hurbinal** [comment]
I found the problem, i was using jQuery 3.X, i have to use 2.1.0 instead :P
