### ISSUE TITLE
Hide empty optgroups on search

### ISSUE THREAD

**Issue by deel77** [silviomoreto/bootstrap-select#768]
I needed to hide empty optgroups during search, so I added at line 925 code:
```javascript
          that.$lis.filter('.dropdown-header').each(function(index, header){
              header = $(header);
              var lastElem = header.nextUntil(':not(.hide)').last();
              var nextElem = lastElem.next();
              if ((lastElem.size() > 0 && nextElem.size() === 0) || nextElem.hasClass('divider')) {
                  header.addClass('hide');
                  nextElem.addClass('hide');
              }
          });
```

not sure if it is best, but if somebody needs it ;-)

**Comment by artsx** [comment]
Hello, the new version of the plugin where do you put the code to hide the divider?

Thx

**Comment by deel77** [comment]
It looks quite changed and in marginal ways, I use it in project with older version and would need more time to analyse new version. If you are in hurry, I can send old file.

**Comment by artsx** [comment]
Hello, thank you for taking the time to answer me.
I'll look at that!

**Comment by dhimancontact** [comment]
this is already resolved with new version of download.
