### ISSUE TITLE
JS Error in IE8

### ISSUE THREAD

**Issue by adick** [silviomoreto/bootstrap-select#769]
There is an error in the htmlEscape function; IE8 says 

````
Message: Object doesn't support this property or method
Line: 63
Char: 5
Code: 0
URI: bootstrap-select/js/bootstrap-select.js
````

Line 63 is

``
var source = '(?:' + Object.keys(escapeMap).join('|') + ')',
``

Solution would be to add a polyfill for browsers that don't support Object.keys()

````
Object.keys = Object.keys || function(
	o, // object
	k, // key
	r  // result array
) {
	// initialize object and result
	r = [];
	// iterate over object keys
	for (k in o)
		// fill result array with non-prototypical keys
		r.hasOwnProperty.call(o, k) && r.push(k);
	// return result
	return r
};
````

**Comment by jnovec** [comment]
Can you please write where this part of code should i put ? Many many thanks :)

**Comment by CheapSk8** [comment]
Just copy what he wrote and paste it at the end of the bootstrap-select.js file, after the (jquery); That should take care of it for you.

**Comment by ofiros** [comment]
10x saved me !

**Comment by andyburton** [comment]
This worked in solving the error but just kicked the can further down the road and triggers the "A script on this page is causing Internet Explorer to run slowly" alert which i can't seem to overcome.

**Comment by SnehaSuryawanshi** [comment]
Saved big time! thanks!!

**Comment by izkuved0** [comment]
This is awesome. Thanks

**Comment by jatorresdev** [comment]
Thanks
