### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by lvgunst** [silviomoreto/bootstrap-select#778]
Latest release is 1.6.3. But the NPM package is still at 1.6.2: https://www.npmjs.org/package/bootstrap-select. Can the package maintainer please publish the latest release to NPM?

**Comment by caseyjhol** [comment]
@t0xicCode Can you add me as a collaborator?

**Comment by t0xicCode** [comment]
Sure.

**Comment by t0xicCode** [comment]
I'll need to have your npm username.

**Comment by caseyjhol** [comment]
It's caseyjhol

**Comment by t0xicCode** [comment]
Done
