### ISSUE TITLE
Using bootstrap-select with CommonJS (webpack/browserify)

### ISSUE THREAD

**Issue by chiefGui** [silviomoreto/bootstrap-select#789]
Hey guys!

There's a (native) way to work with `bootstrap-select`  through CommonJS, such as browserify or webpack? Or should I to shim it?

**Comment by caseyjhol** [comment]
Fixed in #866.

**Comment by Wilfred** [comment]
What's the correct usage for bootstrap-select with webpack/browserify these days? I've tried

```js
require('bootstrap-select/js/bootstrap-select');
require('bootstrap-select/dist/css/bootstrap-select.css');
```

but this assumes that `jQuery` is available on the global window object.

**Comment by tonyseek** [comment]
@Wilfred 

```
require('bootstrap-select')
```

**Comment by Wilfred** [comment]
Gotcha, thanks. I needed to use the exposed jquery too.

Per [this article](https://65535th.com/jquery-plugins-and-webpack/), I installed `expose-loader`, updated my webpack.config.js to include:

```js
loaders: [ // ...
{ test: /jquery/, loader: 'expose?$!expose?jQuery' }
```

and then in my code:

```js
require('jquery');
require('bootstrap-select');

// ...
window.$('.foobar').selectpicker();

**Comment by AngularTx** [comment]
Hi Guys, 

I need help in getting Bootstrap-select working with my Angular2 application . 

Angular version - 2.4.8 , webpack 
Browser - IE 

I have followed some of the steps given here , but the select drop down has no effect. Only thing happens is that the drop down is hidden. Styles are not getting added. Can some one help me here .

**Comment by binary2quantum** [comment]
Hi guys,

I need some suggestions in fixing up my issue... 

i have added the bootstrap-select in angular.cli.json file... The selectpicker will not appear when the page is initially loaded.... but it will appear when the page is refreshed again....

So i don't know what will be the exact problem... can anyone pls help me to fix it up...
