### ISSUE TITLE
Setting 'data-max-options' via jquery doesn't work.

### ISSUE THREAD

**Issue by mrudult** [silviomoreto/bootstrap-select#800]
I'm trying to set the _data-max-options_ attribute programmatically after clicking a button. The data attribute is being added correctly but the _'render'_ or _'refresh'_ method has no effect on the select. 

```
$("#select").attr("data-max-options", "2");
$('#select').selectpicker('render');
```

**Comment by vgross** [comment]
I have the same issue using your code. I have a function to disable and enable my select + set maxOptions but unfortunately your line

 $('#select').selectpicker('maxOptions', 2); 

doesn't work for me as the disable/enable method works fine.

here my method:

    function initChildren(e) {
        var form_child = e.parent().parent().next().find('select[id$="_children_ages"]').first();
        if(e.val() == "0"){
            form_child.prop('disabled', true);
        } else {
            form_child.prop('disabled', false);
            //TODO : Make that works
            form_child.selectpicker('maxOptions', e.val());
        }
        form_child.selectpicker('refresh');
    }

Even if I replace e.val() by a number directly, it doesn't work.
