### ISSUE TITLE
Performance issues on refresh

### ISSUE THREAD

**Issue by sheeshmohsin** [silviomoreto/bootstrap-select#806]
when using .selectpicker('refresh') on a huge list of items dynamically added to the dropdown, it takes a lot of time for refresh, the list is around of 5000 items or more. Please help someone to solving this performance issue.

**Comment by enricosoft** [comment]
I have the same problem when try to refresh about 30 selects (without a lot of items inside), in particular on mobile devices. Hope this problem will be fixed asap cause this is a nice plugin

**Comment by caseyjhol** [comment]
Please try v1.7.0-rc2 and report back.
