### ISSUE TITLE
how to use i18n

### ISSUE THREAD

**Issue by valix85** [silviomoreto/bootstrap-select#813]
Hello, is it possible to have  a guide for use other languafe in i18n?
i need to load Italian language for this component, whan can i do it?

thank you

**Comment by ochafloquet** [comment]
LIKE THIS
<script>    
    $(document).ready(function(){

        $('#combogrados').selectpicker({
         language: 'ES'
        });
	
    });
    </script>

**Comment by ochafloquet** [comment]
Only put the language.js and it works

**Comment by totpero** [comment]
Hello, this method don't works if i have `selectpicker` class on my select.
You have this on end of the plugin:

```
 // SELECTPICKER DATA-API
// =====================
        $(window).on('load.bs.select.data-api', function () {
            $('.selectpicker').each(function () {
                var $selectpicker = $(this);
                Plugin.call($selectpicker, $selectpicker.data());
            })
        });
```

Is any method to do this without jquey call `$('#combogrados').selectpicker(....`?

**Comment by dfarm3r** [comment]
I've been trying to figure out how to do this for days and can't get it to work. I emailed Silvio to no avail. Could someone please post complete example of how to use the right locale file when using this module?

**Comment by caseyjhol** [comment]
Simply load the language file after bootstrap-select.

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/i18n/defaults-de_DE.min.js"></script>

**Comment by dfarm3r** [comment]
This doesn't seem to work. Still seeing English text within the dropdown
for "select all" and "deselect all".

**Comment by dfarm3r** [comment]
So, it does work. Just turns out these are not translated for German. Thanks

**Comment by caseyjhol** [comment]
Hrmm...they should be translated for German: https://github.com/silviomoreto/bootstrap-select/blob/master/dist/js/i18n/defaults-de_DE.js#L37-L38

**Comment by aolszak** [comment]
It would be better to select language in options :-(

**Comment by caseyjhol** [comment]
At some point we'll add the option to select the language in the options, but you'll still always have to load the language files separately.

**Comment by NeilAllen** [comment]
Let me know when the **option** feature is sorted, Ta!

**Comment by adaamz** [comment]
For those using webpack there is solution using `require` function:
```html
<html lang="cs">
```
```js
const langMap = {
    cs: "cs_CZ",
    en: "en_US",
};

if (document.documentElement.lang in langMap) {
    require("bootstrap-select/js/i18n/defaults-" + langMap[document.documentElement.lang]);
} else {
    console.error("Unknown language " + document.documentElement.lang);
}
```
