### ISSUE TITLE
 [Proposal] Use dataSource to store object items, add events, pass data from options

### ISSUE THREAD

**Issue by gperdomor** [silviomoreto/bootstrap-select#814]
Hi, I'm working on a project using this plugin and ajax-bootstrap-select plugin (https://github.com/truckingsim/Ajax-Bootstrap-Select) which adds capability to use ajax, but in some cases, i need execute some function on select event, the problem is when that function needs a field of the object represented in the options list, for example, in my project, the ajax request return a client list, where the client's id is the 'value' and the client's name is the 'text' shown on the options list of the plugin, i need execute a function for validate or show something using/depending of another field of the client, like status or email (any field can be used), but i can't access to these fields.

Removing the ajax part, this can be applied to this plugin with local data, now, the local data are the <option> elements of the select, but that "data" only have a value and text (yes, i can add data attributes to set another values but i don't like the idea, i think is much better pass an array of data on the plugin options).

Twitter Typeahead plugin have a event ('typeahead:selected') which is fired when the user select an item, and the function of this event has two parameters, the event himself and the item with the object. Would be nice have something like that here....

Would be nice too, have events like onOpen, onClose, onSelect...

I post a similar issue here: https://github.com/truckingsim/Ajax-Bootstrap-Select/issues/33

**Comment by caseyjhol** [comment]
See https://github.com/silviomoreto/bootstrap-select/releases/tag/v1.7.0-rc1. You can now use the events `show.bs.select`, `shown.bs.select`, `hide.bs.select`, `hidden.bs.select` and `changed.bs.select`.
