### ISSUE TITLE
Support for contextual classes

### ISSUE THREAD

**Issue by LoLFactor** [silviomoreto/bootstrap-select#815]
You should add support for Bootstrap form-group contextual classes.

For those of you looking for a quick fix to the same problem, here's one in plain CSS:

```
.form-group.has-success .bootstrap-select .btn.dropdown-toggle {
    border-color: #3C763D;
}
```
Now just replace the `.has-success` part with any other contextual class and replace the color value accordingly.

**Comment by caseyjhol** [comment]
Duplicate of #569.
