### ISSUE TITLE
"Select all" option for multiple select

### ISSUE THREAD

**Issue by taspeotis** [silviomoreto/bootstrap-select#825]
I'm replacing some rather ugly jQuery UI multiselect controls with bootstrap-select and everything works quite well except I cannot find any built-in way to display a "select all" option.

The old controls look something like this:

![image](https://cloud.githubusercontent.com/assets/1189399/5408956/193d894c-822f-11e4-90e2-d5808d320d8d.png)

I'm not proposing two options (select all and deselect all, like in the screenshot) but I would think a

```
[ x ] Select All
```

option, that floats at the top like the search bar does, would be nice to have.

I'm not a JavaScript virtuoso but if there was some interest or acceptance of this idea I could try developing it and submitting a pull request.

**Comment by leocaseiro** [comment]
Use the parameter data-actions-box="true"

**Comment by erkanakoglu** [comment]
is it possible to change text Select All and Deselect All ?

**Comment by giero** [comment]
```javascript
$('.selectpicker').selectpicker({
    selectAllText: 'Your select-all-text',
    deselectAllText: 'Your deselect-all-text'
});
```

**Comment by maloomadhur** [comment]
Adding a style attribute doesn't change the style of actionsBox buttons. Am I missing something?

$('.selectpicker').selectpicker({
            style: 'btn-select',
            selectAllText: 'All',
            deselectAllText: 'None'
        });

**Comment by giero** [comment]
Looks like 'style' attribute is not combined with actionsBox

```javascript
var actionsbox = this.multiple && this.options.actionsBox ?
      '<div class="bs-actionsbox">' +
      '<div class="btn-group btn-group-sm btn-block">' +
      '<button type="button" class="actions-btn bs-select-all btn btn-default">' +
      this.options.selectAllText +
      '</button>' +
      '<button type="button" class="actions-btn bs-deselect-all btn btn-default">' +
      this.options.deselectAllText +
      '</button>' +
      '</div>' +
      '</div>'
          : '';
```

Should be then

```javascript
var actionsbox = this.multiple && this.options.actionsBox ?
      '<div class="bs-actionsbox">' +
      '<div class="btn-group btn-group-sm btn-block">' +
      '<button type="button" class="actions-btn bs-select-all btn '+this.options.style+'">' +
      this.options.selectAllText +
      '</button>' +
      '<button type="button" class="actions-btn bs-deselect-all btn '+this.options.style+'">' +
      this.options.deselectAllText +
      '</button>' +
      '</div>' +
      '</div>'
          : '';
```

But that's only fast idea - didn't check it ;)
