### ISSUE TITLE
selectpicker not showing properly in table (bootstrap-select 1.6.3)  

### ISSUE THREAD

**Issue by avarndell** [silviomoreto/bootstrap-select#838]
Select multiple in table cell is not showing properly and I noticed that looking at the elements in the brower (f12) is showing different html construction which the same code.

same code in both
![tdcode](https://cloud.githubusercontent.com/assets/7513911/5542843/b9c1249a-8ab9-11e4-8efe-b4d5a9f20f45.png)

![td2working](https://cloud.githubusercontent.com/assets/7513911/5542825/6b825f24-8ab9-11e4-981a-79eb2ab927e0.png)

![tb1notworking](https://cloud.githubusercontent.com/assets/7513911/5542826/6f2ca238-8ab9-11e4-88e1-8a0c6c2ad51b.png)

**Comment by avarndell** [comment]
After further digging, I found that the dropdown doesn't show properly when angularjs is being used.

**Comment by avarndell** [comment]
Here is the sample.  JS Fiddler is not using the correct versions of angular, etc.
    <div ng-controller="ProjectController">
           <div style="max-height: 650px; overflow-y: auto; overflow-x:hidden">
     <table  class="table table-striped">
         <thead>
             <tr>
                 <th>
                     Name
                 </th>
                 <th ng-repeat="(key, value) in attributes">
                     {{key}}
                 </th>
                 <th></th>
             </tr>
         </thead>
         <tbody>
             <tr ng-repeat="device in devices">
                 
                 <td colspan="{{numAttributes + 4}}" >
                     <form name="editForm" >
                         <table class="table table-no-border table-internal">
                             <tr>
                                 <th>Name</th>
                                 <th ng-repeat="(key, value) in attributes">
                                     {{key}}
                                 </th>
                             </tr>
                             <tr>
                                 <td>
                                     <input name="uName" type="text" class="form-control" maxlength="32" ng-model="selectedDevice.name" placeholder="Enter the device name" />
                                 </td>
                                 <td ng-repeat="(key, value) in attributes">
                                     <select class="selectpicker form-control" name="uAttr_{{key}}[]" ng-if="value.property=='MultiSelect'" ng-model="selectedDevice.attributes[key.toLocaleLowerCase()]" multiple="multiple" ng-options="attrType for attrType in value">
                                     </select>
                                     <select class="selectpicker form-control" name="uAttr_{{key}}" ng-if="value.property !='MultiSelect'" ng-model="selectedDevice.attributes[key.toLocaleLowerCase()]" ng-options="attrType for attrType in value">
                                     </select>
                                 </td>
                                 <td ng-if="selectedDevice.id == device.id">
                                     <button class="btn btn-primary" ng-click="saveEditDeviceModel()">Save</button>
                                     <a class="btn btn-link btnlink" ng-click="cancelEditDeviceModel()">Cancel</a>
                                 </td>
                             </tr>
                         </table>
                     </form>
                 </td>
                 
                 <td ng-if="selectedDevice.id != device.id">
                     {{device.name}}
                 </td>
                 <td ng-repeat="(key, value) in attributes" ng-if="selectedDevice.id != device.id" ng-model="key">
                     {{device.attributes[key.toLocaleLowerCase()]}}
                 </td>
                 <td ng-if="selectedDevice.id != device.id">
                     <div class="dropdown">
                         <button class="btn btn-default dropdown-toggle tablebutton" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
                             <span class="fa fa-ellipsis-h"></span>
                         </button>
                         <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                             <li role="presentation"><a role="menuitem" ng-click="editDeviceModel(device)" class="tableicon-color"><span class="fa fa-pencil-square-o tableicon-color"></span>Edit</a></li>
                             <li role="presentation"><a role="menuitem" ng-click="deleteDeviceModel(device)" class="tableicon-color"><span class="fa fa-trash-o tableicon-color"></span>Delete</a></li>
                         </ul>
                     </div>
                 </td>
             </tr>
             
         </tbody>
                </table>      </div>
         </div>
         
  CSS
  /* use for table when you don't want the separating lines'*/
  .table-no-border>thead>tr>th,
  .table-no-border>tbody>tr>th,
  .table-no-border>tfoot>tr>th,
  .table-no-border>thead>tr>td,
  .table-no-border>tbody>tr>td,
  .table-no-border>tfoot>tr>td {
      border-top: none;
      background-color: transparent;
      color: #455059;
      padding: 0 8px 0 0;
  }
  
  /* removes the cell padding and striped backgrounds*/
  .table .table-internal {
      background-color: transparent;
      height: auto;
  }
  .table-internal>thead>tr,
  .table-internal>tbody>tr,
  .table-internal>tfoot>tr
  {
      height: auto;
  }
  .table-internal>thead>tr>td,
  .table-internal>tbody>tr>td,
  .table-internal>tfoot>tr>td {
      padding-top: 0;
      padding-left: 8px;
      padding-right: 8px;
      padding-bottom: 0;
  }
  
  .tableicon-color
  {
    color: #006ebb !important;
}

javaSCRIPT
var myApp = angular.module('myApp', ['commonDirectives']);
 angular.module("myApp").controller('ProjectController', function ($scope) {
        $scope.devices = [];
        $scope.attributes = [];
        $scope.attributes =
        {
            "Antenna": ["None", "Type 3i"],
            "Band": ["700 Mhz", "800 Mhz", "1900 Mhz"],
            "Chipset": ["MDM 8960", "MDM 6610", "MT6525"],
            "Form Factor": ["Candybar", "Fliphone", "Smartphone"],
            "GPRS-Edge Capability": ["Yes", "No"],
            "Manufacturer": ["Apple", "Samsung", "ZTE"],
            "Operating Systems": ["Android OS", "iOS", "Win RT"],
            "UMTS Capability": ["CAT 10", "CAT 14", "LTE"]

        };
            $scope.numAttributes = 5;
            var devices = [
                        {
                        "Name": "aAnnette",
                          "Id": "255",
                          "attributes": {
                              "Band":["800 Mhz", "1900 Mhz"],
                              "UMTS Capability":["CAT 10", "LTE"]
                          }
                      },
                      {
                          "Name": "test",
                          "Id": "256",
                          "attributes": {
                              "Antenna": "None",
                              "Band":["800 Mhz", "1900 Mhz"],
                              "Band.property": 'MultiSelect',
                              "Chipset": "MDM 8960",
                              "Form Factor": "Candybar",
                              "GPRS Edge Capability": "No",
                              "Manufacturer": "Apple",
                              "Operating Systems": "iOS",
                              "UMTS Capability":["CAT 10", "LTE"]  
                          }
                      },
                      {
                          "Name": "aaaa",
                          "Id": "257",
                          "attributes": {
                              "Antenna": "None",
                              "Band":["800 Mhz", "1900 Mhz"],
                              "Band.property": 'MultiSelect',
                              "Chipset": "MDM 8960",
                              "Form Factor": "Candybar",
                              "GPRS Edge Capability": "No",
                              "Manufacturer": "Apple",
                              "Operating Systems": "iOS",
                              "UMTS Capability":["CAT 10", "LTE"]
                          }
                      }];

            angular.forEach(devices, function (index) {
                if (index.attributes != null) {
                    angular.forEach(index.attributes, function (attr) {
                        if (attr.length > 1) {
                            attr.property = 'MultiSelect';
                        }
                    });
                }
            });
        $scope.devices = devices;

    });

    var commonDirectives = angular.module('commonDirectives', []);

    angular.module('commonDirectives')
        .filter("arrayToCsv", function () {
            return function (input) {
                //console.log("arrayToCsv", input);
                if (angular.isArray(input)) {

                    var str = "";
                    for (var i = 0; i < input.length - 1; ++i) {
                        str += input[i] + ", ";
                    }
                    if (input.length > 0)
                        str += input[input.length - 1];
                    return str;
                } else {
                    return input;
                }
            }
        });

**Comment by t0xicCode** [comment]
that didn't format properly. Could you put the code up in a gist or a pastebin?

**Comment by caseyjhol** [comment]
Closing this until additional information is provided.
