### ISSUE TITLE
Form reset support

### ISSUE THREAD

**Issue by deSpartaan** [silviomoreto/bootstrap-select#84]
When I hit a button with type="reset" the reqular form fields are being reset to their default / initial value. But the bootstrap-select selectbox is not.
Please provide a method to reset the bootstrap select element.
Patrick

**Comment by mayankit** [comment]
Not working for me

**Comment by tentus** [comment]
@mayankit This reply is just for posterity, I found that wrapping the render inside a setTimeout() call would fix an order of operations issue that might explain why it wasn't working for you.

**Comment by pienisieni** [comment]
I'm using a plain hyperlink to reset the form. With the above code I had to click on it twice for it to work. So this is what's working for me now.

`<a id="resetme" href="">Reset Form</a>`

```
$('#resetme').click(function(event) {
	 event.preventDefault();
        url = $(this).attr("href");
	$(".selectpicker").val('').selectpicker('render');
});

```
also useful:

// this is to reset everything else
$('#eventForm')[0].reset(); 

// this is useful to hide stuff, in this case formvalidation.io feedback icons
$('.form-control-feedback').css('display','none');
$('.help-block').css('display','none');
$(".has-feedback").removeClass("has-error has-success");
