### ISSUE TITLE
Bootstrap-select does not respond to forms’ reset event.

### ISSUE THREAD

**Issue by infinnie** [silviomoreto/bootstrap-select#844]
So when the form is reset using the reset button, the select box doesn’t get updated and gives us an unpredictable and annoying experience.
My current fix is like this:
<pre>
            $("form").on("reset", function () {
                var that = this;
                setTimeout(function () {
                    $(that).find("select").trigger("change");
                }, 1);
            });
</pre>

**Comment by caseyjhol** [comment]
Simply run `$('select').selectpicker('refresh')`.
