### ISSUE TITLE
Translation problem Select-all

### ISSUE THREAD

**Issue by andos21** [silviomoreto/bootstrap-select#848]
Hi,

how is it possible to translate the text for "Select All" or "Deselect All"?

regards,
andos

**Comment by vsn4ik** [comment]
```js
$.fn.selectpicker.defaults = {
  selectAllText: 'Select All',
  deselectAllText: 'Deselect All'
};
```

**Comment by MarcosMenegazzo** [comment]
Would be nice if these defaults could be set as " data-* " attributes for i18n apps.
