### ISSUE TITLE
Ajax call on "data-live-search"

### ISSUE THREAD

**Issue by samphp90** [silviomoreto/bootstrap-select#849]
Hello,
Please help me !!
Is any method to call the custom ajax method to get the values from database ?

**Comment by truckingsim** [comment]
There is no way to do this natively.

This is why I made [this plugin](https://github.com/truckingsim/Ajax-Bootstrap-Select) which extends bootstrap-select to add the ability to do ajax searching.

**Comment by samphp90** [comment]
Thanks :D
