### ISSUE TITLE
Beta tag for v1.6.4

### ISSUE THREAD

**Issue by begizi** [silviomoreto/bootstrap-select#853]
There seem to have been a lot of code changes/bug fixes since v1.6.3. What is the plan for a v1.6.4 release? Can we add a git tag for the current alpha/beta that I can use with bower?

**Comment by Khrysller** [comment]
+1

**Comment by kiRach** [comment]
+1

**Comment by t0xicCode** [comment]
Seems like a good idea. I might tag it with 1.7.0-beta though.
