### ISSUE TITLE
Tab key does'nt move focus to next control in DOM when selectOnTab = true

### ISSUE THREAD

**Issue by SamerX** [silviomoreto/bootstrap-select#859]
When selectOnTab option is set to true and the drop down is open the tab key should select the selected option by arrows and move focus to next control in DOM.

**Comment by caseyjhol** [comment]
Standard select behavior is to select the option and then close the menu, while keeping the select focused. I think standard functionality is what users would expect, but if there's more interest in this feature I'll reopen.
