### ISSUE TITLE
No support for disabling options from javascript

### ISSUE THREAD

**Issue by dmitry-solomadin** [silviomoreto/bootstrap-select#86]
Currently there is no way to dynamically disable option from js.

**Comment by saptisunil** [comment]
Heyy ! I just want to disable some of the options from the drop down list. How can i do that? Please help ! Thanks in Advance

**Comment by jeuelc** [comment]
any of the following will work:
```
$("#selectId option[value=1]").attr("disabled","disabled");
$("#selectId option[value='2']").attr("disabled","disabled");
$("#selectId option[value=3]").prop("disabled",true);
$("#selectId option[value='4']").prop("disabled",true);
```
just refresh the rendering of the selectpicker:

`$('#selectId').selectpicker('refresh');`

**Comment by minddifferent** [comment]
@jeuelc thanks man
