### ISSUE TITLE
Index not correct

### ISSUE THREAD

**Issue by AntiFish03** [silviomoreto/bootstrap-select#867]
I am seeing an issue where the index is not being calculated correctly, I have 3 option groups US States, Canadian Provinces, and Australian States.  So for example pressing 't' should return 3 key indexes. Also, I noticed that `$items.length` should be 87 but `.index()` is returning a value out of that range.

``` javascript
// Expected:
keyIndex = [
  56 // Tennessee
  , 57 // Texas
  , 84 // Tasmania
]

// Actual:
keyIndex = [
  58 // Utah
  , 59 // Vermont
  , 90 // ??? Out of range. 
]
```
When inspecting Line 1074
```javascript

$items.each(function () {
  if ($(this).parent().is(':not(.disabled)')) {
    if ($.trim($(this).text().toLowerCase()).substring(0, 1) == keyCodeMap[e.keyCode]) {
      keyIndex.push($(this).parent().index());
    }
  }
});
```
I noticed that the `data-original-index="56"`
but in the following the `.index()` is returning as 58.

I will try to get a fiddle setup so that you can debug the issue.

**Comment by acshef** [comment]
The indices get messed up when there are group headers or dividers.

**Comment by caseyjhol** [comment]
In b3bbb6b9c30249481b6798d7b511b5a936ebe4cb it was changed to use `.data('originalIndex')` instead of `.index()`. This should be working now in the latest release candidate.
