### ISSUE TITLE
Accessibility: Dropdown buttons are just "buttons".

### ISSUE THREAD

**Issue by IngwiePhoenix** [silviomoreto/bootstrap-select#870]
Hey there.

I am currently going over my site using VoiceOver and I got rather disappointed when I had it read back my bootstrap-select content...it only read it as a button. So on the example page, it would only read "Mustard, button" and the actual dropdown was read properly ("Mustard, dropdown menu, three entries").

How can I have that fixed?

**Comment by johnpalaganas** [comment]
Would be great to address all accessibility issues. Is this project still alive?

**Comment by caseyjhol** [comment]
Related to #541.
