### ISSUE TITLE
[ Proposal ] Grouping: Allow options to be shared among selects

### ISSUE THREAD

**Issue by gtristan** [silviomoreto/bootstrap-select#871]
This is somewhat of a performance issue for me, I have some pretty small selects, with only around 30 options... but they are all pretty and have an <img> beside some text and also a tooltip showing for each content in the case that ellispizing is needed.

What happens, and I'm sure this is a common enough occurance, is that I need to have many of these selects on screen a the same time... say you are editing a list of data and each item of the list has the option to 'Select an animal'... and so you repeat the 'animal select' for each item in the list.

It would be very nice if the options in the menu could be shared among all select pickers displayed of  the same group - currently I have some performance issues specifically when this list appears in a bootstrap 'modal' dialog - when the modal is dismissed there is a lag at the end of the animation when the list is finally detached from the DOM and reflow occurs.

In any case the drop down menu is an exclusive UI (there can only be one dropdown menu displayed at a time), so it seems logical that many select pickers in the same group should share the DOM fragment that is shown in the dropdown.

**Comment by gtristan** [comment]
First sentence got garbled by github... I meant to say that there is an image beside some text for each option, plus a tooltip... looks like github comments just done like '&lt;' and '&gt;'

**Comment by t0xicCode** [comment]
If I understood you correctly, you are re-using the same `<select>` on multiple place on your webpage, and you'd like to know if the generated selectpicker can be reused (or the generated dropdown at least)?

**Comment by gtristan** [comment]
Exactly, actually I'm using the same <select> a dynamic number of times on the same page (as many times as a user adds an item to a configurable list).

**Comment by t0xicCode** [comment]
Because of the way events are bubbled and handled both by the bootstrap dropdown and the selectpicker, I can't really think off-hand of a way to accomplish this without garbling the whole library. However, if you do come up with a sane & simple solution for it, I'd be willing to consider incorporating it.

In the meantime I'll close the issue.

**Comment by gtristan** [comment]
I think I can come up with a sane solution, unfortunately I doubt it would be simple, but it might also address other use cases I had in mind...

I'll just bounce some ideas off you just in case it interests you, basically the idea is to break selectpicker down into 3 MVC like components, one model and two views, allowing more flexible setups.

### The model
The model would be a JS object which stores the current value of the select, it would have an array of callbacks which would be called at any time the value changes, depending on the list view implementation, it would also store the original `select` element and notify changes made to the options.

### The button view
The button view would just be a basically be a bootstrap style button which can be connected to the select model, when the value changes, the button updates it's appearance. The button can also optionally be connected to a list view (and would be by default if one constructs the selectpicker using the regular API). The button would also have the option of setting the size of it's connected dropdown menu, or letting the dropdown menu have it's own natural size.

### The list view
The list view is the thing which pops up when you show the selectpicker, it needs to be connected to a model and it could be used independently without a button view, allowing one to create completely custom views and showing the listview manually.

### Problems
There are a bunch of problems when considering doing a proper MVC within a jquery plugin, which is rather functional and has the opinion that state should be in the DOM instead of managed by a proper JS object.
* Does the model store the hidden `select` element and propagate changes to the views about changes the user makes when they call `refresh` ? Probably it must.
* Does one allow creating multiple `list view` widgets ? Perhaps the implementation is simplified by enforcing that there must be a 1:1 relationship between the list view and the model ?


In any case, I realise this would mean a large refactor and I don't expect it to write itself by magick, and unfortunately I don't have the time to focus on this myself, I just wanted to leave some ideas in the comment here.
