### ISSUE TITLE
Regression: select no longer fits the content height

### ISSUE THREAD

**Issue by gtristan** [silviomoreto/bootstrap-select#874]
When using data-content to set some image, bootstrap-select used to automatically cause the select button to require enough height to fit the content.

Here is an example of the breakage: http://jsfiddle.net/96f74jmL/

**Comment by gtristan** [comment]
Bisected problem down to this commit:

commit efe57bdcf73c12e226fbccfa1a4d602b3346804e
Author: César Kästli <cesarkastli@gmail.com>
Date:   Fri Oct 10 13:53:42 2014 -0300

    Adds 'form-control' class to the dropdown-toggle button

Looks like forcing 'form-control' on the button gives it a hard coded height, causing it to rebel against the content inside the button.

**Comment by caseyjhol** [comment]
Fixed.
