### ISSUE TITLE
Regression: data-container="body" causes select to popup below modal

### ISSUE THREAD

**Issue by gtristan** [silviomoreto/bootstrap-select#875]
This is another regression I found when trying master.

I need to use the data-container="body" for selects which appear inside scrollable content in modals.

Here is a demo of the problem with today's git version of bootstrap-select: http://jsfiddle.net/r6c80t4r/

**Comment by gtristan** [comment]
I've performed a bisection and found the regression comes from this commit:

commit e0dbad84d4492d0b03354d2ea55a1be97f630c61
Author: t0xicCode <xavier.l@t0xic.co.de>
Date:   Wed Aug 20 09:29:14 2014 -0400

    Reduced z-index values. Fixes #608

**Comment by rsertelon** [comment]
I've got the same problem, If I'm right, this fix was not even needed because it seems that the problem come from the select not closing correctly when a modal was opened...

See #608

**Comment by jacobbroberg** [comment]
I'm struggling with this issue as well. I can of course just overload the CSS in my own project, but that would just be a hack. 
Would it be possible to either revert e0dbad8 (if not really needed as @rsertelon indicates) and fix the real problem (if any) in #608. Or allow the user to set a `data-zindex` to manually override z-index to whatever seems right?
