### ISSUE TITLE
liveSearch: Text normalization seems unused

### ISSUE THREAD

**Issue by gtristan** [silviomoreto/bootstrap-select#877]
bootstrap-select does something with a normalizeToBase() function, however it seems the good intentions are missed.

A.) I need to manually normalize the text I add to data-tokens myself, this fixes case/accent insensitive searches but only half way.

B.) When entering/pasting text *with* accents in the entry, it fails to find matches.

**Comment by t0xicCode** [comment]
`normalizeToBase` is automatically called when generating the selectpicker. However, live search does not call it on its input by default. To turn on live search normalization, you need to set `liveSearchNormalize` to true (`searchAccentInsensitive` in 1.6.3).
