### ISSUE TITLE
Dividers are staying in livesearch results

### ISSUE THREAD

**Issue by caseyjhol** [silviomoreto/bootstrap-select#879]
Recreate:

Have a select with a data-divider it. Perform a search for an option not located in the select. Rather than showing the "no results" text, it simply shows the divider. Also, if an opt-group is being hidden, the opt-group's divider is staying behind. See here: http://jsfiddle.net/caseyjhol/tss4znof/.

I've created a patch but haven't set up a development environment yet to submit it. See 
http://jsfiddle.net/caseyjhol/cy752mee/3/ for the fix.

Relevant changes:

Line 460: 
```javascript
_li.push(generateLI('', null, 'divider', optID + 'div'));
```
Line 1003: 
```javascript
if (that.$lis.filter('[data-optgroup=' + optgroup + ']').not($this).filter(':not(.hidden)').length === 0) {
 $this.addClass('hidden');
 that.$lis.filter('[data-optgroup=' + optgroup + 'div]').addClass('hidden');
}
```
Line 1009:
```javascript
that.$lis.filter('.divider:not(.hidden)').each(function () {
 var $this = $(this)

 if (that.$lis.filter(':not(.hidden)').last().index() === $this.index() ||
    that.$lis.filter(':not(.hidden)').first().index() === $this.index()) {
     $this.addClass('hidden');
 }
});
```
Line 1018:
```javascript
if (!that.$lis.filter(':not(.hidden):not(.no-results)').length) {
```
Line 1036:
```javascript
that.$menu.find('li').filter(':not(.hidden):not(.divider)').eq(0).addClass('active').find('a').focus();
```
Hoping to get a chance to fix this in the coming days, but if you get a chance (@t0xicCode), please go ahead and patch it. I also updated `:visible` to `:not(.hidden)`.

**Comment by t0xicCode** [comment]
Basically, we need to hide the dividers when they are the first thing
visible, if they are followed by a divider, or if they are the last thing
visible.

You can take a crack at it. I might have time by Sunday.

**Comment by caseyjhol** [comment]
Oh yea. The code I posted is the fixed code. The function I added on line 1009 addresses the divider issue if it's first or last. The changes to 460 and 1003 hide the divider associated with the optgroup if the optgroup is hidden.

**Comment by t0xicCode** [comment]
Right. I sorta browsed over it ;)
