### ISSUE TITLE
Dont't work with ng-if

### ISSUE THREAD

**Issue by mateusz-c** [silviomoreto/bootstrap-select#881]
Hi , if I have in select ng-if condition the boostrap select is doubled after clicking the bootstrap select. In first load it works fine , but it become doubled after clicking.
I really need the ng-if , becouse I dont want to hide all with the selectpicker('hide'), I want to hide single select.

**Comment by caseyjhol** [comment]
Try using the angular-bootstrap-select directive. Also, try wrapping the select in a span with ng-if, rather than using ng-if with the select directly.
