### ISSUE TITLE
Hide selectpicker on init if select element display:none

### ISSUE THREAD

**Issue by hilyin** [silviomoreto/bootstrap-select#883]
Would it be possible to hide when initializing selectpicker, if the select element is display:none?

I am running into an issue where I want to use the selectpicker, but not on initial load. So I have the select with display:none, but selectpicker still displays the element when initialized.

**Comment by caseyjhol** [comment]
You can apply the `bs-select-hidden` class to the select (using v1.7.0). This class only hides select elements.
