### ISSUE TITLE
Show title for single select

### ISSUE THREAD

**Issue by RMK147** [silviomoreto/bootstrap-select#888]
Is there a way to show the title for a single select like you can for a multiple one?

**Comment by hellocosmin** [comment]
+1

This feature would be very useful. I have single selects that I don't want to have the first option checked by default. Instead, it would make sense for us to be able to define something like a title/placeholder, asking the user to choose an option.

**Comment by eat-sleep-code** [comment]
Another option is to set it to a multiple select dropdown, but limit the number of selected items to 1.

    <select multiple data-max-options="1" id="Choice" class="selectpicker form-control" title="What is your choice?" >
        <option value="No">No</option>
        <option value="Maybe">Maybe</option>
        <option value="Yes">Yes</option>
    </select>

**Comment by hellocosmin** [comment]
Hmm, that sounds even better. Sneaky. I like it :D 

Thanks for the heads-up!

**Comment by hellocosmin** [comment]
Actually there's a problem with using a multiple select like that: when clicking an option, the dropdown items do not go away. That's normal for multiple selects, but unexpected behavior for a single select.

**Comment by geekdevs** [comment]
+1 that is surprising the feature is not supported. My current workaround for this is adding disabled hidden option:

```
<option style="display: none" value="" selected disabled>Choose your option</option>
```

The only problem is that it is showing black and needs extra js to change color when option selected.
