### ISSUE TITLE
how to display png icons instead of gyp-icons

### ISSUE THREAD

**Issue by frndxyz** [silviomoreto/bootstrap-select#892]

**Comment by bstst** [comment]
I suppose you could try and use the data-content attribute, and add there whatever HTML you might need, not excluding images.

**Comment by nickbouton** [comment]
Using `data-content` works, but a more explicit way to specify an actual image via `data-image` attribute would be nice.

**Comment by caseyjhol** [comment]
Similar to #861. Closing this. Currently image icons must be set with CSS using the background property.

**Comment by dakotahNorth** [comment]
@nickbouton ... can you please post an example of data-content working. Clearly I was doing something wrong as I couldn't get this to work.

**Comment by nickbouton** [comment]
@dakotahNorth We ended up ditching this component entirely in favour of a solution that we could have a little more customization control over. Sorry to not be of more help, haven't looked at it in over a year.

**Comment by caseyjhol** [comment]
@dakotahNorth 

```html
<select class="selectpicker">
    <option data-content="<img src='image1.png'> Option 1">
</select>
