### ISSUE TITLE
Found element not higlighted

### ISSUE THREAD

**Issue by l0pez** [silviomoreto/bootstrap-select#893]
I have select with search field.
If i type letter the result is higlighted, and it is correct.
Otherwise, I have select with optiongroupt and search field, and than if i type letters the result is found but not highlighted. If i want to select the result i have to click it, not to tap enter.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case? Closing this until I get more information.
