### ISSUE TITLE
Expanded Dropdowns when multiple on page

### ISSUE THREAD

**Issue by andrade1379** [silviomoreto/bootstrap-select#894]
Hello guys.

I'm seeing this occur when I am trying to target multiple selects on a page. Here is what I'm doing to get this to work:

`jQuery('#edit-sort-bef-combine, #edit-submitted-package-freshness-date-day, #edit-submitted-package-freshness-date-month, #edit-submitted-package-freshness-date-year').addClass('selectpicker');`

`if ( /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent) ) {
      
      jQuery('.selectpicker').selectpicker({
        style: 'btn-sort',
        mobile: true
      });
  } else {

    jQuery('.selectpicker').selectpicker({
      style: 'btn-sort',
      dropupAuto: true
    });

  }`

Here are the selects:

`<select name="submitted[package_freshness_date][day]" id="edit-submitted-package-freshness-date-day" class="day form-select"></select>`
`<select name="submitted[package_freshness_date][month]" id="edit-submitted-package-freshness-date-month" class="month form-select"></select>`
`<select name="submitted[package_freshness_date][year]" id="edit-submitted-package-freshness-date-year" class="year form-select"></select>`

Funny thing is on this very same page there is a single select field above the three here and that's being styled correctly.

Is there something I"m missing here?

**Comment by caseyjhol** [comment]
Can you elaborate on the issue? What is happening that is different from what you're expecting?
