### ISSUE TITLE
data-content option shows code on option hover

### ISSUE THREAD

**Issue by emage** [silviomoreto/bootstrap-select#896]
If i am using the data-content option and if the mouse pointer is over the selected item it shows the jibberish code in the tooltip-like bubble

How can i disabled this option to show content in this tooltip

**Comment by Khrysller** [comment]
I am facing the same thing

**Comment by jgambarios** [comment]
Same here, related to #469 it seems it won't be fix it soon....

**Comment by caseyjhol** [comment]
Duplicate of #469.
