### ISSUE TITLE
Multiple select using keyboard

### ISSUE THREAD

**Issue by neonwired** [silviomoreto/bootstrap-select#904]
There's a bug with the multiple select when using keyboard, you can test this on the demo page (http://silviomoreto.github.io/bootstrap-select/) if you tab to the mulitple select example and select an option from the list using arrow keys and return it loses focus after the selection meaning the only way to select another option is to tab all the way through the page back to the multiple select.

**Comment by caseyjhol** [comment]
Docs updated. This is now fixed.
