### ISSUE TITLE
Cannot open dropdown menu

### ISSUE THREAD

**Issue by tjwebb** [silviomoreto/bootstrap-select#909]
The dropdown button renders and shows the first `<option>` value, but when I click it to show the options, nothing happens.

**Comment by sylow** [comment]
+1

**Comment by Izopi4a** [comment]
I got the same problem under mobile after appending options and firing "refresh"

**Comment by jaukia** [comment]
+1

**Comment by salehliam** [comment]
The same problem here, interesingly enough it worked well before in my case.

**Comment by jaukia** [comment]
I got my issue fixed, in my case it was a typo in URL when loading one of the JS libs.

**Comment by salehliam** [comment]
I've checked the refrences, seem perfectly fine.

**Comment by salehliam** [comment]
Fixed, I loaded some jquery libs twice.

**Comment by caseyjhol** [comment]
Can anybody reproduce this issue with a reduced test case?

**Comment by dougfarre** [comment]
This started happnening after I upgrade from rails 4.1.8 to 4.2.0. The boostrap toggle-dropdown feature is also not working (I imagine they are related?).

**Comment by caseyjhol** [comment]
This doesn't appear to be an issue related to bootstrap-select. Closing this until somebody can provide an example.
