### ISSUE TITLE
Option dropdownAlignRight

### ISSUE THREAD

**Issue by mewsoft** [silviomoreto/bootstrap-select#913]
I see the option ```dropdownAlignRight``` but not documented. 
Can this option be passed with the data attribute like ```data-dropdownAlignRight="true"```

**Comment by caseyjhol** [comment]
It would be `data-dropdown-align-right="true"`.

**Comment by mewsoft** [comment]
Yes this is perfect  ```data-dropdown-align-right="true"```

**Comment by chandon** [comment]
data-dropdown-align-right="true" alignment is working with default "fixed-width" button but not working well with an automatic adaptative size for the button

    .btn-group.bootstrap-select {
        width: inherit !important;
    }

![image](https://cloud.githubusercontent.com/assets/4522557/6355208/8da39ea2-bc54-11e4-8fd2-09ae30cf79b8.png)
