### ISSUE TITLE
In IE 11, while scrolling the list, there is some weird overlay over the options.

### ISSUE THREAD

**Issue by ykiran** [silviomoreto/bootstrap-select#914]
In IE 11, when the drop down is opened, and the list is slowly scrolled, a weird grey color blanket is overlaid over the options. I believe the grey color comes from the options' border color.

When the scroll bar is vigorously shook / jerked, the overlay disappears. I've attached a screenshot for reference.

![ie11_options_bug](https://cloud.githubusercontent.com/assets/5526410/6123527/d7200c22-b129-11e4-9384-e074472f260f.jpg)

**Comment by caseyjhol** [comment]
Can you link me to an example or a reduced test case?

**Comment by caseyjhol** [comment]
Closed due to inactivity - most likely a CSS issue.
