### ISSUE TITLE
Title is overriden by data-content

### ISSUE THREAD

**Issue by Andarist** [silviomoreto/bootstrap-select#920]
In my opinion defining a title for option is far way more important than it's content, where content is used (at least by me) for puting img's into dropdowns, however for selected item I would strongly prefer to have text displayed instead of that img.

its at 380 line and fix would look like this (just order of conditioning is changed)
        if (typeof $this.attr('title') !== 'undefined') {
          return $this.attr('title');
        } else if ($this.data('content') && that.options.showContent) {
          return $this.data('content');
        }
        /*if ($this.data('content') && that.options.showContent) {
          return $this.data('content');
        } else if (typeof $this.attr('title') !== 'undefined') {
          return $this.attr('title');
        }*/

**Comment by dannief** [comment]
I just noticed this issue as well. I think common use case is that if title is specified then it should be the display value even if data-content is specified

**Comment by Andarist** [comment]
Yep, that was exactly what I ment, as I'm not familiar with forking yet and I would like to be able to use future releases of this plugin I've used MutationObservers to accomplish what I want, although it is not ideal solution.

**Comment by dannief** [comment]
This seems to fixed in the latest version on github. The CDN version is not yet updated.
