### ISSUE TITLE
Bootstrap-select popup position

### ISSUE THREAD

**Issue by IvoPereira** [silviomoreto/bootstrap-select#930]
Hello,

I would like to know how can I specify a specific position for the popup to appear.

As I have a lot of elements, popup has space to open in the top. However, when searching through the items and the list gets smaller, it does go to bottom, and it looks very weird.

Any suggestions?

**Comment by caseyjhol** [comment]
Set `dropupAuto: false`.

From the docs:

> `dropupAuto` is set to true by default, which automatically determines whether or not the select should be a dropup. If `dropupAuto` is set to false, manually make the select a dropup menu by adding the `.dropup` class to the select.
