### ISSUE TITLE
Can user edit the option?

### ISSUE THREAD

**Issue by RockyNiu** [silviomoreto/bootstrap-select#935]
Hello,

Would you please provide a new method: when user do search, if the key word doesn't exist, user can save the new word by some way?

The attached is my codes (sorry for the ugly, I am a newbie though) by providing a save button.

Thank you!

// modifying bootstrap-select function
// add a save button to save new input option
// selectId is the id of original select
// $.randomId() generates a new uuid

function searchComboBox(selectId, callback) {
    $("#" + selectId).next().find("input").on('input propertychange', function () {
        var addOn = $("#" + selectId).next();
        var btnId = "btn" + $.randomId();
        if (!addOn.find('ul.selectpicker').find('li').filter(':visible:not(.no-results)').length) {
            addOn.find("li.no-results button").remove();
            addOn.find("li.no-results").append('<button id="' + btnId + '" type="button" class="btn btn-sm pull-right">save</button>'); // append a save button (my codes were not shown here)
        }
        $("#" + btnId).click(function () {
            callback();
        });
    });
}

**Comment by caseyjhol** [comment]
See #847.

**Comment by caseyjhol** [comment]
Please subscribe to #990.
