### ISSUE TITLE
Bootstrap tooltip on select

### ISSUE THREAD

**Issue by LDSign** [silviomoreto/bootstrap-select#938]
Hi

One of my selects has a confirgured bootstrap tooltip.

Without "bootstrap-select" this tooltip shows up as expected. But with "bootstrap-select" the orginal select is hidden and the data attributes are not copied to the styled select. So no tooltip :(

Have I missed any option or do I have to do a dirty hack?

Thanks,
Frank

**Comment by caseyjhol** [comment]
If you're using the bootstrap-select data-api to initialize the selectpicker, you'll need to assign the tooltip to the selectpicker's container. Something like: 

```javascript
    $('body').tooltip({
        selector: '.selectpicker',
        container: 'body',
        placement: 'bottom'
    });
```

If you're manually calling `$('.selectpicker').selectpicker()`, simply initialize call `tooltip()` afterward.

**Comment by LDSign** [comment]
HI

Thanks for your help. But I am not sure what you mean ;)

This is my code within document.ready:

	$('select.select-picker').selectpicker({
		actionsBox: true,
		dropupAuto: false
	});

	$('[data-toggle="tooltip"]').tooltip({
		container: 'body'
	});

What should I adjust here?

Thanks,
Frank

**Comment by caseyjhol** [comment]
`'[data-toggle="tooltip"]'` selects the `select` element, not the `button` element, so the tooltip is being applied to the hidden select. You'll want to do something like:

```javascript
$('[data-toggle="tooltip"], [data-toggle="tooltip"] + .bootstrap-select > button').tooltip({
    container: 'body
'});

**Comment by Bruskyer** [comment]
Hi
Im using bootstrap and bootstrap select with dynamic data (from web service, like country list) also I use liveseach everything is ok but I need to add tooltip with same text when move mouse over each item but I can't I only made it for static option "value" or option title "text" how is it possible to implement this feature.
regards
thanks
