### ISSUE TITLE
live search with selectpicker('mobile') enabled

### ISSUE THREAD

**Issue by sscotti** [silviomoreto/bootstrap-select#939]
Just wondering if live search works on a mobile device when you enable the mobile device select list.  Apparently not.  I actually like the native mobile device interface better the the bootstrap-select interface for the mobile device.  It works fine in my browser and probably even on an iPad, but for a phone the mobile device interface has a smaller and more accessible interface.

An related or unrelated issue is that I am using live-search for a select on my web site.  I have a total of 6 bootstrap select select lists, 4 in one form and 2 in another.  I am initializing them with jQuery $(document).ready and $('.selectpicker').selectpicker(); with no arguments.  I am using the data-x in each element to configure them individually.

I am using using:

    	if( /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent) ) {
    		$('.selectpicker').selectpicker('mobile');
		}
to enable the mobile picker, which is working also, except for the live-search feature.  There is no input field, which I can understand since it is using the mobile interface.

They all initialize and seem to work pretty well.  However, The 2 select lists in the second form are configured for live search and have the input field in the drop down, but the search isn't working.  It isn't filtering the list.  Probably something I don't have configured correctly.

It is on a development site at:  http://www.loscabosairportshuttles.com  

It is .htaccess protected, but you could sign in with:  sscotti, olorin!1 if you wanted to look at it.

I think that I sent you a previous question about the tab order.  You could examine that at the same time.  Basically, if you tab through the fields it skips over the bootstrap select elements.

The live-search isn't a killer for Smartphones, but it is a nice feature for long lists, like the destinations.  That one is working, it is the following ones for the airlines that are not working.

Thanks.

**Comment by sscotti** [comment]
This might have something to do with it.  I am seeing a js error in Safari.

null is not an object (evaluating '/^[^?#]*\//.exec(location.href)[0]')

**Comment by caseyjhol** [comment]
Hrmm...what exactly is the issue here? liveSearch doesn't work with mobile enabled as it uses the device's UI. That can't be changed. Although, we could offer a responsive option in the future that would display a bootstrap-select style menu that fills up the screen and allows for search and other bootstrap-select features.
