### ISSUE TITLE
JQMIGRATE: jQuery.fn.attr('selected') may use property instead of attribute 

### ISSUE THREAD

**Issue by sylouuu** [silviomoreto/bootstrap-select#94]
Hello,

The title is clear, use <code>.prop('selected', true)</code> instead of <code>.attr()</code>

Regards

**Comment by gravelld** [comment]
Hmmm, for me, JQuery 1.8.3 and Chrome 38.0.2125.104 (also FF) only attr works... In the click handler:

          if (!that.multiple) { // Deselect all others if not multi select box
            $options.prop('selected', false);
            $option.prop('selected', true);
            that.$menu.find('.selected').removeClass('selected');
            that.setSelected(clickedIndex, true);

The lines 2-3 don't change the selected status of the original `<select>`. Note the dropdown is successfully changed. If I go in and change those `prop`s to `attr` it works...
