### ISSUE TITLE
No overflow with FuelUX wizard

### ISSUE THREAD

**Issue by Leobaillard** [silviomoreto/bootstrap-select#943]
Hi there!

I'm not sure that this is the right place for this issue, so if that is not the case, feel free to let me know!

I'm constructing a wizard on my admin portal using various components and among them FuelUX, for the actual wizard, and bootstrap-select for some of the lists.

My problem is that, when a choice list is opened and the list's height is greater than the step-pane of the wizard it sits on, there is no overflow: meaning, the rest of the list is hidden, making it impossible to select members at the end of the list.

Here is a picture for better understanding:
![overflow-fail](https://cloud.githubusercontent.com/assets/402250/6364104/ebc0a258-bca1-11e4-9e39-d6c32d2594b0.png)

Now, I'm not a CSS expert but I tried to fiddle around in my browser, but CSS being what it is, and moreover, the CSSs of bootstrap-select and FuelUX being what they are (quite long and complicated for me), I couldn't come up with a good fix...

Do you have any ideas on how to solve this? Or at least pointers as to where I should look/tweak?

Thanks so much for this great component, and in advance for any help you might provide.

**Comment by caseyjhol** [comment]
You might want to try setting `data-container="body"`. See http://silviomoreto.github.io/bootstrap-select/#container

**Comment by Leobaillard** [comment]
Oops... I feel stupid I did not read the documentation carefully enough...

Thanks @caseyjhol, it worked of course.

**Comment by gsesito** [comment]
Hi,
I had the same problem but with other bootstrap component like https://github.com/Eonasdan/bootstrap-datetimepicker. Step pane hides datetime panel making it impossible to select date & time. data-container="body" doesn't works.

//a small image as part of screenshoot 

![wizardissue](https://cloud.githubusercontent.com/assets/11755262/6942528/75ebaf70-d888-11e4-8096-62e6d6c12d43.png)
