### ISSUE TITLE
Cancel the change with modal bootstrap

### ISSUE THREAD

**Issue by Emyleen** [silviomoreto/bootstrap-select#946]
Hello! I have a question:  It is possible to cancel the change of the select with a confirm modal from bootstrap? I tried this but it doesn't work :/ http://www.bootply.com/iSeFO0yxDI

Thank you for your answer!

**Comment by caseyjhol** [comment]
You'll want to store the previous value, pop up the alert, and if they click "Cancel" then set the value of the select to its original value. Then, call `selectpicker('refresh')`.
