### ISSUE TITLE
Programmatically open the menu

### ISSUE THREAD

**Issue by mewsoft** [silviomoreto/bootstrap-select#950]
Is there a way to programmatically open the menu same effect as click the button to open, currently I am using this:

```
<select id="selectID">
...
</select>
```

```
$('[data-id="selectID"]').trigger('click');
```

**Comment by breiko83** [comment]
I do need the same behaviour, but your solution doesn't work for me.
Is there any other workaround?

**Comment by Jogai** [comment]
If you want it just to open as soon as the selectpicker is applied, you can just provide the open class on the original select element.

**Comment by turigeza** [comment]
In case anybody looking for the same thing.

Open Menu 
$('.selectpicker').addClass('open');
$('.selectpicker').selectpicker('refresh');

Close Menu
$('.selectpicker').removeClass('open');
$('.selectpicker').selectpicker('refresh');

**Comment by MilenFrom** [comment]
Is there a way to keep it always open?
Even the page is refreshed or its clicked outside of the element?

**Comment by Jogai** [comment]
@turigeza Just use the open & close methods for that: http://silviomoreto.github.io/bootstrap-select/methods/#selectpickerhide

@MilenFrom apply the open class on the select (in html)

**Comment by MilenFrom** [comment]
Hi @Jogai I tried this and didn't work.
However, my solution was to trigger adding display:block; to the dropdown element on document change.

Code:
$(document).on('change','body',function(){
     $('.dropdown-menu').css('display','block');
});

**Comment by Jogai** [comment]
how do you initialize the component?

**Comment by MilenFrom** [comment]
Hi @Jogai 

First I've set a custom class to the form and initialized Bootstrap-Select for it.
`$('.skillselect').selectpicker('toggle');` 
Then added display block to the dropdown menu of this class
`$('div.skillselect > div.dropdown-menu').css('display','block');`
Then added a check when something is changed on the body, as example item is chosen or the user clicks outside of this element to keep the display property block.
`$(document).on('change','body',function(){
	$('div.skillselect > div.dropdown-menu').css('display','block');
});`

You can see the demo to see it how its working.
[https://nuboyana.com/edit-profile/skills/?nocache=1](https://nuboyana.com/edit-profile/skills/?nocache=1)

On the same site you can see other forms without this feature but with another class and they're working just fine.
[https://nuboyana.com/edit-profile/details/?nocache=1](https://nuboyana.com/edit-profile/details/?nocache=1)

**Comment by Jogai** [comment]
Ok, you want it to stay open, thats slightly different. 

This should be enough (though not compatible with screenreaders):

`$('select').selectpicker('show');

$('.dropdown-menu').css('display','block');`
