### ISSUE TITLE
Item selected in dropdown wrong when calling .selectpicker("val", val)

### ISSUE THREAD

**Issue by gwendall** [silviomoreto/bootstrap-select#965]
When manually setting the value to a selectpicker, the selected item in the dropdown does not follow.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case?
