### ISSUE TITLE
404 Error Loading the .map File from NuGet Installation

### ISSUE THREAD

**Issue by ddelella** [silviomoreto/bootstrap-select#966]
When installing the bootstrap-select plug-in from NuGet via ASP.NET the script files are installed into a folder called Scripts in the root of the project.  In the bootstrap-select.min.js file there is a line of code:

//# sourceMappingURL=bootstrap-select.js.map

This line points to the map file.  However, for the NuGet installation the path should be:

//# sourceMappingURL=Scripts/bootstrap-select.js.map

**Comment by caseyjhol** [comment]
Fixed in 1.7.2
