### ISSUE TITLE
options don't work with ng-repeat

### ISSUE THREAD

**Issue by thouse75** [silviomoreto/bootstrap-select#967]
see the following jsfiddle: http://jsfiddle.net/thouse75/L0b4pyo9/1/

this prevents you from using the data-content / data-icon attributes.

**Comment by caseyjhol** [comment]
You need to run `selectpicker('refresh')` wrapped in setTimeout.

```js
  angular.module('myApp', [])
    .controller('MainCtlr', ['$scope', '$timeout', function($scope, $timeout) {
      $scope.list = [1, 2, 3, 4, 5];
        $timeout(function() {
            $('.selectpicker').selectpicker('refresh');
        });
    }]);
```

If you're going to be using bootstrap-select with AngularJS, I recommend you check out https://github.com/joaoneto/angular-bootstrap-select and http://stackoverflow.com/questions/28336106/angular-bootstrap-select-timing-issue-to-refresh.
