### ISSUE TITLE
Dropdown List display behind the bootstrap table-responsive element

### ISSUE THREAD

**Issue by M1chae1** [silviomoreto/bootstrap-select#972]
**Environment**
bootstrap 3.3.2
jQuery 2.1.3
bootstrap-select 1.6.4

**Expected Result**
![expected](https://cloud.githubusercontent.com/assets/5714586/6701871/8c9296a2-cd5d-11e4-8728-b0c6a44aedd8.png)

**Problem Result**
![problem](https://cloud.githubusercontent.com/assets/5714586/6701873/904fab2c-cd5d-11e4-9101-e14f0853090c.png)

**Sample URL**
http://jsfiddle.net/micwallo/fn2xs923/

**Code**
```html
<div class="table-responsive">
	<table class="table">
		<thead>
			<tr><th>Text</th>
				<th>DropDown</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Hello!</td>
				<td><select name="CurrencyISOCode" id="CurrencyISOCode" class="selectpicker">
					<option value="HKD">CAD</option>
					<option value="HKD">TWN</option>
					<option value="HKD">RMB</option>
					<option value="USD">USD</option>
					<option value="HKD">HKD</option>
					</select>
					
				</td>
			</tr>
		</tbody>
	</table>
</div>
```

**Comment by gdanen** [comment]
I have similar behaviour, but I don't use table-responsive. I can't pinpoint what class is doing it (if it is class related at all).

![image](https://cloud.githubusercontent.com/assets/8509049/6912801/fa84595e-d733-11e4-9f5a-8bed681bdb6d.png)

**Comment by caseyjhol** [comment]
This appears to be working fine for me in Chrome, Firefox, and IE11. If you can't find a workaround, I recommend setting `data-container` or `overflow: visible;` on its parent. If you can provide me with another example and some more information I'll reopen this.

**Comment by gdanen** [comment]
*data-container=**"body"* on the select did the trick. The overflow:visible
was not required.

Thank you for your help!

Gerry

**Comment by diksen0131** [comment]
kjkljkljkl

**Comment by Kokleng-Dev** [comment]
Sir, for data-container="body", it move the option to the body tag, I want it show in cell and display over overflow-scroll. I want a responsive table (scroll-x) and when click the bootstrap-select make it show list of options. Please help me, Thank you
