### ISSUE TITLE
Bootstrap 3 data-style does not work in v1.6.4

### ISSUE THREAD

**Issue by Jcerwin** [silviomoreto/bootstrap-select#973]
Bootstrap 3 <code>data-style</code> worked in v1.6.3, but no longer appears to work in v1.6.4. The issue can be demonstrated when using button sizing (control height): <code>data-style="btn btn-default btn-xs"</code>

1.6.3 example (btn-xs works): http://jsfiddle.net/jcer/naoqrxr2/
1.6.4 example (btn-xs does not work):  http://jsfiddle.net/jcer/zh0ymdeh/

**Comment by caseyjhol** [comment]
It's not working with the latest stable release, but this was fixed in c0a7414fef20786e42078bcfbd9d628ae7041b80. See https://github.com/silviomoreto/bootstrap-select/tree/master/dist/js
