### ISSUE TITLE
text selection not updated when an option w/ same value is selected

### ISSUE THREAD

**Issue by ekeneijeoma** [silviomoreto/bootstrap-select#974]
When you select an option which has the same value as another option the selection doesnt change.

```
<select> 
<option value="1">item 1</option>
<option value="1">item 2</option>
<option value="2">item 3</option>
</select>
```

If item 1 or 2 are selected it defaults to item 1.

**Comment by caseyjhol** [comment]
This appears to have been fixed after the setSelected() function was changed. If not, please link me to a jsfiddle.
