### ISSUE TITLE
Support input-lg sizing

### ISSUE THREAD

**Issue by thiagof** [silviomoreto/bootstrap-select#975]
Old issue, fixed: https://github.com/silviomoreto/bootstrap-select/issues/694

Somehow the commit got out of current releases

**Comment by 0x3333** [comment]
I have the same issue with input-sm.

I add btn-sm in the button generated and it works great.

**Comment by gwrey** [comment]
I fixed this by making the following update.  It translates any input-* classes on the select to btn- classes on the button.

Original code:
```
    setStyle: function (style, status) {
        if (this.$element.attr('class')) {
            this.$newElement.addClass(this.$element.attr('class').replace(/selectpicker|mobile-device|validate\[.*\]/gi, ''));
        }
```

New code:
```
    setStyle: function (style, status) {
        if (this.$element.attr('class')) {
            var selectClass = this.$element.attr('class').replace(/selectpicker|mobile-device|validate\[.*\]|form-control/gi, '');
            this.$button.addClass(selectClass.replace(/input-/g, "btn-"));
        }
```

**Comment by ghost** [comment]
Please re-open this, as sizing is not working as expected.

```
$('.selectpicker').selectpicker({
    style: 'input-lg'
});
```

No class is being outputted, and the dropdown just remains as standard sizing.
