### ISSUE TITLE
Not working well with jQuery Validation

### ISSUE THREAD

**Issue by thdoan** [silviomoreto/bootstrap-select#978]
Bootstrap-select doesn't play nicely with the jQuery Validation plugin. When the select element is left empty, the "error" class is properly added, but when the select element becomes valid (non-empty value), the "error" class is not removed. Here's a fiddle:

http://jsfiddle.net/10basetom/4402y5h1/

**Comment by thdoan** [comment]
I found a solution that is acceptable, so closing...

```
  // Make Bootstrap-select play nicely with jQuery Validation
  $('select.selectpicker').change(function() {
    $(this).valid();
  });
```

**Comment by noguer19** [comment]
Nice!! i spent some hours trying to find a solution for this issue. Thanks 👍
