### ISSUE TITLE
OptGroup labels in Live Search

### ISSUE THREAD

**Issue by mwkeller** [silviomoreto/bootstrap-select#982]
I'm not quite sure if this is a bug or an enhancement request but when using live search with data that includes OptGroups, the OptGroup labels still appear in the dropdown even if there are no matching options within them.

**Comment by CepheiA** [comment]
+1

**Comment by robholmes** [comment]
:+1: This is a must have for large data sets with lot's of groups.

**Comment by caseyjhol** [comment]
Fixed in v1.6.4.
