### ISSUE TITLE
btn sizes

### ISSUE THREAD

**Issue by Khrysller** [silviomoreto/bootstrap-select#992]
btn sizes doesn't seen to be working:

https://jsfiddle.net/aufozkgh/

**Comment by neotropic2023** [comment]
Weird. They seem to work for me.

**Comment by Khrysller** [comment]
can you share a picture?

**Comment by MrGeneric** [comment]
Here's what I see.

![image](https://cloud.githubusercontent.com/assets/3923223/7063352/dc9344fc-de9d-11e4-84e8-a1a897ad230a.png)

**Comment by Khrysller** [comment]
@MrGeneric, the same as me. And I assume this is not ok.

**Comment by MrGeneric** [comment]
Yeah, there's a Bootstrap form-control class being added which sets the height to 34px for each of them.

**Comment by caseyjhol** [comment]
This was fixed in c0a7414fef20786e42078bcfbd9d628ae7041b80, after the 1.6.4 release. Using the latest version should fix your problem.

https://github.com/silviomoreto/bootstrap-select/compare/v1.6.4...master
