### ISSUE TITLE
Selectpicker slow to load

### ISSUE THREAD

**Issue by enyosolutions** [silviomoreto/bootstrap-select#995]
Hello,

I'm having a bit a of problem with the selectpicker. It's taking a bit of time to get styled. SO when the page load, the select appears unstyled before actually becoming styled. 

Is there a way to avoid that ? 

the trouble can be seen here http://www.kenweego.com

**Comment by thomas-parrish** [comment]
I'm noticing this as well. It seems like older version did not have this issue?

**Comment by benatwork99** [comment]
I notice this as well. I tried 1.6.2 and it was a little faster but not much faster.

We have many select controls on the page and this delay at startup is a problem. 

For a select control with 50 options it takes latest Firefox on my machine about 40ms per item to setup. On IE8 it's taking around 300ms. If you have a few of them on the page the delay is enough to show 'slow running script' warnings.

Is there any good approach here other than trying to not instantiate so many of the controls at page load time?

**Comment by caseyjhol** [comment]
Please try v1.7.0-rc2 and report back.

**Comment by thomas-parrish** [comment]
SO much faster!

**Comment by benatwork99** [comment]
Major improvement - that same test in Firefox now takes 15ms per item (used to be 40ms). 

Thanks and nice work!
