### ISSUE TITLE
dropdown menu is overlapped by bootstrap menu bar

### ISSUE THREAD

**Issue by schlussbilanz** [silviomoreto/bootstrap-select#996]
Hi,

i have the problem that if the dropdown menu is open the bootstrap menu bar overlaps it. 
How can i set the dropdown menu always in foreground?
z-index doesn't help...

Greets schlussbilanz

**Comment by eroltoker** [comment]
I also have this issue.

**Comment by caseyjhol** [comment]
See [guidelines for contributing](https://github.com/silviomoreto/bootstrap-select/blob/master/CONTRIBUTING.md). Any chance you can link me to a demo or jsfiddle? Have you been able to reproduce this with a reduced test case?

**Comment by mksoftpoint** [comment]
Please find a very simple test html on http://webtest3.softpoint.de/bug.html.
The bug can be corrected in this example by adding the following line to 
**bootstrap-select.css** after line **37**:
*z-index: auto;*
