### ISSUE TITLE
First optgroup label is shifted/broken when data-actions-box = true

### ISSUE THREAD

**Issue by meetmagdalene** [silviomoreto/bootstrap-select#998]
![optgroup-label-bug](https://cloud.githubusercontent.com/assets/1317384/7203717/41fcc08a-e4e2-11e4-84b5-1ca3c8acc3e0.PNG)

I'd like to continue using the data-actions-box but I also need some group labels because this select list is going to be very long. Has anyone else noticed this issue? Or is it currently on the list to be addressed? 

I searched the existing and previous issues and didn't find anything documented about it or a fix.

This is my code: 
```
<select id='select-customer' class='selectpicker form-control' data-actions-box="true" data-size="15" multiple data-selected-text-format="count>2">
    <optgroup label="CustomerGroup">
        <option>Customer 1.1</option>
        <option>Customer 1.2</option>
	<option>Customer 1.3</option>
    </optgroup>
    <optgroup label="CustomerGroup2">
        <option>Customer 2.1</option>
	<option>Customer 2.2</option>
	<option>Customer 2.3</option>
    </optgroup>
</select>
```

**Comment by caseyjhol** [comment]
What browser/OS are you using? Are you sure you don't have some interfering CSS on the page? Can you create a reduced test case and link me to it?

**Comment by meetmagdalene** [comment]
Thanks for checking in with me. It must have had something to do with CSS interference because when I just went back to test again to reply to this it is in the place it is supposed to be now.

Thanks anyway!
