### ISSUE TITLE
Conflict with Events Manager wordpress plugin

### ISSUE THREAD

**Issue by lsterling03** [silviomoreto/bootstrap-select#999]
I've got bootstrap-select working fine in my wordpress template, but when I activate the Events Manager plugin, all the dropdowns are permanently opened (they all have the class of "open") no matter what I do. 

Even if I completely remove the initializing code ($('.selectpicker').selectpicker()), but leave the bootstrap-select.min.js file loaded in the footer, it still forces all select boxes with the selectpicker class to remain open.

I've tried manually loading bootstrap + bootstrap-select files before the
Events Manager plugin files (which load in the head not the footer, btw), and that didn't work either. 

Do you know why this is happening?

Events Manager:
http://wp-events-plugin.com/

Note: I tried a different select box script (SelectBoxIt) and that one did not have a conflict with Events Manager, if that helps you track down the issue.

**Comment by caseyjhol** [comment]
This seems more like an issue with Events Manager than bootstrap-select. If you can link me to an example, I'd be happy to take a look. Closing this in the meantime.
